const { loadEnvConfig } = require('@next/env');
loadEnvConfig(process.cwd());
const { createClient } = require('@supabase/supabase-js');

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
);

const fastingModalities = [
  {
    id: 'intermittent_fasting_18_6',
    slug: 'intermittent-fasting-18-6',
    name: 'Time-Restricted Eating (18:6)',
    display_name: 'Time-Restricted Eating (18:6)',
    modality_type: 'fasting',
    category: 'Fasting & Autophagy',
    status: 'active',
    brief_description: 'An 18-hour daily fasting window followed by a 6-hour eating window to boost AMPK activation, glycogen depletion, and fat oxidation.',
    headline_benefit: 'Enhanced Fat Burning & AMPK Pathway Activation',
    expanded_why: 'Extending the daily fast from 16 to 18 hours significantly deepens glycogen depletion and stimulates early autophagy while promoting insulin sensitivity.',
    primary_outcome: 'Fat Oxidation & Insulin Sensitivity',
    secondary_outcomes: ['Cellular Autophagy', 'Mental Clarity', 'Metabolic Flexibility'],
    overall_longevity_benefit: 4,
    implementation_summary: 'Fast for 18 consecutive hours daily (e.g. 7 PM to 1 PM). Consume all calories within a 6-hour window.',
    instructions: 'Maintain an 18-hour fast drinking only water, black coffee, or plain tea. Break your fast with a nutrient-dense, protein-rich meal.',
    dose_or_exposure: '18 hours fasting / 6 hours eating',
    timing_summary: 'Daily 18-hour fast window',
    frequency: 'Daily or 5x per week',
    schedule_pattern: 'daily_fasting',
    difficulty: 'moderate',
    cost_tier: 'free',
    effort_level: 'low',
    time_to_benefit: '3-5 days',
    evidence_quality: 4,
    effect_size_estimate: 4,
    safety_level: 'low_risk',
    logging_type: 'fasting',
    cadence_layer: 'daily',
    functional_impacts: {
      "Fat Burning": { score: 9 },
      "Autophagy": { score: 7 },
      "Metabolic Health": { score: 9 }
    }
  },
  {
    id: 'intermittent_fasting_20_4',
    slug: 'intermittent-fasting-20-4',
    name: 'Warrior Diet Fasting (20:4)',
    display_name: 'Warrior Diet Fasting (20:4)',
    modality_type: 'fasting',
    category: 'Fasting & Autophagy',
    status: 'active',
    brief_description: 'A 20-hour daily fast with a 4-hour evening eating window for deep cellular cleanup and growth hormone stimulation.',
    headline_benefit: 'Deep Glycogen Depletion & HGH Surge',
    expanded_why: '20 hours of fasting triggers substantial autophagy in liver and muscular tissue while dramatically elevating growth hormone levels.',
    primary_outcome: 'Autophagy Induction & HGH Elevation',
    secondary_outcomes: ['Visceral Fat Loss', 'Inflammation Reduction'],
    overall_longevity_benefit: 4,
    implementation_summary: 'Fast for 20 hours daily. Consume nutrient-dense meals within a 4-hour evening window.',
    instructions: 'Drink water, electrolytes, and unflavored tea during the 20-hour fasting period.',
    dose_or_exposure: '20 hours fasting / 4 hours eating',
    timing_summary: 'Daily 20-hour fast',
    frequency: '3-5x per week',
    schedule_pattern: 'intermittent_fasting',
    difficulty: 'hard',
    cost_tier: 'free',
    effort_level: 'medium',
    time_to_benefit: '1 week',
    evidence_quality: 4,
    effect_size_estimate: 4,
    safety_level: 'low_risk',
    logging_type: 'fasting',
    cadence_layer: 'daily',
    functional_impacts: {
      "Autophagy": { score: 8 },
      "HGH Elevation": { score: 8 },
      "Fat Loss": { score: 9 }
    }
  },
  {
    id: 'omad_fasting',
    slug: 'omad-fasting',
    name: 'OMAD (One Meal A Day Fasting)',
    display_name: 'OMAD (One Meal A Day)',
    modality_type: 'fasting',
    category: 'Fasting & Autophagy',
    status: 'active',
    brief_description: 'Fast for ~23 hours each day and consume all daily calories in a single 1-hour feast meal.',
    headline_benefit: 'Maximum Daily Autophagy & Insulin Reset',
    expanded_why: 'OMAD maximizes daily autophagy and gives the gut and metabolic pathways 23 uninterrupted hours of rest.',
    primary_outcome: 'Insulin Sensitivity & Weight Management',
    secondary_outcomes: ['Gut Microbiome Rest', 'Cellular Autophagy'],
    overall_longevity_benefit: 4,
    implementation_summary: 'Eat 1 large meal daily within 60 minutes. Fast for the remaining 23 hours.',
    instructions: 'Ensure your single meal contains adequate protein, healthy fats, and micronutrients.',
    dose_or_exposure: '23 hours fasting / 1 hour meal window',
    timing_summary: 'Single daily meal',
    frequency: '2-4x per week',
    schedule_pattern: 'intermittent_fasting',
    difficulty: 'hard',
    cost_tier: 'free',
    effort_level: 'medium',
    time_to_benefit: '3-7 days',
    evidence_quality: 4,
    effect_size_estimate: 4,
    safety_level: 'low_risk',
    logging_type: 'fasting',
    cadence_layer: 'daily',
    functional_impacts: {
      "Autophagy": { score: 9 },
      "Gut Health": { score: 8 },
      "Insulin Reset": { score: 9 }
    }
  },
  {
    id: 'water_fast_24h',
    slug: 'water-fast-24h',
    name: '24-Hour Water Fast (Dinner-to-Dinner)',
    display_name: '24-Hour Water Fast',
    modality_type: 'fasting',
    category: 'Fasting & Autophagy',
    status: 'active',
    brief_description: 'A full 24-hour fast from dinner one day to dinner the next day once per week.',
    headline_benefit: 'Weekly Autophagy Peak & Immune Cell Recycling',
    expanded_why: 'Crossing the 24-hour mark induces systemic autophagy and resets digestive and metabolic pathways.',
    primary_outcome: 'Systemic Autophagy & Immune Recycling',
    secondary_outcomes: ['Cellular Cleanout', 'Weight Maintenance'],
    overall_longevity_benefit: 4,
    implementation_summary: 'Eat dinner on Day 1, fast through breakfast and lunch on Day 2, eat dinner on Day 2.',
    instructions: 'Drink plenty of water and add 500mg sodium / electrolytes as needed throughout the 24 hours.',
    dose_or_exposure: '24 consecutive hours fasting',
    timing_summary: '1x per week fast',
    frequency: '1x per week',
    schedule_pattern: 'weekly_fasting',
    difficulty: 'hard',
    cost_tier: 'free',
    effort_level: 'medium',
    time_to_benefit: '1 day',
    evidence_quality: 4,
    effect_size_estimate: 4,
    safety_level: 'low_risk',
    logging_type: 'fasting',
    cadence_layer: 'weekly',
    functional_impacts: {
      "Autophagy": { score: 9 },
      "Immune Reset": { score: 8 }
    }
  },
  {
    id: 'monk_fast_36h',
    slug: 'monk-fast-36h',
    name: '36-Hour Monk Fast (Alternate Day Fasting)',
    display_name: '36-Hour Monk Fast',
    modality_type: 'fasting',
    category: 'Fasting & Autophagy',
    status: 'active',
    brief_description: 'Fast for a full day plus two nights (e.g. stop eating Sunday 8 PM, break fast Tuesday 8 AM).',
    headline_benefit: 'Deep Autophagy, Ketosis & Stem Cell Rejuvenation',
    expanded_why: '36-hour fasts trigger deep autophagy and significant stem cell rejuvenation without severe metabolic slowing.',
    primary_outcome: 'Deep Autophagy & Stem Cell Activation',
    secondary_outcomes: ['Visceral Fat Loss', 'Brain-Derived Neurotrophic Factor (BDNF)'],
    overall_longevity_benefit: 5,
    implementation_summary: 'Fast through an entire calendar day. Drink water, electrolytes, and unflavored tea.',
    instructions: 'Take sodium, potassium, and magnesium electrolytes throughout the fast. Break fast with bone broth or light protein.',
    dose_or_exposure: '36 consecutive hours fasting',
    timing_summary: '36-hour window',
    frequency: '1-2x per month',
    schedule_pattern: 'infrequent_fasting',
    difficulty: 'very_hard',
    cost_tier: 'free',
    effort_level: 'high',
    time_to_benefit: 'Immediate',
    evidence_quality: 4,
    effect_size_estimate: 5,
    safety_level: 'medium_risk',
    logging_type: 'fasting',
    cadence_layer: 'monthly',
    functional_impacts: {
      "Autophagy": { score: 10 },
      "Stem Cell Reset": { score: 9 },
      "Fat Burning": { score: 10 }
    }
  },
  {
    id: 'extended_fast_48h',
    slug: 'extended-fast-48h',
    name: '48-Hour Extended Fasting',
    display_name: '48-Hour Extended Fasting',
    modality_type: 'fasting',
    category: 'Fasting & Autophagy',
    status: 'active',
    brief_description: 'A 2-day extended fast for maximal autophagy, growth hormone surge, and profound metabolic reset.',
    headline_benefit: 'Peak Autophagy, Growth Hormone & Inflammation Reset',
    expanded_why: '48 hours of fasting provides maximal autophagy clearance of senescent cell debris while spiking HGH up to 500%.',
    primary_outcome: 'Maximal Autophagy & HGH Spike',
    secondary_outcomes: ['Mitochondrial Biogenesis', 'Systemic Anti-Inflammatory Action'],
    overall_longevity_benefit: 5,
    implementation_summary: 'Fast for 48 consecutive hours with water and electrolytes.',
    instructions: 'Supplement with 1500-2000mg sodium, potassium, and magnesium. Break fast carefully with bone broth first.',
    dose_or_exposure: '48 consecutive hours',
    timing_summary: '48-hour protocol',
    frequency: '1x per month or quarterly',
    schedule_pattern: 'infrequent_fasting',
    difficulty: 'very_hard',
    cost_tier: 'free',
    effort_level: 'high',
    time_to_benefit: 'Immediate',
    evidence_quality: 5,
    effect_size_estimate: 5,
    safety_level: 'medium_risk',
    logging_type: 'fasting',
    cadence_layer: 'monthly',
    functional_impacts: {
      "Autophagy": { score: 10 },
      "HGH Elevation": { score: 10 },
      "Mitochondrial Health": { score: 9 }
    }
  },
  {
    id: 'prolonged_autophagy_fast_72h',
    slug: 'prolonged-autophagy-fast-72h',
    name: '72-Hour Prolonged Autophagy Fast',
    display_name: '72-Hour Prolonged Autophagy Fast',
    modality_type: 'fasting',
    category: 'Fasting & Autophagy',
    status: 'active',
    brief_description: 'A 3-day extended water fast for complete immune system recycling and white blood cell renewal.',
    headline_benefit: 'Immune System Reset & White Blood Cell Renewal',
    expanded_why: 'Pioneered by Dr. Valter Longo, 72-hour fasting triggers PKA degradation, resetting old immune cells and activating hematopoiesis stem cells.',
    primary_outcome: 'Hematopoietic Stem Cell Immune Reset',
    secondary_outcomes: ['Senescent Cell Clearance', 'Deep Ketosis'],
    overall_longevity_benefit: 5,
    implementation_summary: 'Fast for 72 consecutive hours with disciplined electrolyte support.',
    instructions: 'Requires electrolyte water (Sodium 2-3g, Potassium 1g, Magnesium 400mg). Carefully break fast with bone broth, followed by healthy fats 2 hours later.',
    dose_or_exposure: '72 consecutive hours',
    timing_summary: '72-hour protocol',
    frequency: '1-2x per year',
    schedule_pattern: 'infrequent_fasting',
    difficulty: 'expert',
    cost_tier: 'free',
    effort_level: 'high',
    time_to_benefit: 'Immediate',
    evidence_quality: 5,
    effect_size_estimate: 5,
    safety_level: 'medium_risk',
    logging_type: 'fasting',
    cadence_layer: 'multi_month',
    functional_impacts: {
      "Immune Reset": { score: 10 },
      "Autophagy": { score: 10 },
      "Stem Cell Reset": { score: 10 }
    }
  },
  {
    id: 'bone_broth_fast',
    slug: 'bone-broth-fast',
    name: 'Bone Broth Fasting',
    display_name: 'Bone Broth Fasting',
    modality_type: 'fasting',
    category: 'Fasting & Autophagy',
    status: 'active',
    brief_description: 'Fast utilizing grass-fed bone broth for gut lining repair, collagen synthesis, and easy adherence.',
    headline_benefit: 'Gut Lining Repair & Collagen Synthesis',
    expanded_why: 'Bone broth provides glycine and glutamine to heal mucosal gut lining while keeping blood glucose minimal.',
    primary_outcome: 'Gut Health & Collagen Support',
    secondary_outcomes: ['Joint Support', 'Gentle Detoxification'],
    overall_longevity_benefit: 4,
    implementation_summary: 'Sip 3-4 cups of organic bone broth daily during a 24-48 hour fasting window.',
    instructions: 'Drink 250-500ml organic bone broth with sea salt 3x daily.',
    dose_or_exposure: '3-4 cups bone broth daily',
    timing_summary: '24-48h broth fast',
    frequency: '1-2x per month',
    schedule_pattern: 'intermittent_fasting',
    difficulty: 'moderate',
    cost_tier: 'low',
    effort_level: 'low',
    time_to_benefit: '1-2 days',
    evidence_quality: 4,
    effect_size_estimate: 4,
    safety_level: 'low_risk',
    logging_type: 'fasting',
    cadence_layer: 'weekly',
    functional_impacts: {
      "Gut Health": { score: 9 },
      "Joint Health": { score: 8 }
    }
  },
  {
    id: 'fat_fasting',
    slug: 'fat-fasting',
    name: 'Fat Fasting (Keto Mimicking)',
    display_name: 'Fat Fasting (Keto Mimicking)',
    modality_type: 'fasting',
    category: 'Fasting & Autophagy',
    status: 'active',
    brief_description: 'Consume 80-90% calories from healthy fats (MCT oil, avocado, butter) to rapidly enter deep ketosis without hunger.',
    headline_benefit: 'Rapid Ketosis Entry Without Hunger',
    expanded_why: 'Fat intake keeps insulin completely suppressed, forcing rapid hepatic ketone generation while avoiding severe appetite signals.',
    primary_outcome: 'Rapid Ketone Production & Hunger Suppression',
    secondary_outcomes: ['Mental Focus', 'Ketone Adaptation'],
    overall_longevity_benefit: 4,
    implementation_summary: 'Consume 1000-1200 kcal daily consisting of 85-90% pure healthy fats for 24-72 hours.',
    instructions: 'Use MCT oil, black coffee with ghee/butter, and avocados. Avoid all carbohydrates and high proteins.',
    dose_or_exposure: '24-72 hours fat fast',
    timing_summary: '1-3 day fat fast',
    frequency: '1x per month',
    schedule_pattern: 'intermittent_fasting',
    difficulty: 'moderate',
    cost_tier: 'low',
    effort_level: 'low',
    time_to_benefit: '24 hours',
    evidence_quality: 4,
    effect_size_estimate: 4,
    safety_level: 'low_risk',
    logging_type: 'fasting',
    cadence_layer: 'monthly',
    functional_impacts: {
      "Ketosis Entry": { score: 9 },
      "Focus": { score: 8 }
    }
  }
];

async function main() {
  console.log(`Upserting ${fastingModalities.length} fasting modalities into Supabase...`);
  const { data, error } = await supabase
    .from('modalities')
    .upsert(fastingModalities, { onConflict: 'id' })
    .select();

  if (error) {
    console.error("Error seeding fasting modalities:", error);
  } else {
    console.log(`Successfully added/updated ${data.length} fasting modalities!`);
  }
}

main();
