const { createClient } = require('@supabase/supabase-js');
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);

const modalities = [
  {
    id: 'red_light_therapy',
    slug: 'red-light-therapy',
    name: 'Red Light Therapy (PBM)',
    display_name: 'Red Light Therapy',
    modality_type: 'habit',
    category: 'Cellular Energy & Recovery',
    brief_description: 'Exposure to specific wavelengths of red and near-infrared light to stimulate cellular energy production.',
    expanded_why: 'Photobiomodulation uses red (660nm) and near-infrared (850nm) light to penetrate the skin and reach mitochondria. Cytochrome c oxidase, a photoreceptor within the electron transport chain, absorbs these photons, leading to increased ATP production, mild ROS generation (hormesis), and nitric oxide release. This powerfully accelerates muscle recovery, reduces systemic inflammation, and improves skin elasticity.',
    primary_outcome: 'Mitochondrial Function & Recovery',
    mechanism_of_action: 'Upregulation of cytochrome c oxidase in the mitochondrial electron transport chain.',
    hallmarks_of_aging_impact: ["Mitochondrial Dysfunction", "Cellular Senescence"],
    synergy_notes: {"pairsWellWith": ["morning_sunlight", "resistance_training"], "rationale": "Used post-workout, it rapidly accelerates muscle repair and reduces delayed onset muscle soreness (DOMS)."},
    antagonism_notes: {"avoidCombiningWith": ["photosensitizing_medications"], "rationale": "Certain drugs (like Accutane or tetracyclines) make the skin hypersensitive to light, increasing the risk of burns."},
    evidence_quality: 4,
    effect_size_estimate: 3,
    safety_level: 'low_risk',
    cost_tier: 'high',
    effort_level: 'low',
    contraindications: ['Active skin cancer in the treatment area'],
    functional_outcomes_to_track: ['soreness', 'energy', 'skin_quality'],
    status: 'active'
  },
  {
    id: 'nac_supplement',
    slug: 'nac-supplement',
    name: 'N-Acetyl Cysteine (600-1200mg)',
    display_name: 'NAC',
    modality_type: 'supplement',
    category: 'Cellular Cleanup',
    brief_description: "A precursor to glutathione, the body's master antioxidant, used to protect against cellular damage and oxidative stress.",
    expanded_why: 'NAC provides the rate-limiting amino acid (cysteine) necessary for the intracellular synthesis of glutathione. By replenishing glutathione levels, NAC protects cells against oxidative damage, reduces systemic inflammation, and acts as a powerful mucolytic agent (breaking up mucus). It is heavily utilized for liver detoxification and mitigating neuroinflammation.',
    primary_outcome: 'Glutathione Replenishment',
    mechanism_of_action: 'Direct precursor for glutathione (GSH) biosynthesis.',
    hallmarks_of_aging_impact: ["Loss of Proteostasis", "Mitochondrial Dysfunction"],
    synergy_notes: {"pairsWellWith": ["glycine"], "rationale": "Combining NAC with Glycine (GlyNAC) provides all the essential rate-limiting building blocks for glutathione, reversing age-related deficiency."},
    antagonism_notes: {"avoidCombiningWith": ["nitroglycerin"], "rationale": "May cause severe hypotension and headache when combined with nitroglycerin."},
    evidence_quality: 4,
    effect_size_estimate: 3,
    safety_level: 'low_risk',
    cost_tier: 'medium',
    effort_level: 'very_low',
    contraindications: ['Bleeding disorders (mild risk)'],
    functional_outcomes_to_track: ['brain_fog', 'energy', 'respiratory_health'],
    status: 'active'
  },
  {
    id: 'vitamin_d3_k2',
    slug: 'vitamin-d3-k2',
    name: 'Vitamin D3 + K2 (5000 IU / 100mcg)',
    display_name: 'Vitamin D3 + K2',
    modality_type: 'supplement',
    category: 'Longevity Foundation',
    brief_description: 'A synergistic pair of fat-soluble vitamins essential for bone health, immune function, and cardiovascular protection.',
    expanded_why: 'Vitamin D3 massively increases intestinal calcium absorption. Without Vitamin K2 (MK-7), this excess calcium can mistakenly deposit in soft tissues and arteries (calcification). Vitamin K2 activates matrix GLA protein (MGP) and osteocalcin, which specifically direct the calcium out of the bloodstream and into the bone matrix, preventing cardiovascular disease while strengthening bones.',
    primary_outcome: 'Calcium Routing & Immune Function',
    mechanism_of_action: 'Vitamin D receptor activation paired with Vitamin K-dependent protein carboxylation.',
    hallmarks_of_aging_impact: ["Altered Intercellular Communication"],
    synergy_notes: {"pairsWellWith": ["fat_containing_meal", "magnesium_glycinate"], "rationale": "Fat is required for absorption. Magnesium is the necessary cofactor for the enzymatic activation of Vitamin D in the kidneys."},
    antagonism_notes: {"avoidCombiningWith": ["warfarin"], "rationale": "Vitamin K directly antagonizes the blood-thinning mechanism of Warfarin (Coumadin)."},
    evidence_quality: 5,
    effect_size_estimate: 4,
    safety_level: 'low_risk',
    cost_tier: 'low',
    effort_level: 'very_low',
    contraindications: ['Hypercalcemia', 'Warfarin use (for the K2 component)'],
    functional_outcomes_to_track: ['energy', 'immunity', 'mood'],
    status: 'active'
  },
  {
    id: 'fisetin',
    slug: 'fisetin',
    name: 'Fisetin (High-Dose Pulse)',
    display_name: 'Fisetin',
    modality_type: 'supplement',
    category: 'Cellular Cleanup',
    brief_description: 'A highly potent plant polyphenol shown to clear senescent ("zombie") cells from tissues.',
    expanded_why: 'Fisetin acts as a senolytic. Senescent cells stop dividing but refuse to die, secreting a toxic cocktail of inflammatory cytokines (SASP) that rapidly accelerate aging in surrounding cells. Fisetin suppresses the PI3K/AKT/mTOR pathway and forces these zombie cells into apoptosis (programmed cell death). The Mayo Clinic protocol involves a massive dose taken for 2-3 days, followed by a month off to allow the body to flush the dead cells.',
    primary_outcome: 'Senescent Cell Clearance',
    mechanism_of_action: 'Senolytic via inhibition of the PI3K/AKT/mTOR survival pathway.',
    hallmarks_of_aging_impact: ["Cellular Senescence", "Chronic Inflammation"],
    synergy_notes: {"pairsWellWith": ["quercetin", "dasatinib"], "rationale": "Often stacked in research (D+Q) or with other senolytics to hit different survival pathways in different tissue types."},
    antagonism_notes: {"avoidCombiningWith": ["daily_use"], "rationale": "Taking senolytics daily prevents the immune system from clearing the dead cells and blunts the hormetic response. It must be pulsed."},
    evidence_quality: 3,
    effect_size_estimate: 4,
    safety_level: 'moderate_risk',
    cost_tier: 'high',
    effort_level: 'very_low',
    contraindications: ['Active infections', 'Pregnancy'],
    functional_outcomes_to_track: ['energy', 'joint_pain', 'brain_fog'],
    status: 'active'
  },
  {
    id: 'myo_inositol',
    slug: 'myo-inositol',
    name: 'Myo-Inositol (2-4g)',
    display_name: 'Myo-Inositol',
    modality_type: 'supplement',
    category: 'Metabolic Regulation',
    brief_description: 'A carbohydrate compound that profoundly improves cellular insulin signaling and supports sleep architecture.',
    expanded_why: "Myo-inositol acts as a secondary messenger for insulin, meaning it directly amplifies the cell's sensitivity to insulin without increasing insulin levels. This makes it incredibly effective for managing PCOS and metabolic syndrome. In the brain, it alters serotonin and orexin signaling, leading to decreased anxiety and faster sleep onset.",
    primary_outcome: 'Insulin Sensitivity & Anxiety Reduction',
    mechanism_of_action: 'Secondary messenger in the insulin signaling pathway and serotonin modulation.',
    hallmarks_of_aging_impact: ["Deregulated Nutrient Sensing"],
    synergy_notes: {"pairsWellWith": ["magnesium_glycinate", "l_theanine"], "rationale": "A cornerstone of the Huberman sleep stack, assisting with sleep latency and preventing midnight awakenings."},
    antagonism_notes: {"avoidCombiningWith": ["high_dose_lithium"], "rationale": "Lithium depletes cellular inositol, so they interact dynamically."},
    evidence_quality: 4,
    effect_size_estimate: 3,
    safety_level: 'low_risk',
    cost_tier: 'low',
    effort_level: 'very_low',
    contraindications: [],
    functional_outcomes_to_track: ['sleep_latency', 'anxiety', 'cravings'],
    status: 'active'
  },
  {
    id: 'lions_mane',
    slug: 'lions-mane',
    name: "Lion's Mane Mushroom",
    display_name: "Lion's Mane",
    modality_type: 'supplement',
    category: 'Nervous System & Sleep',
    brief_description: 'A medicinal mushroom containing unique compounds that stimulate nerve growth factor (NGF) in the brain.',
    expanded_why: "Lion's Mane contains hericenones and erinacines, unique compounds capable of crossing the blood-brain barrier. Once in the brain, they strongly stimulate the synthesis of Nerve Growth Factor (NGF) and Brain-Derived Neurotrophic Factor (BDNF). This promotes neuroplasticity, myelination, and the growth of new neurons, making it a leading functional mushroom for cognitive enhancement and neuroprotection against Alzheimer's.",
    primary_outcome: 'Neuroplasticity & BDNF Upregulation',
    mechanism_of_action: 'Stimulation of Nerve Growth Factor (NGF) synthesis via erinacines.',
    hallmarks_of_aging_impact: ["Altered Intercellular Communication"],
    synergy_notes: {"pairsWellWith": ["psilocybin", "niacin"], "rationale": "Often used in Paul Stamets' neurogenesis stack where niacin acts as a vasodilator to push the compounds deep into the peripheral nervous system."},
    antagonism_notes: {"avoidCombiningWith": ["immunosuppressants"], "rationale": "Like many functional mushrooms, it modulates the immune system and may counteract immunosuppressive drugs."},
    evidence_quality: 3,
    effect_size_estimate: 3,
    safety_level: 'low_risk',
    cost_tier: 'medium',
    effort_level: 'very_low',
    contraindications: ['Mushroom allergies', 'Autoimmune conditions'],
    functional_outcomes_to_track: ['focus', 'memory', 'brain_fog'],
    status: 'active'
  },
  {
    id: 'curcumin_phytosome',
    slug: 'curcumin-phytosome',
    name: 'Curcumin (Phytosome / Meriva)',
    display_name: 'Curcumin',
    modality_type: 'supplement',
    category: 'Cellular Cleanup',
    brief_description: 'The highly bioavailable, active anti-inflammatory compound found in turmeric.',
    expanded_why: 'Curcumin is one of the most potent natural anti-inflammatories ever studied. It works by inhibiting the COX-2 and LOX enzymes, identically to pharmaceutical NSAIDs (like Ibuprofen), but without the severe gastrointestinal or cardiovascular side effects. Because raw curcumin has nearly 0% bioavailability, it must be bound to a lipid (phytosome/Meriva) or combined with black pepper extract (piperine) to reach systemic circulation.',
    primary_outcome: 'Systemic Inflammation Reduction',
    mechanism_of_action: 'Inhibition of COX-2, LOX, and TNF-alpha inflammatory pathways.',
    hallmarks_of_aging_impact: ["Chronic Inflammation", "Altered Intercellular Communication"],
    synergy_notes: {"pairsWellWith": ["epa_dha_omega3", "black_pepper"], "rationale": "Piperine (black pepper) inhibits liver enzymes that destroy curcumin, boosting absorption by 2000%."},
    antagonism_notes: {"avoidCombiningWith": ["blood_thinners", "fasting"], "rationale": "Curcumin is highly fat-soluble and will not absorb on an empty stomach. It also has mild anticoagulant properties."},
    evidence_quality: 5,
    effect_size_estimate: 4,
    safety_level: 'low_risk',
    cost_tier: 'medium',
    effort_level: 'very_low',
    contraindications: ['Gallbladder disease', 'Upcoming surgery'],
    functional_outcomes_to_track: ['joint_pain', 'brain_fog', 'recovery'],
    status: 'active'
  },
  {
    id: 'phosphatidylserine',
    slug: 'phosphatidylserine',
    name: 'Phosphatidylserine (300mg)',
    display_name: 'Phosphatidylserine',
    modality_type: 'supplement',
    category: 'Nervous System & Sleep',
    brief_description: 'A phospholipid essential for brain cell membranes, used to lower elevated cortisol and protect cognitive function.',
    expanded_why: 'Phosphatidylserine (PS) covers and protects the cells in your brain and carries messages between them. It plays a critical role in keeping your mind and memory sharp. When taken as a supplement (especially post-workout or during high stress), it blunts the hyper-secretion of ACTH and cortisol from the adrenal glands, returning the body to a parasympathetic state faster and preventing stress-induced cognitive decline.',
    primary_outcome: 'Cortisol Buffering & Memory',
    mechanism_of_action: 'Cell membrane structural support and HPA axis modulation.',
    hallmarks_of_aging_impact: ["Altered Intercellular Communication"],
    synergy_notes: {"pairsWellWith": ["epa_dha_omega3"], "rationale": "DHA actively regulates the levels of phosphatidylserine in neuronal membranes; they work together structurally."},
    antagonism_notes: {"avoidCombiningWith": ["anticholinergic_drugs"], "rationale": "May increase acetylcholine levels, antagonizing medications designed to block it."},
    evidence_quality: 4,
    effect_size_estimate: 3,
    safety_level: 'low_risk',
    cost_tier: 'high',
    effort_level: 'very_low',
    contraindications: [],
    functional_outcomes_to_track: ['stress', 'memory', 'sleep_quality'],
    status: 'active'
  },
  {
    id: 'l_tyrosine',
    slug: 'l-tyrosine',
    name: 'L-Tyrosine (500-1000mg)',
    display_name: 'L-Tyrosine',
    modality_type: 'supplement',
    category: 'Physical Performance',
    brief_description: 'An amino acid precursor used to rapidly replenish depleted dopamine and norepinephrine during acute stress.',
    expanded_why: "L-Tyrosine is the direct building block for catecholamines (dopamine, epinephrine, norepinephrine). During intense physical stress, sleep deprivation, or heavy cognitive load, the brain burns through its dopamine reserves, causing the classic \"crash\" or brain fog. L-Tyrosine does not stimulate dopamine release (like a drug), but rather provides the raw materials to prevent depletion, making it an incredible cognitive safety net.",
    primary_outcome: 'Dopamine Replenishment',
    mechanism_of_action: 'Direct metabolic precursor to L-DOPA and catecholamine neurotransmitters.',
    hallmarks_of_aging_impact: ["Altered Intercellular Communication"],
    synergy_notes: {"pairsWellWith": ["caffeine", "cold_water_immersion"], "rationale": "Caffeine forces the release of dopamine; Tyrosine ensures you don't run out of it."},
    antagonism_notes: {"avoidCombiningWith": ["maois", "levodopa"], "rationale": "Can cause a dangerous hypertensive crisis if combined with MAOI antidepressants."},
    evidence_quality: 4,
    effect_size_estimate: 3,
    safety_level: 'moderate_risk',
    cost_tier: 'low',
    effort_level: 'very_low',
    contraindications: ['Hyperthyroidism', 'Melanoma', 'MAOI use'],
    functional_outcomes_to_track: ['focus', 'energy', 'stress'],
    status: 'active'
  },
  {
    id: 'hiit_vo2_max',
    slug: 'hiit-vo2-max',
    name: 'VO2 Max / HIIT Training',
    display_name: 'HIIT (VO2 Max)',
    modality_type: 'exercise',
    category: 'Physical Performance',
    brief_description: 'Short bursts of maximum cardiovascular output designed to push the heart and lungs to their absolute peak capacity.',
    expanded_why: 'While Zone 2 cardio builds the mitochondrial base, High-Intensity Interval Training (HIIT) pushes the ceiling (VO2 Max). VO2 Max is the single strongest predictor of human lifespan—more than smoking history, cancer, or heart disease. Training protocols like the 4x4 (4 mins max effort, 4 mins active rest, repeated 4 times) dramatically increase stroke volume, cardiac output, and mitochondrial peak power.',
    primary_outcome: 'Cardiopulmonary Capacity (VO2 Max)',
    mechanism_of_action: 'Cardiac remodeling and central oxygen delivery optimization.',
    hallmarks_of_aging_impact: ["Mitochondrial Dysfunction", "Cellular Senescence"],
    synergy_notes: {"pairsWellWith": ["creatine", "beetroot_juice"], "rationale": "Beetroot juice (nitrates) acts as a vasodilator, reducing the oxygen cost of exercise during max efforts."},
    antagonism_notes: {"avoidCombiningWith": ["daily_frequency"], "rationale": "HIIT causes massive central nervous system fatigue and oxidative stress. It should only be done 1-2 times per week to prevent overtraining."},
    evidence_quality: 5,
    effect_size_estimate: 5,
    safety_level: 'moderate_risk',
    cost_tier: 'free',
    effort_level: 'extreme',
    contraindications: ['Unstable angina', 'Severe orthopedic limitations', 'Untreated hypertension'],
    functional_outcomes_to_track: ['endurance', 'energy', 'soreness'],
    status: 'active'
  }
];

async function run() {
  const { error } = await supabase.from('modalities').upsert(modalities);
  if (error) {
    console.error("Error inserting modalities:", error);
    process.exit(1);
  } else {
    console.log("Successfully inserted 10 new protocol modalities.");
  }
}

run();
