const { createClient } = require('@supabase/supabase-js');
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);

const modalities = [
  {
    id: 'hyperbaric_oxygen',
    slug: 'hyperbaric-oxygen',
    name: 'Hyperbaric Oxygen Therapy (HBOT)',
    display_name: 'HBOT',
    modality_type: 'clinical',
    category: 'Cellular Energy & Recovery',
    brief_description: "Breathing pure oxygen in a pressurized chamber to massively increase oxygen dissolution in blood plasma.",
    expanded_why: "Under normal atmospheric pressure, oxygen is almost entirely carried by hemoglobin in red blood cells. In a hyperbaric chamber (typically 1.5 to 2.5 ATA), the pressure physically dissolves oxygen directly into the blood plasma. This allows oxygen to penetrate deep into tissues with compromised blood supply, triggering massive angiogenesis (new blood vessel growth), stem cell mobilization, and reducing systemic inflammation.",
    primary_outcome: 'Tissue Healing & Stem Cell Mobilization',
    mechanism_of_action: 'Hyperoxia-induced HIF-1 alpha fluctuation and vascular endothelial growth factor (VEGF) upregulation.',
    hallmarks_of_aging_impact: ["Stem Cell Exhaustion", "Altered Intercellular Communication"],
    synergy_notes: {"pairsWellWith": ["fasting", "ketones"], "rationale": "Combining HBOT with a ketogenic state forces cells to rapidly utilize the flooded oxygen for highly efficient fat oxidation and neuro-healing."},
    antagonism_notes: {"avoidCombiningWith": ["antioxidants_before_session"], "rationale": "HBOT relies on a brief spike in reactive oxygen species (ROS) to trigger the healing response; high doses of antioxidants right before can blunt this hormesis."},
    evidence_quality: 4,
    effect_size_estimate: 5,
    safety_level: 'moderate_risk',
    cost_tier: 'premium',
    effort_level: 'high',
    contraindications: ["Untreated pneumothorax", "Certain chemotherapy drugs", "Severe claustrophobia"],
    functional_outcomes_to_track: ["recovery", "brain_fog", "wound_healing"],
    status: 'active'
  },
  {
    id: 'cpap_therapy',
    slug: 'cpap-therapy',
    name: 'CPAP Therapy',
    display_name: 'CPAP',
    modality_type: 'clinical',
    category: 'Nervous System & Sleep',
    brief_description: "Continuous Positive Airway Pressure machine to treat sleep apnea and prevent nighttime oxygen desaturation.",
    expanded_why: "Sleep apnea silently destroys longevity by causing dozens of micro-awakenings per hour, preventing deep sleep and violently spiking nighttime blood pressure and cortisol. A CPAP machine provides a continuous stream of pressurized air to keep the airway open. For those who need it, this is often the single highest-leverage longevity intervention they will ever make, instantly reversing massive cardiovascular and cognitive strain.",
    primary_outcome: 'Apnea Reversal & Deep Sleep',
    mechanism_of_action: 'Mechanical pneumatic splinting of the upper airway during sleep.',
    hallmarks_of_aging_impact: ["Mitochondrial Dysfunction", "Chronic Inflammation"],
    synergy_notes: {"pairsWellWith": ["mouth_taping"], "rationale": "Using a CPAP with a nasal mask often requires mouth taping to prevent the pressurized air from escaping through the mouth."},
    antagonism_notes: {"avoidCombiningWith": ["alcohol_before_bed"], "rationale": "Alcohol relaxes the throat muscles so severely that even a CPAP may struggle to keep the airway fully open."},
    evidence_quality: 5,
    effect_size_estimate: 5,
    safety_level: 'low_risk',
    cost_tier: 'high',
    effort_level: 'high',
    contraindications: ["Severe bullous lung disease", "CSF leaks"],
    functional_outcomes_to_track: ["sleep_quality", "energy", "blood_pressure"],
    status: 'active'
  },
  {
    id: 'methylene_blue',
    slug: 'methylene-blue',
    name: 'Methylene Blue (Low Dose)',
    display_name: 'Methylene Blue',
    modality_type: 'supplement',
    category: 'Cellular Energy & Recovery',
    brief_description: "A pharmaceutical dye that acts as an alternative electron carrier in the mitochondria to boost ATP production.",
    expanded_why: "At low doses (0.5 - 4mg/kg), Methylene Blue possesses the unique ability to act as an electron cycler in the mitochondrial electron transport chain. If a mitochondrion is damaged or poisoned (e.g., by cyanide or aging), MB bypasses complexes I-III and donates electrons directly to cytochrome c oxidase (Complex IV). This drastically increases ATP energy production and reduces oxidative stress in the brain.",
    primary_outcome: 'Mitochondrial Respiration Rescue',
    mechanism_of_action: 'Alternative electron donor to Complex IV in the electron transport chain.',
    hallmarks_of_aging_impact: ["Mitochondrial Dysfunction"],
    synergy_notes: {"pairsWellWith": ["red_light_therapy"], "rationale": "Both MB and Red Light directly stimulate Complex IV. Using MB prior to red light therapy creates a massive synergistic spike in ATP production."},
    antagonism_notes: {"avoidCombiningWith": ["ssri_antidepressants"], "rationale": "Methylene Blue is a potent MAO inhibitor; combining it with SSRIs can cause deadly serotonin syndrome."},
    evidence_quality: 3,
    effect_size_estimate: 4,
    safety_level: 'high_risk',
    cost_tier: 'low',
    effort_level: 'very_low',
    contraindications: ["SSRI or SNRI use", "G6PD deficiency", "Pregnancy"],
    functional_outcomes_to_track: ["brain_fog", "energy", "focus"],
    status: 'active'
  },
  {
    id: 'pterostilbene',
    slug: 'pterostilbene',
    name: 'Pterostilbene (50mg)',
    display_name: 'Pterostilbene',
    modality_type: 'supplement',
    category: 'Metabolic Regulation',
    brief_description: "A highly bioavailable analog of resveratrol that activates sirtuin longevity pathways.",
    expanded_why: "Like resveratrol (found in red wine), pterostilbene is a polyphenol that mimics the biological effects of fasting by activating SIRT1. However, pterostilbene has two methoxy groups that make it vastly more lipophilic (fat-soluble), giving it an 80% bioavailability compared to resveratrol's 20%, and allowing it to easily cross the blood-brain barrier for neuroprotection.",
    primary_outcome: 'Sirtuin Activation & Neuroprotection',
    mechanism_of_action: 'Activation of SIRT1 (sirtuins) mimicking caloric restriction.',
    hallmarks_of_aging_impact: ["Epigenetic Alterations", "Deregulated Nutrient Sensing"],
    synergy_notes: {"pairsWellWith": ["nad_precursors"], "rationale": "Sirtuins are enzymes that require NAD+ as fuel. Pterostilbene steps on the gas pedal, but NAD+ provides the fuel. They must be taken together."},
    antagonism_notes: {"avoidCombiningWith": ["high_dose_statins"], "rationale": "Can occasionally cause mild elevations in LDL cholesterol, which may counteract lipid-lowering therapies."},
    evidence_quality: 3,
    effect_size_estimate: 3,
    safety_level: 'low_risk',
    cost_tier: 'medium',
    effort_level: 'very_low',
    contraindications: [],
    functional_outcomes_to_track: ["memory", "blood_sugar", "energy"],
    status: 'active'
  },
  {
    id: 'alpha_ketoglutarate',
    slug: 'alpha-ketoglutarate',
    name: 'Calcium Alpha-Ketoglutarate (Ca-AKG)',
    display_name: 'Ca-AKG',
    modality_type: 'supplement',
    category: 'Longevity Foundation',
    brief_description: "A critical Krebs cycle metabolite shown to compress morbidity and reverse biological age markers.",
    expanded_why: "AKG is a key intermediate in the Krebs (energy) cycle, but its levels drop by up to 10-fold between the ages of 40 and 80. Recent landmark studies show that supplementing Ca-AKG not only extends lifespan in mice, but dramatically compresses morbidity—meaning they stay healthy and vital right up until the end of life. It acts as an epigenetic demethylase, actively scrubbing age-related damage from DNA.",
    primary_outcome: 'Epigenetic Reprogramming & Healthspan Extension',
    mechanism_of_action: 'Substrate for TET enzymes which remove epigenetic DNA methylation marks.',
    hallmarks_of_aging_impact: ["Epigenetic Alterations", "Mitochondrial Dysfunction"],
    synergy_notes: {"pairsWellWith": ["vitamin_c"], "rationale": "TET enzymes require both AKG and Vitamin C as cofactors to successfully demethylate DNA."},
    antagonism_notes: {"avoidCombiningWith": ["eating_windows"], "rationale": "Best taken away from large meals to prevent it from simply being burned as immediate cellular fuel."},
    evidence_quality: 4,
    effect_size_estimate: 4,
    safety_level: 'low_risk',
    cost_tier: 'high',
    effort_level: 'very_low',
    contraindications: [],
    functional_outcomes_to_track: ["energy", "bone_density", "frailty"],
    status: 'active'
  },
  {
    id: 'sulforaphane',
    slug: 'sulforaphane',
    name: 'Sulforaphane (Broccoli Sprouts)',
    display_name: 'Sulforaphane',
    modality_type: 'nutrition',
    category: 'Cellular Cleanup',
    brief_description: "The most potent naturally occurring activator of the Nrf2 pathway, heavily concentrated in broccoli sprouts.",
    expanded_why: "Sulforaphane is a phytochemical that acts as a mild cellular stressor. It activates the Nrf2 pathway, which is the master regulator of the body's antioxidant and detoxification defense system. This upregulates hundreds of protective genes, massively increasing the liver's ability to excrete carcinogens and air pollution (like benzene). To get clinical doses, you must eat 3-4 day old broccoli sprouts, not mature broccoli.",
    primary_outcome: 'Nrf2 Activation & Detoxification',
    mechanism_of_action: 'Upregulation of the Nrf2-ARE (Antioxidant Response Element) pathway.',
    hallmarks_of_aging_impact: ["Loss of Proteostasis", "Chronic Inflammation"],
    synergy_notes: {"pairsWellWith": ["mustard_seed_powder"], "rationale": "Heating or freezing destroys myrosinase, the enzyme required to create sulforaphane. Adding raw mustard seed powder provides active myrosinase to rescue the conversion."},
    antagonism_notes: {"avoidCombiningWith": ["boiling"], "rationale": "Boiling sprouts completely destroys the myrosinase enzyme, resulting in zero sulforaphane yield."},
    evidence_quality: 5,
    effect_size_estimate: 4,
    safety_level: 'low_risk',
    cost_tier: 'low',
    effort_level: 'medium',
    contraindications: ["Thyroid dysfunction (mild risk due to goitrogens if eaten in massive quantities)"],
    functional_outcomes_to_track: ["brain_fog", "skin_quality", "immunity"],
    status: 'active'
  },
  {
    id: 'l_citrulline',
    slug: 'l-citrulline',
    name: 'L-Citrulline (6-8g)',
    display_name: 'L-Citrulline',
    modality_type: 'supplement',
    category: 'Physical Performance',
    brief_description: "An amino acid that powerfully increases nitric oxide production for blood flow and cardiovascular health.",
    expanded_why: "While L-Arginine is heavily broken down by the liver, L-Citrulline bypasses liver metabolism entirely and converts into arginine in the kidneys. This results in a massive, sustained spike in Nitric Oxide (NO). This aggressively dilates blood vessels, significantly lowering blood pressure, improving erectile function, and dramatically increasing oxygen and nutrient delivery to muscles during workouts.",
    primary_outcome: 'Vasodilation & Blood Flow',
    mechanism_of_action: 'Conversion to L-arginine in the kidneys, leading to endothelial nitric oxide synthase (eNOS) activation.',
    hallmarks_of_aging_impact: ["Altered Intercellular Communication"],
    synergy_notes: {"pairsWellWith": ["beetroot_juice", "sauna_exposure"], "rationale": "Combines perfectly with sauna or beet juice to maximize endothelial expansion and blood pressure reduction."},
    antagonism_notes: {"avoidCombiningWith": ["pde5_inhibitors"], "rationale": "Combining high-dose citrulline with Viagra or Cialis can cause a dangerous crash in blood pressure."},
    evidence_quality: 5,
    effect_size_estimate: 4,
    safety_level: 'low_risk',
    cost_tier: 'low',
    effort_level: 'very_low',
    contraindications: ["Hypotension", "Concurrent use of ED medications"],
    functional_outcomes_to_track: ["blood_pressure", "endurance", "recovery"],
    status: 'active'
  },
  {
    id: 'evoo_high_polyphenol',
    slug: 'evoo-high-polyphenol',
    name: 'High-Polyphenol EVOO',
    display_name: 'EVOO',
    modality_type: 'nutrition',
    category: 'Longevity Foundation',
    brief_description: "Extra Virgin Olive Oil with a high oleocanthal content, used to mimic ibuprofen and protect cardiovascular health.",
    expanded_why: "The cornerstone of the Mediterranean diet isn't just the fat profile; it's the polyphenols, specifically Oleocanthal. Oleocanthal produces a peppery, burning sensation in the back of the throat and is a natural, potent COX-1 and COX-2 inhibitor, identically mimicking the effects of Ibuprofen but without organ toxicity. Consuming 2-4 tablespoons daily provides constant, low-level systemic anti-inflammatory protection.",
    primary_outcome: 'Cardiovascular Protection & Anti-inflammation',
    mechanism_of_action: 'Oleocanthal-mediated inhibition of cyclooxygenase (COX) enzymes.',
    hallmarks_of_aging_impact: ["Chronic Inflammation"],
    synergy_notes: {"pairsWellWith": ["leafy_greens"], "rationale": "The monounsaturated fats massively increase the absorption of fat-soluble vitamins (A, D, E, K) from vegetables."},
    antagonism_notes: {"avoidCombiningWith": ["high_heat_cooking"], "rationale": "Frying with high-polyphenol EVOO destroys the delicate polyphenols and causes them to smoke and oxidize."},
    evidence_quality: 5,
    effect_size_estimate: 3,
    safety_level: 'low_risk',
    cost_tier: 'high',
    effort_level: 'low',
    contraindications: [],
    functional_outcomes_to_track: ["joint_pain", "blood_pressure", "lipids"],
    status: 'active'
  },
  {
    id: 'kefir',
    slug: 'kefir',
    name: 'Kefir (Fermented Milk)',
    display_name: 'Kefir',
    modality_type: 'nutrition',
    category: 'Metabolic Regulation',
    brief_description: "A highly diverse, fermented dairy drink containing up to 60 strains of beneficial bacteria and yeast.",
    expanded_why: "Unlike yogurt, which usually only contains 2-3 strains of transient bacteria, Kefir contains a massive diversity of symbiotic bacteria and yeast that can actually colonize the gut. Regular consumption repairs the gut lining, significantly reduces systemic inflammation markers (like CRP), and alters the microbiome to produce massive amounts of serotonin and GABA, dramatically improving mood.",
    primary_outcome: 'Microbiome Diversity & Gut Barrier Repair',
    mechanism_of_action: 'Inoculation of the gastrointestinal tract with diverse probiotic colonies.',
    hallmarks_of_aging_impact: ["Dysbiosis", "Chronic Inflammation"],
    synergy_notes: {"pairsWellWith": ["prebiotic_fibers"], "rationale": "Probiotics need food. Pairing kefir with inulin or resistant starch ensures the new bacteria thrive and multiply."},
    antagonism_notes: {"avoidCombiningWith": ["antibiotics"], "rationale": "Antibiotics will nuke the beneficial bacteria. If taking antibiotics, kefir should be spaced at least 4 hours apart."},
    evidence_quality: 4,
    effect_size_estimate: 4,
    safety_level: 'low_risk',
    cost_tier: 'low',
    effort_level: 'very_low',
    contraindications: ["Severe lactose/dairy allergy", "Histamine intolerance"],
    functional_outcomes_to_track: ["digestion", "mood", "immunity"],
    status: 'active'
  },
  {
    id: 'akkermansia',
    slug: 'akkermansia',
    name: 'Akkermansia Muciniphila',
    display_name: 'Akkermansia',
    modality_type: 'supplement',
    category: 'Metabolic Regulation',
    brief_description: "A keystone gut bacterium that fortifies the intestinal mucus layer and prevents metabolic syndrome.",
    expanded_why: "Akkermansia muciniphila is a unique bacterium that literally eats the mucus lining of your gut. This mild stress forces the goblet cells to produce a thicker, healthier mucus barrier, completely sealing \"leaky gut\" (intestinal permeability). High levels of Akkermansia are strongly correlated with leanness, insulin sensitivity, and longevity, while obese or diabetic individuals are almost entirely depleted of it.",
    primary_outcome: 'Intestinal Barrier Fortification',
    mechanism_of_action: 'Mucin degradation stimulating goblet cell hyper-secretion and GLP-1 release.',
    hallmarks_of_aging_impact: ["Dysbiosis", "Deregulated Nutrient Sensing"],
    synergy_notes: {"pairsWellWith": ["pomegranate_extract", "polyphenols"], "rationale": "Akkermansia thrives on dark polyphenols. Taking pomegranate extract massively increases endogenous Akkermansia levels."},
    antagonism_notes: {"avoidCombiningWith": ["high_fat_diets"], "rationale": "Standard high-fat/low-fiber diets starve Akkermansia, leading to thinning of the mucus layer."},
    evidence_quality: 4,
    effect_size_estimate: 4,
    safety_level: 'low_risk',
    cost_tier: 'high',
    effort_level: 'very_low',
    contraindications: [],
    functional_outcomes_to_track: ["blood_sugar", "cravings", "digestion"],
    status: 'active'
  }
];

async function run() {
  const { error } = await supabase.from('modalities').upsert(modalities);
  if (error) {
    console.error("Error inserting modalities:", error);
    process.exit(1);
  } else {
    console.log("Successfully inserted 10 more protocol modalities.");
  }
}

run();
