const { createClient } = require('@supabase/supabase-js');
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);

const modalities = [
  {
    id: 'alcar_carnitine',
    slug: 'alcar-carnitine',
    name: 'Acetyl-L-Carnitine (ALCAR)',
    display_name: 'ALCAR',
    modality_type: 'supplement',
    category: 'Cellular Energy & Recovery',
    brief_description: "An amino acid derivative that shuttles fatty acids into the mitochondria for energy and crosses the blood-brain barrier for cognitive benefits.",
    expanded_why: "ALCAR is critical for fat metabolism; it literally acts as the shuttle that carries long-chain fatty acids into the mitochondria so they can be burned for ATP. Unlike regular L-Carnitine, the acetylated form (ALCAR) crosses the blood-brain barrier. There, it donates its acetyl group to synthesize acetylcholine, a neurotransmitter essential for memory, focus, and learning.",
    primary_outcome: 'Fat Oxidation & Focus',
    mechanism_of_action: 'Mitochondrial fatty acid transport and acetylcholine precursor.',
    hallmarks_of_aging_impact: ["Mitochondrial Dysfunction"],
    synergy_notes: {"pairsWellWith": ["alpha_lipoic_acid", "caffeine"], "rationale": "Often stacked with Alpha-Lipoic Acid (ALA) for synergistic mitochondrial function and antioxidant protection."},
    antagonism_notes: {"avoidCombiningWith": ["hypothyroidism_meds"], "rationale": "May mildly antagonize thyroid hormone action, so it should be separated from thyroid medication."},
    evidence_quality: 4,
    effect_size_estimate: 3,
    safety_level: 'low_risk',
    cost_tier: 'low',
    effort_level: 'very_low',
    contraindications: ["Hypothyroidism (relative)"],
    functional_outcomes_to_track: ["energy", "focus", "fat_loss"],
    status: 'active'
  },
  {
    id: 'magnesium_threonate',
    slug: 'magnesium-threonate',
    name: 'Magnesium L-Threonate',
    display_name: 'Magnesium Threonate',
    modality_type: 'supplement',
    category: 'Nervous System & Sleep',
    brief_description: "A specialized form of magnesium designed specifically to cross the blood-brain barrier to enhance learning, memory, and cognitive aging.",
    expanded_why: "Developed by researchers at MIT, Magnesium L-Threonate is the only form of magnesium proven to significantly elevate brain magnesium levels. Once inside the brain, it increases the density of synapses and enhances neuroplasticity. This makes it superior to other magnesiums for preventing cognitive decline, improving short-term memory, and reducing brain fog.",
    primary_outcome: 'Synaptic Density & Neuroplasticity',
    mechanism_of_action: 'NMDA receptor modulation and enhanced synaptic plasticity in the hippocampus.',
    hallmarks_of_aging_impact: ["Altered Intercellular Communication"],
    synergy_notes: {"pairsWellWith": ["apigenin", "l_theanine"], "rationale": "A core component of the Huberman sleep and cognition stack, acting directly on the central nervous system to facilitate relaxation."},
    antagonism_notes: {"avoidCombiningWith": ["iron_supplements"], "rationale": "Minerals compete for absorption in the gut; separate by 2 hours."},
    evidence_quality: 3,
    effect_size_estimate: 3,
    safety_level: 'low_risk',
    cost_tier: 'high',
    effort_level: 'very_low',
    contraindications: [],
    functional_outcomes_to_track: ["memory", "sleep_quality", "focus"],
    status: 'active'
  },
  {
    id: 'astaxanthin',
    slug: 'astaxanthin',
    name: 'Astaxanthin (4-12mg)',
    display_name: 'Astaxanthin',
    modality_type: 'supplement',
    category: 'Cellular Cleanup',
    brief_description: "A wildly potent marine carotenoid that provides unparalleled protection against oxidative stress and UV radiation.",
    expanded_why: "Astaxanthin is the red pigment that gives salmon their color and the endurance to swim upstream. It is uniquely shaped to span the entire cell membrane, protecting both the fat-soluble and water-soluble parts of the cell simultaneously. It is roughly 6,000 times stronger than Vitamin C at quenching singlet oxygen, making it a premier supplement for skin health, eye health, and intense athletic recovery.",
    primary_outcome: 'Cell Membrane Protection & Skin Defense',
    mechanism_of_action: 'Potent quenching of reactive oxygen species (ROS) spanning the lipid bilayer.',
    hallmarks_of_aging_impact: ["Loss of Proteostasis"],
    synergy_notes: {"pairsWellWith": ["epa_dha_omega3"], "rationale": "Often bundled with krill oil, as the fats enhance the absorption of this deeply fat-soluble antioxidant."},
    antagonism_notes: {"avoidCombiningWith": ["fasting"], "rationale": "Extremely poor absorption without dietary fat."},
    evidence_quality: 4,
    effect_size_estimate: 3,
    safety_level: 'low_risk',
    cost_tier: 'medium',
    effort_level: 'very_low',
    contraindications: [],
    functional_outcomes_to_track: ["skin_quality", "joint_pain", "endurance"],
    status: 'active'
  },
  {
    id: 'liposomal_glutathione',
    slug: 'liposomal-glutathione',
    name: 'Liposomal Glutathione',
    display_name: 'Liposomal Glutathione',
    modality_type: 'supplement',
    category: 'Cellular Cleanup',
    brief_description: "The body's master antioxidant, encapsulated in a lipid layer to survive digestion and directly enter cells.",
    expanded_why: "Glutathione is essential for neutralizing free radicals, recycling other antioxidants, and detoxifying heavy metals in the liver. Unfortunately, oral glutathione is destroyed by stomach acid. Liposomal delivery wraps the glutathione in a phospholipid sphere, allowing it to bypass digestion and absorb directly into the bloodstream, powerfully combating systemic oxidative stress.",
    primary_outcome: 'Systemic Detoxification',
    mechanism_of_action: 'Direct provision of GSH to neutralize reactive oxygen and nitrogen species.',
    hallmarks_of_aging_impact: ["Mitochondrial Dysfunction", "Loss of Proteostasis"],
    synergy_notes: {"pairsWellWith": ["vitamin_c", "nac_supplement"], "rationale": "Vitamin C helps keep glutathione in its active, reduced state, extending its half-life in the body."},
    antagonism_notes: {"avoidCombiningWith": ["alcohol"], "rationale": "Alcohol massively depletes liver glutathione; taking it during active drinking wastes the supplement."},
    evidence_quality: 3,
    effect_size_estimate: 4,
    safety_level: 'low_risk',
    cost_tier: 'high',
    effort_level: 'very_low',
    contraindications: [],
    functional_outcomes_to_track: ["energy", "skin_quality", "immunity"],
    status: 'active'
  },
  {
    id: 'urolithin_a',
    slug: 'urolithin-a',
    name: 'Urolithin A (Mitopure)',
    display_name: 'Urolithin A',
    modality_type: 'supplement',
    category: 'Cellular Energy & Recovery',
    brief_description: "A postbiotic compound that triggers mitophagy, the process of clearing out dead and dysfunctional mitochondria.",
    expanded_why: "As we age, our cells accumulate damaged mitochondria, which produce less energy and more toxic exhaust. Urolithin A is the only known compound that specifically activates mitophagy—the cellular recycling process that identifies, destroys, and clears out these broken mitochondria. This makes room for fresh, highly efficient mitochondria, dramatically improving muscular endurance and cellular lifespan.",
    primary_outcome: 'Mitophagy & Muscular Endurance',
    mechanism_of_action: 'Activation of mitophagy pathways (PINK1/Parkin) to clear defective mitochondria.',
    hallmarks_of_aging_impact: ["Mitochondrial Dysfunction", "Loss of Proteostasis"],
    synergy_notes: {"pairsWellWith": ["zone_2_cardio", "nad_precursors"], "rationale": "Zone 2 cardio and NAD+ build new mitochondria (biogenesis). Urolithin A clears the old ones (mitophagy). Together they completely renovate the cellular power grid."},
    antagonism_notes: {"avoidCombiningWith": [], "rationale": "None currently documented, though absorption requires gut activity."},
    evidence_quality: 3,
    effect_size_estimate: 4,
    safety_level: 'low_risk',
    cost_tier: 'premium',
    effort_level: 'very_low',
    contraindications: [],
    functional_outcomes_to_track: ["endurance", "energy", "soreness"],
    status: 'active'
  },
  {
    id: 'nad_iv_therapy',
    slug: 'nad-iv-therapy',
    name: 'NAD+ IV Therapy',
    display_name: 'NAD+ IV',
    modality_type: 'clinical',
    category: 'Longevity Foundation',
    brief_description: "Intravenous infusion of pure NAD+ to immediately replenish severely depleted cellular energy reserves.",
    expanded_why: "NAD+ is the master molecule of metabolism and DNA repair (via PARP enzymes and Sirtuins). While oral precursors (NR/NMN) raise levels slowly, IV NAD+ floods the systemic circulation instantly, bypassing the gut and liver. It is widely used in anti-aging clinics to reverse severe fatigue, combat chronic neuroinflammation, and accelerate recovery from viral illnesses or substance depletion.",
    primary_outcome: 'Immediate Systemic NAD+ Restoration',
    mechanism_of_action: 'Direct intravenous delivery of nicotinamide adenine dinucleotide (NAD+).',
    hallmarks_of_aging_impact: ["Genomic Instability", "Mitochondrial Dysfunction", "Epigenetic Alterations"],
    synergy_notes: {"pairsWellWith": ["methylated_b_complex", "glutathione"], "rationale": "NAD+ metabolism requires massive amounts of methyl donors. Clinics almost always pair NAD+ with a B-vitamin push to prevent methylation depletion."},
    antagonism_notes: {"avoidCombiningWith": ["rapid_infusion_rates"], "rationale": "Pushing NAD+ too fast intravenously causes intense chest pressure, stomach cramping, and nausea. Must be dripped slowly."},
    evidence_quality: 2,
    effect_size_estimate: 5,
    safety_level: 'moderate_risk',
    cost_tier: 'premium',
    effort_level: 'high',
    contraindications: ["Active cancer (theoretical risk of fueling tumor metabolism)"],
    functional_outcomes_to_track: ["energy", "brain_fog", "recovery"],
    status: 'active'
  },
  {
    id: 'methylated_b_complex',
    slug: 'methylated-b-complex',
    name: 'Methylated B-Complex',
    display_name: 'Methyl-B Complex',
    modality_type: 'supplement',
    category: 'Metabolic Regulation',
    brief_description: "Active, bioavailable forms of B-vitamins crucial for cellular energy, DNA repair, and neurotransmitter synthesis.",
    expanded_why: "Roughly 40% of the population has a mutation in the MTHFR gene, severely limiting their ability to convert cheap synthetic folic acid into its active form. A methylated B-complex provides B12 (as methylcobalamin) and Folate (as methylfolate), bypassing this genetic bottleneck. This restores proper methylation, lowers toxic homocysteine levels, and provides the raw materials for serotonin and dopamine production.",
    primary_outcome: 'Methylation & Homocysteine Reduction',
    mechanism_of_action: 'Provides direct methyl donors for the one-carbon metabolism cycle.',
    hallmarks_of_aging_impact: ["Epigenetic Alterations"],
    synergy_notes: {"pairsWellWith": ["creatine", "nad_precursors"], "rationale": "Creatine synthesis consumes 40% of the body's methyl donors. Supplementing B-vitamins protects the methylation cycle."},
    antagonism_notes: {"avoidCombiningWith": ["evening_timing"], "rationale": "B-vitamins, particularly B12, are highly stimulating and can cause severe insomnia if taken late in the day."},
    evidence_quality: 5,
    effect_size_estimate: 3,
    safety_level: 'low_risk',
    cost_tier: 'low',
    effort_level: 'very_low',
    contraindications: ["Over-methylation sensitivity (anxiety/agitation)"],
    functional_outcomes_to_track: ["energy", "mood", "brain_fog"],
    status: 'active'
  },
  {
    id: 'collagen_peptides',
    slug: 'collagen-peptides',
    name: 'Collagen Peptides (10-20g)',
    display_name: 'Collagen',
    modality_type: 'nutrition',
    category: 'Physical Performance',
    brief_description: 'Hydrolyzed amino acid blocks specifically targeted to repair tendons, ligaments, and skin elasticity.',
    expanded_why: "Collagen makes up a third of the protein in the human body, but muscle meats lack the specific amino acids (glycine, proline, hydroxyproline) needed to build it. By taking hydrolyzed collagen 30-60 minutes before exercise, you flood the bloodstream with these specific building blocks just as blood flow to the tendons and ligaments peaks, directly driving the repair of connective tissues and skin.",
    primary_outcome: 'Connective Tissue & Skin Repair',
    mechanism_of_action: 'Provides high concentrations of glycine and proline for extracellular matrix synthesis.',
    hallmarks_of_aging_impact: ["Loss of Proteostasis"],
    synergy_notes: {"pairsWellWith": ["vitamin_c", "resistance_training"], "rationale": "Vitamin C is the mandatory cofactor for the enzyme that cross-links collagen fibers. Without Vitamin C, collagen cannot be synthesized."},
    antagonism_notes: {"avoidCombiningWith": ["complete_protein_replacement"], "rationale": "Collagen is not a complete protein (lacks tryptophan) and should not be counted toward daily muscle-building macros."},
    evidence_quality: 4,
    effect_size_estimate: 3,
    safety_level: 'low_risk',
    cost_tier: 'medium',
    effort_level: 'very_low',
    contraindications: [],
    functional_outcomes_to_track: ["joint_pain", "skin_quality", "recovery"],
    status: 'active'
  },
  {
    id: 'taurine',
    slug: 'taurine',
    name: 'Taurine (1-3g)',
    display_name: 'Taurine',
    modality_type: 'supplement',
    category: 'Metabolic Regulation',
    brief_description: "A conditionally essential amino acid recently discovered to be a major driver of healthspan and longevity.",
    expanded_why: "Recent blockbuster studies have shown that circulating taurine levels drop by 80% as humans age, and restoring these levels dramatically extends healthspan in animal models. Taurine acts as an osmolyte (maintaining cellular hydration), a potent antioxidant in the mitochondria, and a GABA receptor agonist in the brain. It lowers blood pressure, protects the heart, and calms the nervous system.",
    primary_outcome: 'Cellular Hydration & Longevity',
    mechanism_of_action: 'Osmotic regulation and cytoprotection via mitochondrial ROS reduction.',
    hallmarks_of_aging_impact: ["Mitochondrial Dysfunction", "Cellular Senescence"],
    synergy_notes: {"pairsWellWith": ["electrolytes", "magnesium_glycinate"], "rationale": "Works synergistically with electrolytes to pull water into the cells for extreme hydration, often used by endurance athletes."},
    antagonism_notes: {"avoidCombiningWith": ["high_dose_caffeine_only"], "rationale": "Frequently put in energy drinks to counteract the jittery side effects of massive caffeine doses, acting as a biological brake."},
    evidence_quality: 4,
    effect_size_estimate: 4,
    safety_level: 'low_risk',
    cost_tier: 'low',
    effort_level: 'very_low',
    contraindications: [],
    functional_outcomes_to_track: ["endurance", "anxiety", "blood_pressure"],
    status: 'active'
  },
  {
    id: 'blood_donation',
    slug: 'blood-donation',
    name: 'Blood Donation (Iron Depletion)',
    display_name: 'Blood Donation',
    modality_type: 'clinical',
    category: 'Cellular Cleanup',
    brief_description: "Routine therapeutic phlebotomy to lower dangerous systemic iron accumulation and reduce blood viscosity.",
    expanded_why: "Unlike women (who menstruate), men and post-menopausal women have zero biological mechanisms to excrete excess dietary iron. Over decades, iron accumulates in the heart, liver, and brain, driving massive oxidative stress (via the Fenton reaction) and acting as rust inside the body. Donating blood 2-3 times a year effectively dumps this toxic iron burden and lowers the thickness (viscosity) of the blood, significantly reducing cardiovascular risk.",
    primary_outcome: 'Iron Reduction & Cardiovascular Health',
    mechanism_of_action: 'Mechanical removal of red blood cells leading to systemic ferritin depletion.',
    hallmarks_of_aging_impact: ["Mitochondrial Dysfunction", "Chronic Inflammation"],
    synergy_notes: {"pairsWellWith": ["hydration", "post_donation_rest"], "rationale": "Blood volume takes 24-48 hours to replenish; massive water intake is required immediately after."},
    antagonism_notes: {"avoidCombiningWith": ["hiit_vo2_max"], "rationale": "Do not perform intense cardiovascular exercise for 48 hours post-donation, as oxygen carrying capacity is significantly reduced."},
    evidence_quality: 4,
    effect_size_estimate: 5,
    safety_level: 'moderate_risk',
    cost_tier: 'free',
    effort_level: 'medium',
    contraindications: ["Anemia", "Low Ferritin", "Hypotension", "Recent travel to malaria zones"],
    functional_outcomes_to_track: ["energy", "blood_pressure", "ferritin_levels"],
    status: 'active'
  }
];

async function run() {
  const { error } = await supabase.from('modalities').upsert(modalities);
  if (error) {
    console.error("Error inserting modalities:", error);
    process.exit(1);
  } else {
    console.log("Successfully inserted 10 additional protocol modalities.");
  }
}

run();
