const { createClient } = require('@supabase/supabase-js');

const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);

const modalities = [
  {
    id: 'l_theanine',
    slug: 'l-theanine',
    name: 'L-Theanine (100-200mg)',
    display_name: 'L-Theanine',
    modality_type: 'supplement',
    category: 'Nervous System & Sleep',
    brief_description: 'An amino acid found primarily in green tea that promotes relaxation without drowsiness by increasing alpha brain waves and GABA levels.',
    expanded_why: 'L-Theanine crosses the blood-brain barrier and antagonizes glutamate receptors while simultaneously boosting GABA, serotonin, and dopamine. This dual action blunts the jittery, sympathetic nervous system spikes caused by caffeine, while creating a state of "calm focus". Taken at night, it reduces sleep latency and anxiety-induced racing thoughts.',
    primary_outcome: 'Calm Focus & Sleep Latency',
    mechanism_of_action: 'Glutamate receptor antagonist and GABA upregulator.',
    hallmarks_of_aging_impact: ["Altered Intercellular Communication"],
    synergy_notes: {"pairsWellWith": ["caffeine", "magnesium_glycinate", "apigenin"], "rationale": "Creates the ultimate 1:2 ratio with caffeine for flow state, or synergizes with magnesium for deep sleep."},
    antagonism_notes: {"avoidCombiningWith": ["sedatives"], "rationale": "May excessively compound the effects of prescription sleep aids or heavy sedatives."},
    evidence_quality: 4,
    effect_size_estimate: 3,
    safety_level: 'low_risk',
    cost_tier: 'low',
    effort_level: 'very_low',
    contraindications: [],
    functional_outcomes_to_track: ['focus', 'stress', 'sleep_latency'],
    status: 'active'
  },
  {
    id: 'apigenin',
    slug: 'apigenin',
    name: 'Apigenin (50mg)',
    display_name: 'Apigenin',
    modality_type: 'supplement',
    category: 'Nervous System & Sleep',
    brief_description: 'A flavonoid found in high concentrations in chamomile tea, acting as a mild sedative and anxiolytic.',
    expanded_why: 'Apigenin binds to benzodiazepine receptors in the brain (specifically the GABA-A receptor), promoting relaxation and sleep transition without the addictive profile of pharmaceutical benzodiazepines. It is a core component of the Huberman sleep stack, assisting specifically in the transition phase of falling asleep.',
    primary_outcome: 'Sleep Transition',
    mechanism_of_action: 'GABA-A receptor agonist.',
    hallmarks_of_aging_impact: ["Altered Intercellular Communication"],
    synergy_notes: {"pairsWellWith": ["magnesium_glycinate", "l_theanine"], "rationale": "Completes the trifecta of non-hormonal sleep initiation."},
    antagonism_notes: {"avoidCombiningWith": ["high_dose_estrogen"], "rationale": "Apigenin is a mild aromatase inhibitor and may interact with hormonal therapies."},
    evidence_quality: 3,
    effect_size_estimate: 2,
    safety_level: 'low_risk',
    cost_tier: 'medium',
    effort_level: 'very_low',
    contraindications: ['Hormone-sensitive conditions'],
    functional_outcomes_to_track: ['sleep_latency', 'stress'],
    status: 'active'
  },
  {
    id: 'delay_caffeine',
    slug: 'delay-caffeine',
    name: 'Delay Caffeine 90-120 Minutes',
    display_name: 'Delay Caffeine (90m)',
    modality_type: 'habit',
    category: 'Circadian Alignment',
    brief_description: 'Waiting at least 90 minutes after waking before consuming any caffeine to prevent the afternoon energy crash.',
    expanded_why: 'Adenosine is a molecule that builds up and causes sleep pressure. During sleep, adenosine is cleared. If caffeine (an adenosine receptor antagonist) is consumed immediately upon waking, it blocks receptors before the remaining sleep-induced adenosine is cleared. When the caffeine wears off, a massive backlog of adenosine floods the receptors, causing a severe afternoon crash. Delaying allows natural cortisol to clear the residual adenosine first.',
    primary_outcome: 'Afternoon Energy Stability',
    mechanism_of_action: 'Adenosine receptor blockade timing optimization.',
    hallmarks_of_aging_impact: ["Altered Intercellular Communication"],
    synergy_notes: {"pairsWellWith": ["morning_sunlight", "hydration"], "rationale": "Sunlight provides the cortisol spike needed to wake up naturally while waiting for coffee."},
    antagonism_notes: {"avoidCombiningWith": ["poor_sleep"], "rationale": "Extremely difficult to execute if sleep deprived; users may need to titrate the delay slowly."},
    evidence_quality: 3,
    effect_size_estimate: 4,
    safety_level: 'low_risk',
    cost_tier: 'free',
    effort_level: 'high',
    contraindications: [],
    functional_outcomes_to_track: ['energy', 'brain_fog'],
    status: 'active'
  },
  {
    id: 'mouth_taping',
    slug: 'mouth-taping',
    name: 'Sleep Mouth Taping',
    display_name: 'Mouth Taping',
    modality_type: 'habit',
    category: 'Nervous System & Sleep',
    brief_description: 'Using a small piece of porous, medical-grade tape to keep the lips lightly sealed during sleep, forcing nasal breathing.',
    expanded_why: 'Nasal breathing during sleep significantly increases nitric oxide production in the paranasal sinuses, acting as a vasodilator to increase oxygen delivery. It prevents mouth-breathing-induced dehydration, reduces snoring, and shifts the autonomic nervous system toward parasympathetic dominance, radically increasing the percentage of deep and REM sleep.',
    primary_outcome: 'Sleep Quality & Snoring Reduction',
    mechanism_of_action: 'Nitric oxide upregulation and parasympathetic tone maintenance.',
    hallmarks_of_aging_impact: ["Mitochondrial Dysfunction"],
    synergy_notes: {"pairsWellWith": ["nasal_strips"], "rationale": "Opens the nasal airway mechanically while the tape ensures it is utilized."},
    antagonism_notes: {"avoidCombiningWith": ["severe_nasal_congestion"], "rationale": "Do not use if the nasal airway is fully obstructed by illness or deviated septum."},
    evidence_quality: 3,
    effect_size_estimate: 4,
    safety_level: 'low_risk',
    cost_tier: 'low',
    effort_level: 'low',
    contraindications: ['Sleep apnea (without CPAP)', 'Severe nasal obstruction'],
    functional_outcomes_to_track: ['sleep_quality', 'waking_restedness', 'energy'],
    status: 'active'
  },
  {
    id: 'blue_light_blocking',
    slug: 'blue-light-blocking',
    name: 'Blue Light Blocking Glasses (Evening)',
    display_name: 'Blue Light Blockers',
    modality_type: 'habit',
    category: 'Circadian Alignment',
    brief_description: 'Wearing amber or red-tinted glasses 2-3 hours before bed to block artificial blue and green light.',
    expanded_why: 'Melatonin secretion from the pineal gland is powerfully suppressed by light in the 450-480nm range (blue light emitted by screens and LEDs). By physically blocking these wavelengths after sunset, the brain registers "biological darkness", allowing endogenous melatonin to rise naturally, dramatically reducing sleep latency and improving sleep architecture without supplements.',
    primary_outcome: 'Endogenous Melatonin Production',
    mechanism_of_action: 'Prevention of ipRGC photo-entrainment and melatonin suppression.',
    hallmarks_of_aging_impact: ["Altered Intercellular Communication"],
    synergy_notes: {"pairsWellWith": ["dim_lights", "screen_curfews"], "rationale": "Physical blockers are the last line of defense; environmental dimming is the first."},
    antagonism_notes: {"avoidCombiningWith": ["bright_overhead_lights"], "rationale": "Light can still hit the retinas from the periphery if glasses aren't wraparound."},
    evidence_quality: 4,
    effect_size_estimate: 4,
    safety_level: 'low_risk',
    cost_tier: 'medium',
    effort_level: 'low',
    contraindications: [],
    functional_outcomes_to_track: ['sleep_latency', 'sleep_quality'],
    status: 'active'
  },
  {
    id: 'berberine',
    slug: 'berberine',
    name: 'Berberine (500mg)',
    display_name: 'Berberine',
    modality_type: 'supplement',
    category: 'Metabolic Regulation',
    brief_description: 'A bioactive alkaloid extracted from several plants, acting as a potent over-the-counter glucose disposal agent.',
    expanded_why: 'Berberine is often referred to as "OTC Metformin." It activates AMPK, reduces hepatic gluconeogenesis, and increases glucose uptake into muscle cells. Clinical trials have shown its efficacy in lowering HbA1c and fasting blood glucose is nearly identical to metformin, making it an excellent alternative for those seeking metabolic regulation without a prescription.',
    primary_outcome: 'Glucose Regulation',
    mechanism_of_action: 'AMPK activation and alteration of gut microbiota.',
    hallmarks_of_aging_impact: ["Deregulated Nutrient Sensing"],
    synergy_notes: {"pairsWellWith": ["carbohydrate_meals"], "rationale": "Should be taken exactly prior to or alongside a carbohydrate load for maximum effect."},
    antagonism_notes: {"avoidCombiningWith": ["metformin", "macrolide_antibiotics"], "rationale": "Combining with Metformin can cause severe hypoglycemia. It inhibits CYP3A4, altering drug metabolism."},
    evidence_quality: 4,
    effect_size_estimate: 4,
    safety_level: 'moderate_risk',
    cost_tier: 'medium',
    effort_level: 'very_low',
    contraindications: ['Pregnancy', 'Concurrent use with other hypoglycemic agents'],
    functional_outcomes_to_track: ['energy', 'brain_fog'],
    status: 'active'
  },
  {
    id: 'optic_flow',
    slug: 'optic-flow',
    name: 'Optic Flow / Forward Ambulation',
    display_name: 'Optic Flow (Walk)',
    modality_type: 'habit',
    category: 'Nervous System & Sleep',
    brief_description: 'Walking or running outdoors where visual objects pass by your eyes, generating "optic flow" to quiet the amygdala.',
    expanded_why: 'Forward ambulation generates lateral eye movements as objects pass in the peripheral vision. These specific eye movements suppress the amygdala and reduce sympathetic nervous system arousal (the basis of EMDR therapy). A 10-20 minute walk generates enough optic flow to significantly rapidly reduce acute stress and anxiety.',
    primary_outcome: 'Acute Stress Reduction',
    mechanism_of_action: 'Amygdala suppression via lateral eye movement signaling.',
    hallmarks_of_aging_impact: ["Altered Intercellular Communication"],
    synergy_notes: {"pairsWellWith": ["morning_sunlight", "podcasts"], "rationale": "Combines perfectly with morning light exposure to stack circadian and stress benefits."},
    antagonism_notes: {"avoidCombiningWith": ["treadmills"], "rationale": "Treadmills do not generate optic flow since the visual field is static, neutralizing the neurological benefit."},
    evidence_quality: 3,
    effect_size_estimate: 3,
    safety_level: 'low_risk',
    cost_tier: 'free',
    effort_level: 'low',
    contraindications: [],
    functional_outcomes_to_track: ['stress', 'mood'],
    status: 'active'
  },
  {
    id: 'ashwagandha_ksm66',
    slug: 'ashwagandha-ksm66',
    name: 'Ashwagandha (KSM-66)',
    display_name: 'Ashwagandha',
    modality_type: 'supplement',
    category: 'Nervous System & Sleep',
    brief_description: 'A powerful adaptogenic herb shown to significantly lower baseline cortisol and subjective stress.',
    expanded_why: 'Ashwagandha modulates the HPA (Hypothalamic-Pituitary-Adrenal) axis, buffering the release of cortisol in response to stress. The KSM-66 extract specifically has dozens of human trials showing massive reductions in serum cortisol (up to 30%). It is best cycled (e.g., 4 weeks on, 2 weeks off) to prevent anhedonia resulting from completely blunted cortisol curves.',
    primary_outcome: 'Cortisol Reduction',
    mechanism_of_action: 'HPA axis modulation and GABA-mimetic activity.',
    hallmarks_of_aging_impact: ["Altered Intercellular Communication"],
    synergy_notes: {"pairsWellWith": ["magnesium_glycinate"], "rationale": "Stacks well in the evening for profound systemic relaxation."},
    antagonism_notes: {"avoidCombiningWith": ["continuous_long_term_use"], "rationale": "Should not be taken continuously year-round without breaks due to risks of emotional blunting/anhedonia."},
    evidence_quality: 4,
    effect_size_estimate: 4,
    safety_level: 'moderate_risk',
    cost_tier: 'medium',
    effort_level: 'very_low',
    contraindications: ['Hyperthyroidism', 'Autoimmune conditions'],
    functional_outcomes_to_track: ['stress', 'sleep_quality', 'mood'],
    status: 'active'
  },
  {
    id: 'rhodiola_rosea',
    slug: 'rhodiola-rosea',
    name: 'Rhodiola Rosea (3% Salidroside)',
    display_name: 'Rhodiola Rosea',
    modality_type: 'supplement',
    category: 'Physical Performance',
    brief_description: 'An adaptogen that prevents fatigue and maintains cognitive performance under physical or mental exhaustion.',
    expanded_why: 'Unlike Ashwagandha which relaxes, Rhodiola is highly stimulating. It influences the release and reuptake of monoamines (dopamine, serotonin, norepinephrine) and reduces the perception of fatigue during intense exercise or sleep deprivation. It is an excellent pre-workout alternative for those trying to cycle off caffeine.',
    primary_outcome: 'Fatigue Resistance',
    mechanism_of_action: 'MAO inhibition and stimulation of monoamine receptors.',
    hallmarks_of_aging_impact: ["Altered Intercellular Communication"],
    synergy_notes: {"pairsWellWith": ["resistance_training", "creatine"], "rationale": "Amplifies power output and endurance when taken 30 mins before training."},
    antagonism_notes: {"avoidCombiningWith": ["evening_use", "ssri_medications"], "rationale": "Will absolutely cause insomnia if taken late. Mild risk of serotonin syndrome if combined with high-dose SSRIs."},
    evidence_quality: 3,
    effect_size_estimate: 3,
    safety_level: 'low_risk',
    cost_tier: 'medium',
    effort_level: 'very_low',
    contraindications: ['Bipolar disorder (may trigger mania)'],
    functional_outcomes_to_track: ['energy', 'endurance', 'focus'],
    status: 'active'
  },
  {
    id: 'glycine_3g',
    slug: 'glycine-3g',
    name: 'Glycine (3g)',
    display_name: 'Glycine (Sleep)',
    modality_type: 'supplement',
    category: 'Nervous System & Sleep',
    brief_description: 'An inhibitory amino acid that actively drops core body temperature to facilitate deeper sleep.',
    expanded_why: 'Glycine acts as a neurotransmitter in the central nervous system. When taken in a 3g dose before bed, it increases blood flow to the extremities, effectively pulling heat away from the core. A dropping core body temperature is a strict biological requirement to enter slow-wave (deep) sleep. It also blunts the subjective feeling of fatigue the next morning if sleep is restricted.',
    primary_outcome: 'Core Temperature Drop & Deep Sleep',
    mechanism_of_action: 'NMDA receptor co-agonist and peripheral vasodilator.',
    hallmarks_of_aging_impact: ["Altered Intercellular Communication"],
    synergy_notes: {"pairsWellWith": ["magnesium_bisglycinate", "cold_bedroom"], "rationale": "Magnesium bisglycinate already contains glycine; taking extra pure glycine maxes out the cooling effect."},
    antagonism_notes: {"avoidCombiningWith": ["clozapine"], "rationale": "Can interfere with the efficacy of certain antipsychotics."},
    evidence_quality: 4,
    effect_size_estimate: 3,
    safety_level: 'low_risk',
    cost_tier: 'low',
    effort_level: 'very_low',
    contraindications: [],
    functional_outcomes_to_track: ['sleep_quality', 'waking_restedness'],
    status: 'active'
  }
];

async function run() {
  const { error } = await supabase.from('modalities').upsert(modalities);
  if (error) {
    console.error("Error inserting modalities:", error);
    process.exit(1);
  } else {
    console.log("Successfully inserted 10 new protocol modalities.");
  }
}

run();
