import { Modality, ProtocolStep, UserProfile, DailyProtocolTask } from '../types'

/**
 * Smart Modality Timing Resolver Engine
 * Guarantees that all current and future modalities automatically map to their optimal 
 * timing block (morning, afternoon, evening, bedtime, etc.) instead of defaulting to 'anytime'.
 */

export type OptimalTimingSlot = 
  | 'morning'
  | 'morning_supplement_stack'
  | 'midday'
  | 'midday_stack'
  | 'afternoon'
  | 'late_afternoon'
  | 'post_meal'
  | 'evening'
  | 'evening_supplement_stack'
  | 'wind_down'
  | 'bedtime'
  | 'pre_bed'
  | 'anytime'

export interface MultiDoseSlot {
  doseNumber: number
  totalDoses: number
  label: string
  slot: string
}

/**
 * Resolves a canonical timing slot from any natural text or preset string (e.g. from Dosage/Manage modals).
 */
export function resolveSlotFromTimingString(timingStr?: string, isSupplement: boolean = false): string {
  if (!timingStr || !timingStr.trim()) return 'anytime'
  const lower = timingStr.toLowerCase()

  // Clean away weekly frequency prefixes like "3–4x per week • "
  const clean = lower.includes('•') ? lower.split('•').slice(1).join('•').trim() : lower

  // Pre-Bed (30-60m before sleep)
  if (clean.includes('pre_bed') || clean.includes('pre-bed') || clean.includes('30m before bed') || clean.includes('60m before bed')) {
    return 'pre_bed'
  }

  // Bedtime / Sleep / Overnight
  if (
    clean.includes('bed') || clean.includes('night') || clean.includes('sleep') || 
    clean.includes('9:00 pm') || clean.includes('10:00 pm') || clean.includes('11:00 pm') ||
    clean.includes('overnight')
  ) {
    return 'bedtime'
  }

  // Evening / Post-Meal / Dinner (Checked before generic 8:00 PM cutoff to avoid misrouting Evening presets to wind_down)
  if (
    clean.includes('evening') || clean.includes('dinner') || 
    clean.includes('post-meal') || clean.includes('post meal') || 
    clean.includes('postprandial') || clean.includes('after eating') ||
    clean.includes('6:00 pm') || clean.includes('7:00 pm')
  ) {
    return isSupplement ? 'evening_supplement_stack' : 'evening'
  }

  // Wind down / evening cutoffs
  if (
    clean.includes('wind down') || clean.includes('wind_down') || clean.includes('winddown') ||
    clean.includes('screen cutoff') || clean.includes('digital sunset') || clean.includes('caffeine cutoff') ||
    clean.includes('blue light') || clean.includes('dimming') || clean.includes('8:30 pm') ||
    (clean.includes('8:00 pm') && !clean.includes('evening') && !clean.includes('post-meal'))
  ) {
    return 'wind_down'
  }

  // Late afternoon / Afternoon / Workout
  if (clean.includes('afternoon') || clean.includes('4:00 pm') || clean.includes('5:00 pm') || clean.includes('late afternoon') || clean.includes('2:00 pm – 4:00 pm')) {
    return 'afternoon'
  }

  // Midday / Lunch / Noon
  if (clean.includes('mid-day') || clean.includes('midday') || clean.includes('lunch') || clean.includes('12:00 pm') || clean.includes('1:00 pm') || clean.includes('noon')) {
    return isSupplement ? 'midday_stack' : 'midday'
  }

  // Morning / Breakfast / Waking / Fasted AM
  if (
    clean.includes('waking') || clean.includes('wake') || clean.includes('morning') || 
    clean.includes('breakfast') || clean.includes('6:00 am') || clean.includes('7:00 am') || 
    clean.includes('8:00 am') || clean.includes('9:00 am') || clean.includes('10:00 am') ||
    clean.includes('fasted am') || clean.includes('upon waking')
  ) {
    return isSupplement ? 'morning_supplement_stack' : 'morning'
  }

  return 'anytime'
}

/**
 * Universal Multi-Dose Splitter Parser
 * Parses multi-dose timing strings generated by DosageDetailModal, ManageTaskModal, or protocol steps
 * (e.g. "2x Daily: Dose 1 (Morning...) + Dose 2 (Pre-Bed...)" or "3x/wk • Morning & Evening")
 */
export function parseMultiDoseTimingSlots(timingStr?: string, isSupplement: boolean = false): MultiDoseSlot[] {
  if (!timingStr) return []
  const raw = timingStr.trim()
  const lower = raw.toLowerCase()

  const formatSlot = (slotCandidate: string, fallbackDefault: string): string => {
    const resolved = resolveSlotFromTimingString(slotCandidate, isSupplement)
    if (resolved && resolved !== 'anytime') return resolved
    return isSupplement 
      ? (fallbackDefault === 'morning' ? 'morning_supplement_stack' : fallbackDefault === 'evening' ? 'evening_supplement_stack' : fallbackDefault === 'midday' ? 'midday_stack' : fallbackDefault)
      : fallbackDefault
  }

  const slotToLabel = (slot: string, doseNum: number): string => {
    const s = slot.toLowerCase()
    if (s.includes('morning') || s.includes('wake')) return `Dose ${doseNum} (Morning)`
    if (s.includes('midday') || s.includes('lunch') || s.includes('noon')) return `Dose ${doseNum} (Midday)`
    if (s.includes('afternoon')) return `Dose ${doseNum} (Afternoon)`
    if (s.includes('evening') || s.includes('dinner')) return `Dose ${doseNum} (Evening)`
    if (s.includes('pre_bed') || s.includes('pre-bed')) return `Dose ${doseNum} (Pre-Bed)`
    if (s.includes('bed') || s.includes('night') || s.includes('sleep')) return `Dose ${doseNum} (Bedtime)`
    return `Dose ${doseNum}`
  }

  // 1. Check for comma-separated or semicolon-separated timing slots
  // (e.g. "morning_supplement_stack,evening_supplement_stack", "morning,evening", "waking,bedtime")
  if (raw.includes(',') || raw.includes(';')) {
    // Only treat as delimited slots if not a continuous grammatical sentence without slots
    const rawTokens = raw.split(/[,;]/).map(t => t.trim()).filter(Boolean)
    if (rawTokens.length >= 2) {
      const resolvedTokens = rawTokens.map(t => resolveSlotFromTimingString(t, isSupplement))
      const validSlotsCount = resolvedTokens.filter(s => s !== 'anytime').length
      
      // If at least two tokens resolve to known circadian slots
      if (validSlotsCount >= 2) {
        return resolvedTokens.map((slot, idx) => {
          const doseNum = idx + 1
          const cleanSlot = slot === 'anytime' 
            ? (idx === 0 ? (isSupplement ? 'morning_supplement_stack' : 'morning') : (isSupplement ? 'evening_supplement_stack' : 'evening'))
            : slot
          return {
            doseNumber: doseNum,
            totalDoses: resolvedTokens.length,
            label: slotToLabel(cleanSlot, doseNum),
            slot: cleanSlot
          }
        })
      }
    }
  }

  // 2. Check for standard 2x / 3x daily modal serialized formats:
  // "2x Daily: Dose 1 (Morning / With Breakfast (8:00 AM – 10:00 AM)) + Dose 2 (Pre-Bed / Night (9:00 PM – 11:00 PM))"
  // "3x Daily: Dose 1 (...) + Dose 2 (...) + Dose 3 (...)"
  if (raw.includes('+ Dose 2') || (raw.includes('Dose 1') && raw.includes('+')) || ((raw.includes('2x Daily:') || raw.includes('3x Daily:')) && raw.includes('+'))) {
    const parts = raw.split(/\s*\+\s*/)
    const cleanPart = (str?: string) => {
      if (!str) return ''
      // Strip weekly prefix if present e.g. "3x/wk • " or "7x/wk • "
      const s = str.includes('•') ? str.split('•').slice(1).join('•').trim() : str
      return s
        .replace(/^[23]x\s*(?:daily|per week)?:\s*/i, '')
        .replace(/^Dose \d+\s*\(/i, '')
        .replace(/\)$/, '')
        .trim()
    }

    const slots: MultiDoseSlot[] = []
    const totalDoses = parts.length

    parts.forEach((p, idx) => {
      const doseNum = idx + 1
      const cleaned = cleanPart(p)
      const slot = resolveSlotFromTimingString(cleaned, isSupplement)
      const defaultLabels = ['Morning', 'Midday / PM', 'Evening / Night']
      const derivedSlot = slot === 'anytime' 
        ? (doseNum === 1 ? (isSupplement ? 'morning_supplement_stack' : 'morning') : doseNum === 2 ? (isSupplement ? 'evening_supplement_stack' : 'evening') : 'bedtime') 
        : slot
      const labelShort = slotToLabel(derivedSlot, doseNum).replace(`Dose ${doseNum} (`, '').replace(')', '') || defaultLabels[idx] || `Dose ${doseNum}`
      
      slots.push({
        doseNumber: doseNum,
        totalDoses: totalDoses,
        label: `Dose ${doseNum} (${labelShort})`,
        slot: derivedSlot
      })
    })

    if (slots.length >= 2) return slots
  }

  // 3. Format: "Morning & Bedtime", "Morning & Pre-Bed", "Morning & Night"
  if (
    (lower.includes('morning') || lower.includes('waking') || lower.includes('am')) && 
    (lower.includes('bedtime') || lower.includes('pre-bed') || lower.includes('pre_bed') || lower.includes('night') || lower.includes('sleep'))
  ) {
    const bedSlot = lower.includes('pre-bed') || lower.includes('pre_bed') ? 'pre_bed' : 'bedtime'
    return [
      { doseNumber: 1, totalDoses: 2, label: 'Dose 1 (Morning)', slot: isSupplement ? 'morning_supplement_stack' : 'morning' },
      { doseNumber: 2, totalDoses: 2, label: bedSlot === 'pre_bed' ? 'Dose 2 (Pre-Bed)' : 'Dose 2 (Bedtime)', slot: bedSlot }
    ]
  }

  // 4. Format: "Morning & Midday", "Morning and Midday", "Morning / Midday"
  if (lower.includes('morning & midday') || lower.includes('morning and midday') || lower.includes('morning / midday') || lower.includes('morning/midday')) {
    return [
      { doseNumber: 1, totalDoses: 2, label: 'Dose 1 (Morning)', slot: isSupplement ? 'morning_supplement_stack' : 'morning' },
      { doseNumber: 2, totalDoses: 2, label: 'Dose 2 (Midday)', slot: isSupplement ? 'midday_stack' : 'midday' }
    ]
  }

  // 5. Format: "Midday & Evening", "Midday and Evening", "Midday / Evening"
  if (lower.includes('midday & evening') || lower.includes('midday and evening') || lower.includes('midday / evening') || lower.includes('midday/evening')) {
    return [
      { doseNumber: 1, totalDoses: 2, label: 'Dose 1 (Midday)', slot: isSupplement ? 'midday_stack' : 'midday' },
      { doseNumber: 2, totalDoses: 2, label: 'Dose 2 (Evening)', slot: isSupplement ? 'evening_supplement_stack' : 'evening' }
    ]
  }

  // 6. Format: 3x Daily or TID or "Morning, Midday & Evening"
  if (
    lower.includes('3x/day') || 
    lower.includes('3x daily') || 
    lower.includes('3x_day') || 
    lower.includes('tid') || 
    lower.includes('morning, midday & evening') || 
    lower.includes('morning, midday and evening') ||
    lower.includes('morning, midday, evening') ||
    lower.includes('three times daily')
  ) {
    return [
      { doseNumber: 1, totalDoses: 3, label: 'Dose 1 (Morning)', slot: isSupplement ? 'morning_supplement_stack' : 'morning' },
      { doseNumber: 2, totalDoses: 3, label: 'Dose 2 (Midday)', slot: isSupplement ? 'midday_stack' : 'midday' },
      { doseNumber: 3, totalDoses: 3, label: 'Dose 3 (Evening)', slot: isSupplement ? 'evening_supplement_stack' : 'evening' }
    ]
  }

  // 7. Format: 2x Daily, AM/PM, Morning & Evening, Split Doses
  if (
    lower.includes('morning & evening') || 
    lower.includes('morning and evening') || 
    lower.includes('morning / evening') || 
    lower.includes('morning/evening') || 
    lower.includes('split am / pm') || 
    lower.includes('split am/pm') || 
    lower.includes('am/pm') || 
    lower.includes('am / pm') || 
    lower.includes('2x/day') || 
    lower.includes('2x daily') || 
    lower.includes('2x_day') || 
    lower.includes('bid') ||
    lower.includes('twice daily') ||
    lower.includes('twice a day') ||
    lower.includes('2 doses') ||
    lower.includes('split dose') ||
    lower.includes('split into 2') ||
    lower.includes('divided dose')
  ) {
    return [
      { doseNumber: 1, totalDoses: 2, label: 'Dose 1 (Morning)', slot: isSupplement ? 'morning_supplement_stack' : 'morning' },
      { doseNumber: 2, totalDoses: 2, label: 'Dose 2 (Evening)', slot: isSupplement ? 'evening_supplement_stack' : 'evening' }
    ]
  }

  return []
}

export function resolveOptimalTimingSlot(
  modality?: Modality | null,
  step?: ProtocolStep | null,
  fallbackSlot: string = 'anytime',
  userProfile?: UserProfile | null,
  customTiming?: string | null
): string {
  const isSupplement = (modality?.category || '').toLowerCase().includes('supplement') || 
                       (modality?.modality_type || '').toLowerCase() === 'supplement'

  // GUARD: If customTiming represents a multi-dose schedule (multiple distinct timing slots),
  // and fallbackSlot is ALREADY an assigned concrete single slot (e.g. s.slot from a split dose),
  // NEVER collapse the split dose into a single arbitrary slot! Keep fallbackSlot!
  if (customTiming && customTiming.trim()) {
    const multiSlots = parseMultiDoseTimingSlots(customTiming, isSupplement)
    if (multiSlots.length >= 2 && fallbackSlot && fallbackSlot !== 'anytime') {
      return normalizeSlot(fallbackSlot)
    }
    const fromCustom = resolveSlotFromTimingString(customTiming, isSupplement)
    if (fromCustom && fromCustom !== 'anytime') {
      return normalizeSlot(fromCustom)
    }
  }

  // 1. If user has explicit primary workout window preference in profile, apply to workouts
  if (modality && userProfile?.primary_workout_window) {
    const text = `${modality.name || ''} ${modality.category || ''} ${modality.timing_summary || ''}`.toLowerCase()
    const isWorkout = 
      text.includes('resistance training') || 
      text.includes('strength') || 
      text.includes('hypertrophy') || 
      text.includes('decathlon') ||
      text.includes('vo2 max') ||
      text.includes('sprint')
    
    if (isWorkout) {
      const window = userProfile.primary_workout_window.toLowerCase()
      if (window.includes('morning')) return 'morning'
      if (window.includes('midday')) return 'midday'
      if (window.includes('afternoon')) return 'afternoon'
      if (window.includes('evening')) return 'evening'
    }
  }

  // 2. Explicit task timing slot if non-empty and not 'anytime'
  if (fallbackSlot && fallbackSlot !== 'anytime') {
    return normalizeSlot(fallbackSlot)
  }

  // 3. Explicit protocol step timing slot if non-empty and not 'anytime'
  if (step?.timing_slot && step.timing_slot !== 'anytime') {
    return normalizeSlot(step.timing_slot)
  }

  // 4. Explicit modality default timing slot if non-empty and not 'anytime'
  if (modality?.default_timing_slot && modality.default_timing_slot !== 'anytime') {
    return normalizeSlot(modality.default_timing_slot)
  }

  // 5. Comprehensive Keyword & Semantic Resolver
  if (modality) {
    const timing = (modality.timing_summary || '').toLowerCase()
    const name = (modality.name || '').toLowerCase()
    const cat = (modality.category || '').toLowerCase()
    const inst = (modality.instructions || '').toLowerCase()
    const text = `${timing} ${name} ${cat} ${inst}`.toLowerCase()

    // Wind Down / Evening Cutoffs (Checked before generic bed/sleep)
    if (
      timing.includes('wind down') || timing.includes('wind_down') || timing.includes('winddown') || text.includes('4-7-8') || 
      name.includes('screen time reduction') || timing.includes('screen') || timing.includes('cutoff') ||
      text.includes('caffeine cutoff') || text.includes('alcohol sleep-protection') ||
      name.includes('blue-light') || timing.includes('dimming') || name.includes('blue light')
    ) {
      return 'wind_down'
    }

    // Pre-Bed (30-60m before sleep)
    if (timing.includes('pre_bed') || timing.includes('pre-bed') || text.includes('30m before bed') || text.includes('60m before bed')) {
      return 'pre_bed'
    }

    // Bedtime / Sleep / Overnight / Dental Nightly
    if (
      timing.includes('bed') || timing.includes('nightly') || 
      timing.includes('overnight') || timing.includes('before bed') || timing.includes('sleep environment') ||
      name.includes('flossing') || name.includes('mouth tap') || name.includes('sleep environment') ||
      text.includes('before sleep') || text.includes('sleep architecture') ||
      name.includes('sleep consistency')
    ) {
      return 'bedtime'
    }

    // Evening / Dinner / Sauna
    if (
      timing.includes('evening') || timing.includes('dinner') || timing.includes('night') || 
      timing.includes('dusk') || name.includes('sauna') || timing.includes('sauna') ||
      text.includes('with dinner') || text.includes('evening with') || text.includes('dinner / daily') ||
      text.includes('dinner with food') || text.includes('dinner / evening')
    ) {
      return isSupplement ? 'evening_supplement_stack' : 'evening'
    }

    // Post-Meal / Glycemic walk
    if (
      timing.includes('post-meal') || timing.includes('post meal') || timing.includes('postprandial') ||
      name.includes('postprandial') || text.includes('after eating') || text.includes('after major meals') ||
      (name.includes('soleus') && text.includes('post-meal')) || (name.includes('walk') && text.includes('post-meal'))
    ) {
      return 'post_meal'
    }

    // Afternoon / Late Afternoon / Strength / Workouts
    if (
      timing.includes('afternoon') || timing.includes('2-6 pm') || timing.includes('peak body temp') ||
      timing.includes('4:00 pm') || text.includes('resistance training') || text.includes('hypertrophy') ||
      text.includes('strength training') || text.includes('coherent') || text.includes('resonant') ||
      text.includes('vo2 max') || text.includes('sprints')
    ) {
      return 'afternoon'
    }

    // Midday / Lunch / Desk micro-movement
    if (
      timing.includes('midday') || timing.includes('lunch') || timing.includes('noon') || 
      timing.includes('11:00 am') || timing.includes('12:00 pm') || timing.includes('1:00 pm') ||
      timing.includes('desk micro-movement') || name.includes('nut pudding') || text.includes('box breath')
    ) {
      return isSupplement ? 'midday_stack' : 'midday'
    }

    // Morning / Waking / Breakfast / Morning Supplements / Light / Cold
    if (
      timing.includes('morning') || timing.includes('wake') || timing.includes('waking') ||
      timing.includes('am') || timing.includes('fasted') || timing.includes('breakfast') ||
      name.includes('light') || name.includes('sunlight') || name.includes('cold') || 
      name.includes('coffee') || name.includes('caffeine') || name.includes('sigh') ||
      name.includes('super veggie') || text.includes('morning meal') || text.includes('upon waking') ||
      name.includes('red light') || name.includes('photobiomodulation')
    ) {
      return isSupplement ? 'morning_supplement_stack' : 'morning'
    }
  }

  return 'anytime'
}

function normalizeSlot(slot: string): string {
  const s = slot.toLowerCase().trim()
  if (s.includes('wind_down') || s.includes('winddown') || s.includes('wind down') || s.includes('wind-down')) return 'wind_down'
  if (s.includes('pre_bed') || s.includes('pre-bed') || s.includes('pre bed')) return 'pre_bed'
  if (s.includes('bed') || s.includes('sleep') || s.includes('nightly') || s.includes('overnight')) return 'bedtime'
  if (s.includes('evening_supplement') || s.includes('dinner_stack')) return 'evening_supplement_stack'
  if (s.includes('evening') || s.includes('dinner')) return 'evening'
  if (s.includes('post_meal') || s.includes('post-meal') || s.includes('post meal') || s.includes('postprandial')) return 'post_meal'
  if (s.includes('pre_meal') || s.includes('pre-meal') || s.includes('pre meal')) return 'pre_meal'
  if (s.includes('morning_supplement')) return 'morning_supplement_stack'
  if (s.includes('morning') || s.includes('wake') || s.includes('waking')) return 'morning'
  if (s.includes('midday_stack') || s.includes('lunch_stack')) return 'midday_stack'
  if (s.includes('midday') || s.includes('lunch') || s.includes('noon')) return 'midday'
  if (s.includes('afternoon') || s.includes('workout')) return 'afternoon'
  return s
}

/**
 * Canonical mapping of timing slots to their circadian block sequence order (0 to 15, 99 for anytime).
 * Mirrors the Today feed grouping sequence.
 */
export function getTimeBlockOrder(slot: string): number {
  if (!slot) return 50
  const s = slot.toLowerCase().trim()
  if (s.includes('wake') || s.includes('sunrise') || s.includes('dawn')) return 0
  if (s.includes('morning_routine')) return 1
  if (s.includes('morning_supplement') || s.includes('fasted_am') || s.includes('am_stack') || s.includes('am stack')) return 3
  if (s.includes('first_meal') || s.includes('breakfast') || s.includes('first meal') || s.includes('meal_1')) return 4
  if (s.includes('morning') || s.includes('am')) return 2
  if (s.includes('midday_stack') || s.includes('lunch_stack')) return 6
  if (s.includes('midday') || s.includes('noon') || s.includes('lunch')) return 5
  if (s.includes('afternoon') || s.includes('workout') || s.includes('training')) return 7
  if (s.includes('late_afternoon')) return 8
  if (s.includes('pre_meal') || s.includes('pre-meal') || s.includes('pre meal')) return 9
  if (s.includes('post_meal') || s.includes('postprandial') || s.includes('post meal') || s.includes('post-meal')) return 10
  if (s.includes('evening_supplement') || s.includes('dinner_stack') || s.includes('pm_stack') || s.includes('pm stack')) return 12
  if (s.includes('evening') || s.includes('dinner') || s.includes('dusk')) return 11
  if (s.includes('wind_down') || s.includes('winddown') || s.includes('wind down') || s.includes('wind-down') || s.includes('wind')) return 13
  if (s.includes('pre_bed') || s.includes('pre-bed') || s.includes('pre bed')) return 14
  if (s.includes('bed') || s.includes('night') || s.includes('sleep') || s.includes('overnight')) return 15
  if (s.includes('anytime')) return 99
  return 50
}

/**
 * Calculates a task's chronological position (in minutes from midnight)
 * using scheduled_time, resolved circadian timing slot, and user workout preferences.
 */
export function getTaskChronologicalWeight(
  task: DailyProtocolTask,
  userProfile?: UserProfile | null
): number {
  if (task.scheduled_time && task.scheduled_time.includes(':')) {
    const [h, m] = task.scheduled_time.split(':').map(Number)
    if (!isNaN(h)) {
      return h * 60 + (isNaN(m) ? 0 : m)
    }
  }

  const mod = task.protocol_step?.modality || task.loose_modality
  const customTiming = task.custom_timing || task.execution_details?.custom_timing
  const isSplit = Boolean(task.execution_details?.split_dose_number || task.id?.includes('-split-'))
  const slot = (isSplit && task.timing_slot && task.timing_slot !== 'anytime')
    ? task.timing_slot
    : resolveOptimalTimingSlot(mod, task.protocol_step, task.timing_slot, userProfile, customTiming)
  const order = getTimeBlockOrder(slot)

  switch (order) {
    case 0: return 6 * 60       // 6:00 AM (Waking / Sunrise)
    case 1: return 7 * 60       // 7:00 AM (Morning Routine)
    case 2: return 7.5 * 60     // 7:30 AM (Morning / AM)
    case 3: return 8 * 60       // 8:00 AM (Morning Supplements)
    case 4: return 8.5 * 60     // 8:30 AM (First Meal)
    case 5: return 12 * 60      // 12:00 PM (Midday)
    case 6: return 12.5 * 60    // 12:30 PM (Midday Stack)
    case 7: return 15 * 60      // 3:00 PM (Afternoon / Workout / Inversion)
    case 8: return 17 * 60      // 5:00 PM (Late Afternoon)
    case 9: return 17.5 * 60    // 5:30 PM (Pre-Meal)
    case 10: return 18.5 * 60   // 6:30 PM (Post-Meal)
    case 11: return 19 * 60     // 7:00 PM (Evening / Dinner)
    case 12: return 20 * 60     // 8:00 PM (Evening Supplements)
    case 13: return 21 * 60     // 9:00 PM (Wind Down)
    case 14: return 21.5 * 60   // 9:30 PM (Pre-Bed)
    case 15: return 22.5 * 60   // 10:30 PM (Bedtime / Sleep)
    case 99: return 9.5 * 60    // 9:30 AM (Anytime - placed mid-morning after am routines)
    default: return 10 * 60     // 10:00 AM (Default baseline)
  }
}

/**
 * Standardized chronological task sorter.
 * Ensures modalities across 3-day split, 7-day week, and monthly calendar views
 * appear in the EXACT same chronological circadian order as the user's Today feed.
 */
export function sortTasksChronologically(
  tasks: DailyProtocolTask[],
  userProfile?: UserProfile | null
): DailyProtocolTask[] {
  return [...tasks].sort((a, b) => {
    const weightA = getTaskChronologicalWeight(a, userProfile)
    const weightB = getTaskChronologicalWeight(b, userProfile)
    if (weightA !== weightB) {
      return weightA - weightB
    }

    const orderA = a.protocol_step?.display_order || 0
    const orderB = b.protocol_step?.display_order || 0
    if (orderA !== orderB) {
      return orderA - orderB
    }

    const modA = a.protocol_step?.modality || a.loose_modality
    const modB = b.protocol_step?.modality || b.loose_modality
    const nameA = modA?.name || a.protocol_step?.protocol?.name || (a as any).title || ''
    const nameB = modB?.name || b.protocol_step?.protocol?.name || (b as any).title || ''
    return nameA.localeCompare(nameB)
  })
}

