import { Modality, ProtocolStep, UserProfile } from '../types'

/**
 * Smart Modality Timing Resolver Engine
 * Guarantees that all current and future modalities automatically map to their optimal 
 * timing block (morning, afternoon, evening, bedtime, etc.) instead of defaulting to 'anytime'.
 */

export type OptimalTimingSlot = 
  | 'morning'
  | 'morning_supplement_stack'
  | 'midday'
  | 'midday_stack'
  | 'afternoon'
  | 'late_afternoon'
  | 'post_meal'
  | 'evening'
  | 'evening_supplement_stack'
  | 'wind_down'
  | 'bedtime'
  | 'pre_bed'
  | 'anytime'

export interface MultiDoseSlot {
  doseNumber: number
  totalDoses: number
  label: string
  slot: string
}

/**
 * Resolves a canonical timing slot from any natural text or preset string (e.g. from Dosage/Manage modals).
 */
export function resolveSlotFromTimingString(timingStr?: string, isSupplement: boolean = false): string {
  if (!timingStr || !timingStr.trim()) return 'anytime'
  const lower = timingStr.toLowerCase()

  // Clean away weekly frequency prefixes like "3–4x per week • "
  const clean = lower.includes('•') ? lower.split('•').slice(1).join('•').trim() : lower

  // Bedtime / Pre-bed / Night
  if (
    clean.includes('bed') || clean.includes('night') || clean.includes('sleep') || 
    clean.includes('9:00 pm') || clean.includes('10:00 pm') || clean.includes('11:00 pm') ||
    clean.includes('pre_bed') || clean.includes('pre-bed')
  ) {
    return 'bedtime'
  }

  // Wind down / evening cutoffs
  if (
    clean.includes('wind down') || clean.includes('wind_down') || clean.includes('screen cutoff') ||
    clean.includes('digital sunset') || clean.includes('caffeine cutoff')
  ) {
    return 'wind_down'
  }

  // Post-meal
  if (clean.includes('post-meal') || clean.includes('post meal') || clean.includes('postprandial') || clean.includes('after eating')) {
    return 'post_meal'
  }

  // Evening / Dinner
  if (clean.includes('evening') || clean.includes('dinner') || clean.includes('6:00 pm') || clean.includes('7:00 pm') || clean.includes('8:00 pm')) {
    return isSupplement ? 'evening_supplement_stack' : 'evening'
  }

  // Late afternoon / Afternoon / Workout
  if (clean.includes('afternoon') || clean.includes('4:00 pm') || clean.includes('5:00 pm') || clean.includes('late afternoon') || clean.includes('2:00 pm – 4:00 pm')) {
    return 'afternoon'
  }

  // Midday / Lunch / Noon
  if (clean.includes('mid-day') || clean.includes('midday') || clean.includes('lunch') || clean.includes('12:00 pm') || clean.includes('1:00 pm') || clean.includes('noon')) {
    return isSupplement ? 'midday_stack' : 'midday'
  }

  // Morning / Breakfast / Waking / Fasted AM
  if (
    clean.includes('waking') || clean.includes('wake') || clean.includes('morning') || 
    clean.includes('breakfast') || clean.includes('6:00 am') || clean.includes('7:00 am') || 
    clean.includes('8:00 am') || clean.includes('9:00 am') || clean.includes('10:00 am') ||
    clean.includes('fasted am') || clean.includes('upon waking')
  ) {
    return isSupplement ? 'morning_supplement_stack' : 'morning'
  }

  return 'anytime'
}

/**
 * Universal Multi-Dose Splitter Parser
 * Parses multi-dose timing strings generated by DosageDetailModal, ManageTaskModal, or protocol steps
 * (e.g. "2x Daily: Dose 1 (Morning...) + Dose 2 (Pre-Bed...)" or "3x/wk • Morning & Evening")
 */
export function parseMultiDoseTimingSlots(timingStr?: string, isSupplement: boolean = false): MultiDoseSlot[] {
  if (!timingStr) return []
  const raw = timingStr.trim()
  const lower = raw.toLowerCase()

  // 1. Check for standard 2x / 3x daily modal serialized formats:
  // "2x Daily: Dose 1 (Morning / With Breakfast (8:00 AM – 10:00 AM)) + Dose 2 (Pre-Bed / Night (9:00 PM – 11:00 PM))"
  // "3x Daily: Dose 1 (...) + Dose 2 (...) + Dose 3 (...)"
  if (raw.includes('+ Dose 2') || raw.includes('Dose 1') && raw.includes('+') || (raw.includes('2x Daily:') || raw.includes('3x Daily:')) && raw.includes('+')) {
    const parts = raw.split(/\s*\+\s*/)
    const cleanPart = (str?: string) => {
      if (!str) return ''
      return str
        .replace(/^[23]x\s*(?:daily|per week)?:\s*/i, '')
        .replace(/^Dose \d+\s*\(/i, '')
        .replace(/\)$/, '')
        .trim()
    }

    const slots: MultiDoseSlot[] = []
    const totalDoses = parts.length

    parts.forEach((p, idx) => {
      const doseNum = idx + 1
      const cleaned = cleanPart(p)
      const slot = resolveSlotFromTimingString(cleaned, isSupplement)
      const defaultLabels = ['Morning', 'Midday / PM', 'Evening / Night']
      const labelShort = cleaned.split('/')[0].split('(')[0].trim() || defaultLabels[idx] || `Dose ${doseNum}`
      
      slots.push({
        doseNumber: doseNum,
        totalDoses: totalDoses,
        label: `Dose ${doseNum} (${labelShort})`,
        slot: slot === 'anytime' ? (doseNum === 1 ? 'morning' : doseNum === 2 ? 'evening' : 'bedtime') : slot
      })
    })

    if (slots.length >= 2) return slots
  }

  // 2. Format: "Morning & Evening" or "Morning & Midday" or "Morning, Midday & Evening"
  if (lower.includes('morning & midday') || lower.includes('morning and midday')) {
    return [
      { doseNumber: 1, totalDoses: 2, label: 'Dose 1 (Morning)', slot: isSupplement ? 'morning_supplement_stack' : 'morning' },
      { doseNumber: 2, totalDoses: 2, label: 'Dose 2 (Midday)', slot: isSupplement ? 'midday_stack' : 'midday' }
    ]
  }

  if (lower.includes('morning & evening') || lower.includes('morning and evening') || lower.includes('split am / pm') || lower.includes('split am/pm') || lower.includes('2x/day') || lower.includes('2x daily') || lower.includes('2x_day') || lower.includes('bid')) {
    return [
      { doseNumber: 1, totalDoses: 2, label: 'Dose 1 (Morning)', slot: isSupplement ? 'morning_supplement_stack' : 'morning' },
      { doseNumber: 2, totalDoses: 2, label: 'Dose 2 (Evening)', slot: isSupplement ? 'evening_supplement_stack' : 'evening' }
    ]
  }

  if (lower.includes('3x/day') || lower.includes('3x daily') || lower.includes('3x_day') || lower.includes('tid')) {
    return [
      { doseNumber: 1, totalDoses: 3, label: 'Dose 1 (Morning)', slot: isSupplement ? 'morning_supplement_stack' : 'morning' },
      { doseNumber: 2, totalDoses: 3, label: 'Dose 2 (Midday)', slot: isSupplement ? 'midday_stack' : 'midday' },
      { doseNumber: 3, totalDoses: 3, label: 'Dose 3 (Evening)', slot: isSupplement ? 'evening_supplement_stack' : 'evening' }
    ]
  }

  return []
}

export function resolveOptimalTimingSlot(
  modality?: Modality | null,
  step?: ProtocolStep | null,
  fallbackSlot: string = 'anytime',
  userProfile?: UserProfile | null,
  customTiming?: string | null
): string {
  const isSupplement = (modality?.category || '').toLowerCase().includes('supplement') || 
                       (modality?.modality_type || '').toLowerCase() === 'supplement'

  // 0. If user has an explicit custom timing string override (from execution_details or bench item), resolve from it!
  if (customTiming && customTiming.trim()) {
    const fromCustom = resolveSlotFromTimingString(customTiming, isSupplement)
    if (fromCustom && fromCustom !== 'anytime') {
      return normalizeSlot(fromCustom)
    }
  }

  // 1. If user has explicit primary workout window preference in profile, apply to workouts
  if (modality && userProfile?.primary_workout_window) {
    const text = `${modality.name || ''} ${modality.category || ''} ${modality.timing_summary || ''}`.toLowerCase()
    const isWorkout = 
      text.includes('resistance training') || 
      text.includes('strength') || 
      text.includes('hypertrophy') || 
      text.includes('decathlon') ||
      text.includes('vo2 max') ||
      text.includes('sprint')
    
    if (isWorkout) {
      const window = userProfile.primary_workout_window.toLowerCase()
      if (window.includes('morning')) return 'morning'
      if (window.includes('midday')) return 'midday'
      if (window.includes('afternoon')) return 'afternoon'
      if (window.includes('evening')) return 'evening'
    }
  }

  // 2. Explicit task timing slot if non-empty and not 'anytime'
  if (fallbackSlot && fallbackSlot !== 'anytime') {
    return normalizeSlot(fallbackSlot)
  }

  // 3. Explicit protocol step timing slot if non-empty and not 'anytime'
  if (step?.timing_slot && step.timing_slot !== 'anytime') {
    return normalizeSlot(step.timing_slot)
  }

  // 4. Explicit modality default timing slot if non-empty and not 'anytime'
  if (modality?.default_timing_slot && modality.default_timing_slot !== 'anytime') {
    return normalizeSlot(modality.default_timing_slot)
  }

  // 5. Comprehensive Keyword & Semantic Resolver
  if (modality) {
    const timing = (modality.timing_summary || '').toLowerCase()
    const name = (modality.name || '').toLowerCase()
    const cat = (modality.category || '').toLowerCase()
    const inst = (modality.instructions || '').toLowerCase()
    const text = `${timing} ${name} ${cat} ${inst}`.toLowerCase()

    // Bedtime / Sleep / Overnight / Dental Nightly
    if (
      timing.includes('bed') || timing.includes('nightly') || timing.includes('pre-bed') || 
      timing.includes('overnight') || timing.includes('before bed') || timing.includes('sleep environment') ||
      name.includes('flossing') || name.includes('mouth tap') || name.includes('sleep environment') ||
      text.includes('30m before bed') || text.includes('before sleep') || text.includes('sleep architecture') ||
      name.includes('sleep consistency')
    ) {
      return 'bedtime'
    }

    // Wind Down / Evening Cutoffs
    if (
      timing.includes('wind down') || timing.includes('wind_down') || text.includes('4-7-8') || 
      name.includes('screen time reduction') || timing.includes('screen') || timing.includes('cutoff') ||
      text.includes('caffeine cutoff') || text.includes('alcohol sleep-protection') ||
      name.includes('blue-light') || timing.includes('dimming')
    ) {
      return 'wind_down'
    }

    // Evening / Dinner / Sauna
    if (
      timing.includes('evening') || timing.includes('dinner') || timing.includes('night') || 
      timing.includes('dusk') || name.includes('sauna') || timing.includes('sauna') ||
      text.includes('with dinner') || text.includes('evening with') || text.includes('dinner / daily') ||
      text.includes('dinner with food') || text.includes('dinner / evening')
    ) {
      return isSupplement ? 'evening_supplement_stack' : 'evening'
    }

    // Post-Meal / Glycemic walk
    if (
      timing.includes('post-meal') || timing.includes('post meal') || timing.includes('postprandial') ||
      name.includes('postprandial') || text.includes('after eating') || text.includes('after major meals') ||
      (name.includes('soleus') && text.includes('post-meal')) || (name.includes('walk') && text.includes('post-meal'))
    ) {
      return 'post_meal'
    }

    // Afternoon / Late Afternoon / Strength / Workouts
    if (
      timing.includes('afternoon') || timing.includes('2-6 pm') || timing.includes('peak body temp') ||
      timing.includes('4:00 pm') || text.includes('resistance training') || text.includes('hypertrophy') ||
      text.includes('strength training') || text.includes('coherent') || text.includes('resonant') ||
      text.includes('vo2 max') || text.includes('sprints')
    ) {
      return 'afternoon'
    }

    // Midday / Lunch / Desk micro-movement
    if (
      timing.includes('midday') || timing.includes('lunch') || timing.includes('noon') || 
      timing.includes('11:00 am') || timing.includes('12:00 pm') || timing.includes('1:00 pm') ||
      timing.includes('desk micro-movement') || name.includes('nut pudding') || text.includes('box breath')
    ) {
      return isSupplement ? 'midday_stack' : 'midday'
    }

    // Morning / Waking / Breakfast / Morning Supplements / Light / Cold
    if (
      timing.includes('morning') || timing.includes('wake') || timing.includes('waking') ||
      timing.includes('am') || timing.includes('fasted') || timing.includes('breakfast') ||
      name.includes('light') || name.includes('sunlight') || name.includes('cold') || 
      name.includes('coffee') || name.includes('caffeine') || name.includes('sigh') ||
      name.includes('super veggie') || text.includes('morning meal') || text.includes('upon waking') ||
      name.includes('red light') || name.includes('photobiomodulation')
    ) {
      return isSupplement ? 'morning_supplement_stack' : 'morning'
    }
  }

  return 'anytime'
}

function normalizeSlot(slot: string): string {
  const s = slot.toLowerCase().trim()
  if (s.includes('wind_down') || s.includes('winddown')) return 'wind_down'
  if (s.includes('bed') || s.includes('sleep') || s.includes('nightly') || s.includes('pre_bed') || s.includes('pre-bed')) return 'bedtime'
  if (s.includes('evening_supplement') || s.includes('dinner_stack')) return 'evening_supplement_stack'
  if (s.includes('evening') || s.includes('dinner')) return 'evening'
  if (s.includes('post_meal') || s.includes('post-meal') || s.includes('post meal') || s.includes('postprandial')) return 'post_meal'
  if (s.includes('morning_supplement')) return 'morning_supplement_stack'
  if (s.includes('morning') || s.includes('wake') || s.includes('waking')) return 'morning'
  if (s.includes('midday_stack') || s.includes('lunch_stack')) return 'midday_stack'
  if (s.includes('midday') || s.includes('lunch') || s.includes('noon')) return 'midday'
  if (s.includes('afternoon') || s.includes('workout')) return 'afternoon'
  return s
}
