UPDATE modalities SET effort_level = 'level_4', cost_tier = 'low', hallmarks_of_aging_impact = '["Epigenetic Alterations","Deregulated Nutrient Sensing","Stem Cell Exhaustion"]'::jsonb WHERE id = 'bfr_training';
UPDATE modalities SET effort_level = 'level_4', cost_tier = 'high', hallmarks_of_aging_impact = '["Epigenetic Alterations","Deregulated Nutrient Sensing","Chronic Inflammation"]'::jsonb WHERE id = 'continuous_glucose_monitor';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Cellular Senescence","Epigenetic Alterations"]'::jsonb WHERE id = 'apigenin';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Cellular Senescence","Epigenetic Alterations","Chronic Inflammation"]'::jsonb WHERE id = 'walker_sleep_triad_supplement';
UPDATE modalities SET effort_level = 'level_3', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Chronic Inflammation"]'::jsonb WHERE id = 'red_light_photobiomodulation_therapy';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Epigenetic Alterations"]'::jsonb WHERE id = 'tibialis_raises';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing","Chronic Inflammation","Telomere Attrition"]'::jsonb WHERE id = 'sports-nutrition';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Epigenetic Alterations","Dysbiosis"]'::jsonb WHERE id = 'slant_board_squats';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Chronic Inflammation"]'::jsonb WHERE id = 'lions_mane';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'free', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = '6f188626-3382-4cb1-ab77-5af3ba44bd49';
UPDATE modalities SET effort_level = 'level_2', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'mindfulness-meditation';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'whole_body_mri';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Epigenetic Alterations"]'::jsonb WHERE id = 'nordic_hamstring_curls';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'l_theanine';
UPDATE modalities SET effort_level = 'level_3', cost_tier = 'low', hallmarks_of_aging_impact = '["Epigenetic Alterations"]'::jsonb WHERE id = 'thoracic_spine_extension_rotation';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Epigenetic Alterations"]'::jsonb WHERE id = 'poliquin_step_ups';
UPDATE modalities SET effort_level = 'level_5', cost_tier = 'free', hallmarks_of_aging_impact = '["Cellular Senescence","Epigenetic Alterations","Loss of Proteostasis"]'::jsonb WHERE id = 'longo_5day_fasting_mimicking_diet';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'cac-calcium-scan';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Chronic Inflammation"]'::jsonb WHERE id = 'sinclair_nmn_tmg';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Chronic Inflammation"]'::jsonb WHERE id = 'apob-lipid-panel';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Loss of Proteostasis","Chronic Inflammation","Stem Cell Exhaustion"]'::jsonb WHERE id = 'ashwagandha_ksm_66';
UPDATE modalities SET effort_level = 'level_2', cost_tier = 'free', hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'box_breathing';
UPDATE modalities SET effort_level = 'level_3', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations"]'::jsonb WHERE id = 'vo2-max-cpet-assessment';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Stem Cell Exhaustion"]'::jsonb WHERE id = 'mental-fortitude-training';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'magnesium_threonate';
UPDATE modalities SET effort_level = 'level_2', cost_tier = 'free', hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'cyclic_sighing';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Deregulated Nutrient Sensing","Chronic Inflammation"]'::jsonb WHERE id = 'abpm-24h-blood-pressure-monitor';
UPDATE modalities SET effort_level = 'level_5', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction"]'::jsonb WHERE id = 'blood_donation_phlebotomy';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'heavy-metals-environmental-toxin-panel';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'free', hallmarks_of_aging_impact = '["Epigenetic Alterations","Deregulated Nutrient Sensing","Chronic Inflammation"]'::jsonb WHERE id = 'walker_metabolic_alcohol_cutoff';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'high', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Loss of Proteostasis","Disabled Macroautophagy"]'::jsonb WHERE id = 'urolithin_a_mitophagy';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Epigenetic Alterations","Chronic Inflammation","Genomic Instability"]'::jsonb WHERE id = 'glycine_supplementation';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Chronic Inflammation"]'::jsonb WHERE id = 'brecka_pemf_grounding';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing","Chronic Inflammation","Dysbiosis"]'::jsonb WHERE id = 'recovery-techniques';
UPDATE modalities SET effort_level = 'level_5', cost_tier = 'low', hallmarks_of_aging_impact = '["Epigenetic Alterations"]'::jsonb WHERE id = 'grail-cancer-screen';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Cellular Senescence","Loss of Proteostasis","Chronic Inflammation"]'::jsonb WHERE id = 'lifespan_plus_deepcell';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'full-body-mri-scan';
UPDATE modalities SET effort_level = 'level_2', cost_tier = 'free', hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'breathing_4_7_8';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction"]'::jsonb WHERE id = 'low-dose-aspirin';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Chronic Inflammation"]'::jsonb WHERE id = 'rhonda_omega3_phospholipids';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Chronic Inflammation","Dysbiosis"]'::jsonb WHERE id = 'oral-microbiome-pathogen-screen';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Epigenetic Alterations","Dysbiosis"]'::jsonb WHERE id = 'sinclair_trans_resveratrol';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'premium', hallmarks_of_aging_impact = '["Cellular Senescence","Loss of Proteostasis","Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'longo_post_fmd_stem_cell_refeed';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Deregulated Nutrient Sensing","Chronic Inflammation"]'::jsonb WHERE id = 'glp_1_receptor_agonists';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Chronic Inflammation"]'::jsonb WHERE id = 'vilpa_micro_bursts';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'premium', hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'collagen_peptides';
UPDATE modalities SET effort_level = 'level_3', cost_tier = 'free', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Genomic Instability","Altered Intercellular Communication"]'::jsonb WHERE id = 'f0dba777-57ed-4070-8c2e-038e40a0cf6a';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'dexa-body-composition-scan';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Cellular Senescence","Chronic Inflammation","Dysbiosis"]'::jsonb WHERE id = 'curcumin';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'free', hallmarks_of_aging_impact = '["Epigenetic Alterations","Loss of Proteostasis","Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'monk_fast_36h';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Deregulated Nutrient Sensing","Altered Intercellular Communication"]'::jsonb WHERE id = 'creatine_monohydrate';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Loss of Proteostasis"]'::jsonb WHERE id = 'sinclair_metformin_berberine';
UPDATE modalities SET effort_level = 'level_5', cost_tier = 'low', hallmarks_of_aging_impact = '["Epigenetic Alterations"]'::jsonb WHERE id = 'dunedinpace-epigenetic-clock';
UPDATE modalities SET effort_level = 'level_5', cost_tier = 'free', hallmarks_of_aging_impact = '["Epigenetic Alterations","Loss of Proteostasis","Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'extended_fast_48h';
UPDATE modalities SET effort_level = 'level_4', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Loss of Proteostasis","Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'soberg_reheating_principle';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Chronic Inflammation"]'::jsonb WHERE id = 'nmn';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction"]'::jsonb WHERE id = 'coq10';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'free', hallmarks_of_aging_impact = '["Epigenetic Alterations","Loss of Proteostasis","Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'bone_broth_fast';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'free', hallmarks_of_aging_impact = '["Epigenetic Alterations","Loss of Proteostasis","Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'fat_fasting';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Telomere Attrition"]'::jsonb WHERE id = 'l_carnosine';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Cellular Senescence","Chronic Inflammation"]'::jsonb WHERE id = 'fisetin_quercetin_senolytic_pulse';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'free', hallmarks_of_aging_impact = '["Genomic Instability","Altered Intercellular Communication"]'::jsonb WHERE id = 'walker_melatonin_dimming';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Chronic Inflammation"]'::jsonb WHERE id = 'dayspring_isometric_handgrip_protocol';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction"]'::jsonb WHERE id = 'aged-garlic-extract';
UPDATE modalities SET effort_level = 'level_3', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations"]'::jsonb WHERE id = 'brecka_ewot_exercise_oxygen';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Dysbiosis"]'::jsonb WHERE id = 'hyaluronic_acid_oral';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Chronic Inflammation"]'::jsonb WHERE id = 'nad_precursors';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'genistein';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'rhodiola_rosea';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Chronic Inflammation"]'::jsonb WHERE id = 'taurine';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction"]'::jsonb WHERE id = 'vitamin_k2_mk7';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing","Dysbiosis"]'::jsonb WHERE id = 'means_macro_sequencing';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'free', hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'walker_65f_thermal_drop';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'bacopa_monnieri';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'l-lysine';
UPDATE modalities SET effort_level = 'level_3', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Loss of Proteostasis"]'::jsonb WHERE id = 'rhonda_hyperthermic_sauna';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Cellular Senescence","Epigenetic Alterations"]'::jsonb WHERE id = 'gaba';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations"]'::jsonb WHERE id = 'methylene_blue';
UPDATE modalities SET effort_level = 'level_3', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction"]'::jsonb WHERE id = 'hm_zone2_run';
UPDATE modalities SET effort_level = 'level_5', cost_tier = 'free', hallmarks_of_aging_impact = '["Cellular Senescence","Epigenetic Alterations","Loss of Proteostasis"]'::jsonb WHERE id = 'prolonged_autophagy_fast_72h';
UPDATE modalities SET effort_level = 'level_4', cost_tier = 'low', hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing","Stem Cell Exhaustion"]'::jsonb WHERE id = 'resistance_training';
UPDATE modalities SET effort_level = 'level_4', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction"]'::jsonb WHERE id = 'hm_threshold_intervals';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'hm_runner_stability';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction"]'::jsonb WHERE id = 'hm_progressive_longrun';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Chronic Inflammation"]'::jsonb WHERE id = 'magnesium_glycinate';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'free', hallmarks_of_aging_impact = '["Chronic Inflammation","Genomic Instability","Altered Intercellular Communication"]'::jsonb WHERE id = 'blue_light_blocking';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = '42cd4dd2-312d-49bc-a843-5c34e510178c';
UPDATE modalities SET effort_level = 'level_4', cost_tier = 'low', hallmarks_of_aging_impact = '["Stem Cell Exhaustion"]'::jsonb WHERE id = 'ppl_push_day';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'ppl_pull_day';
UPDATE modalities SET effort_level = 'level_4', cost_tier = 'low', hallmarks_of_aging_impact = '["Stem Cell Exhaustion"]'::jsonb WHERE id = 'ppl_leg_day';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Genomic Instability","Altered Intercellular Communication"]'::jsonb WHERE id = 'melatonin';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'ppl_recovery_day';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Epigenetic Alterations","Chronic Inflammation","Genomic Instability"]'::jsonb WHERE id = 'glycine_3g';
UPDATE modalities SET effort_level = 'level_5', cost_tier = 'premium', hallmarks_of_aging_impact = '["Stem Cell Exhaustion","Dysbiosis"]'::jsonb WHERE id = 'bpc157_subq';
UPDATE modalities SET effort_level = 'level_5', cost_tier = 'premium', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'tb500_subq';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Chronic Inflammation"]'::jsonb WHERE id = 'kpv_subq';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Loss of Proteostasis"]'::jsonb WHERE id = 'spermidine_supplement';
UPDATE modalities SET effort_level = 'level_4', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'rhonda_hiit_sprints';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Chronic Inflammation"]'::jsonb WHERE id = 'tudca';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Chronic Inflammation"]'::jsonb WHERE id = 'tirzepatide_subq';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'free', hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'aod9604_subq';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'cjc1295_no_dac_subq';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'ipamorelin_subq';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Epigenetic Alterations"]'::jsonb WHERE id = 'biological_age_testing';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Telomere Attrition"]'::jsonb WHERE id = 'l_citrulline';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'time-blocking';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Chronic Inflammation"]'::jsonb WHERE id = '3005e947-07b3-4d85-9469-094857f39d5f';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing","Chronic Inflammation"]'::jsonb WHERE id = 'means_acetic_acid_premeal';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Genomic Instability","Altered Intercellular Communication"]'::jsonb WHERE id = 'blueprint_sleep_architecture';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Chronic Inflammation"]'::jsonb WHERE id = 'vitamin-k1';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Loss of Proteostasis","Disabled Macroautophagy"]'::jsonb WHERE id = 'lithium_orotate';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'attia_protein_distribution';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'acarbose';
UPDATE modalities SET effort_level = 'level_4', cost_tier = 'free', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Deregulated Nutrient Sensing","Chronic Inflammation"]'::jsonb WHERE id = 'wim_hof_cold_shock_immersion';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'premium', hallmarks_of_aging_impact = '["Chronic Inflammation"]'::jsonb WHERE id = 'plasmapheresis_therapeutic_plasma_exchange';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Cellular Senescence","Chronic Inflammation"]'::jsonb WHERE id = 'longo_fisetin_quercetin_senolytic_pulse';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'free', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'post_meal_glucose_walk';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'free', hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'walker_caffeine_cutoff';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction"]'::jsonb WHERE id = 'astaxanthin';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Chronic Inflammation","Dysbiosis"]'::jsonb WHERE id = 'dayspring_viscous_fiber_phytosterols';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Cellular Senescence"]'::jsonb WHERE id = 'fisetin';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Chronic Inflammation"]'::jsonb WHERE id = '4ab59fd5-aabc-42e6-ac08-8d0efd7bb2a6';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Chronic Inflammation","Genomic Instability","Dysbiosis"]'::jsonb WHERE id = 'blueprint_super_veggie';
UPDATE modalities SET effort_level = 'level_3', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Telomere Attrition"]'::jsonb WHERE id = 'zone_2_cardio';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'attia_apob_lipid_management';
UPDATE modalities SET effort_level = 'level_3', cost_tier = 'free', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Cellular Senescence","Epigenetic Alterations"]'::jsonb WHERE id = 'intermittent_fasting_18_6';
UPDATE modalities SET effort_level = 'level_4', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Stem Cell Exhaustion"]'::jsonb WHERE id = 'vo2_max_4x4_hiit';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'free', hallmarks_of_aging_impact = '["Chronic Inflammation","Genomic Instability","Altered Intercellular Communication"]'::jsonb WHERE id = 'dark-cool-sleep-environment';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Chronic Inflammation","Genomic Instability","Altered Intercellular Communication"]'::jsonb WHERE id = 'evening-screen-time-reduction';
UPDATE modalities SET effort_level = 'level_5', cost_tier = 'premium', hallmarks_of_aging_impact = '["Chronic Inflammation","Stem Cell Exhaustion"]'::jsonb WHERE id = 'hyperbaric_oxygen_therapy_hbot';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'free', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Chronic Inflammation"]'::jsonb WHERE id = 'wim_hof_cyclic_retention_breathwork';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Loss of Proteostasis"]'::jsonb WHERE id = 'lifespan_plus_activate';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Loss of Proteostasis","Deregulated Nutrient Sensing","Disabled Macroautophagy"]'::jsonb WHERE id = 'glucosamine-sulfate';
UPDATE modalities SET effort_level = 'level_4', cost_tier = 'free', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Deregulated Nutrient Sensing","Chronic Inflammation"]'::jsonb WHERE id = 'cold_water_immersion';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Chronic Inflammation","Genomic Instability","Altered Intercellular Communication"]'::jsonb WHERE id = 'sleep_consistency';
UPDATE modalities SET effort_level = 'level_3', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations"]'::jsonb WHERE id = 'running';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing","Altered Intercellular Communication"]'::jsonb WHERE id = 'myo_inositol';
UPDATE modalities SET effort_level = 'level_3', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Loss of Proteostasis"]'::jsonb WHERE id = 'sauna_exposure';
UPDATE modalities SET effort_level = 'level_3', cost_tier = 'low', hallmarks_of_aging_impact = '["Epigenetic Alterations"]'::jsonb WHERE id = 'handstand';
UPDATE modalities SET effort_level = 'level_4', cost_tier = 'low', hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing","Telomere Attrition","Dysbiosis"]'::jsonb WHERE id = 'strength-training';
UPDATE modalities SET effort_level = 'level_2', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Chronic Inflammation"]'::jsonb WHERE id = 'glynac_glutathione_pulse';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'alpha_gpc';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Dysbiosis"]'::jsonb WHERE id = 'ndga';
UPDATE modalities SET effort_level = 'level_5', cost_tier = 'free', hallmarks_of_aging_impact = '["Epigenetic Alterations","Loss of Proteostasis","Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'water_fast_24h';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Chronic Inflammation"]'::jsonb WHERE id = 'nad_iv_therapy';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'delay_caffeine';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'vitamin-c';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'free', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'coherent_breathing';
UPDATE modalities SET effort_level = 'level_3', cost_tier = 'free', hallmarks_of_aging_impact = '["Epigenetic Alterations","Loss of Proteostasis","Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'intermittent_fasting_20_4';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'phosphatidylserine';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Cellular Senescence","Chronic Inflammation","Stem Cell Exhaustion"]'::jsonb WHERE id = 'quercetin';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'l_tyrosine';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'ghk_cu_subq';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'optic_flow';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'wim_hof_horse_stance_thermogenesis';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'free', hallmarks_of_aging_impact = '["Genomic Instability","Altered Intercellular Communication"]'::jsonb WHERE id = 'morning-sunlight-exposure';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'dexa_scan';
UPDATE modalities SET effort_level = 'level_5', cost_tier = 'high', hallmarks_of_aging_impact = '["Epigenetic Alterations","Loss of Proteostasis","Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'rapamycin_weekly';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'iodine';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Chronic Inflammation","Altered Intercellular Communication"]'::jsonb WHERE id = 'rhonda_vitamin_d3_k2';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Loss of Proteostasis"]'::jsonb WHERE id = 'metformin_daily';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'free', hallmarks_of_aging_impact = '["Genomic Instability","Altered Intercellular Communication"]'::jsonb WHERE id = 'morning_sunlight';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'high', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Disabled Macroautophagy","Telomere Attrition"]'::jsonb WHERE id = 'urolithin_a';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Chronic Inflammation"]'::jsonb WHERE id = 'cyclic_hyperventilation';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'heme-iron';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Deregulated Nutrient Sensing","Chronic Inflammation"]'::jsonb WHERE id = 'attia_centenarian_strength';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Epigenetic Alterations","Stem Cell Exhaustion"]'::jsonb WHERE id = 'alpha_ketoglutarate_akg';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'free', hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'means_soleus_pushups_postmeal_walk';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'vitamin-e';
UPDATE modalities SET effort_level = 'level_3', cost_tier = 'low', hallmarks_of_aging_impact = '["Epigenetic Alterations"]'::jsonb WHERE id = 'blueprint_60m_exercise_routine';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'tongkat_ali';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'continuous_ketone_monitors';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'n_acetyl_cysteine_nac';
UPDATE modalities SET effort_level = 'level_4', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'vo2_max_hiit_training';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing","Chronic Inflammation"]'::jsonb WHERE id = 'ginger-root';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Chronic Inflammation","Genomic Instability"]'::jsonb WHERE id = 'sulforaphane';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Loss of Proteostasis"]'::jsonb WHERE id = 'berberine';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Stem Cell Exhaustion"]'::jsonb WHERE id = 'mouth_taping';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'cocoa-flavanols';
UPDATE modalities SET effort_level = 'level_3', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction"]'::jsonb WHERE id = 'dayspring_inorganic_nitrate_citrulline';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Epigenetic Alterations","Telomere Attrition","Dysbiosis"]'::jsonb WHERE id = 'resveratrol_pterostilbene';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Epigenetic Alterations","Chronic Inflammation","Genomic Instability"]'::jsonb WHERE id = 'zinc';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Cellular Senescence","Epigenetic Alterations","Loss of Proteostasis"]'::jsonb WHERE id = 'extra-virgin-olive-oil';
UPDATE modalities SET effort_level = 'level_2', cost_tier = 'free', hallmarks_of_aging_impact = '["Epigenetic Alterations","Loss of Proteostasis","Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'intermittent_fasting_16_8';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Chronic Inflammation"]'::jsonb WHERE id = 'epa_dha_omega3';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'vitamin-k2-mk4';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Chronic Inflammation","Disabled Macroautophagy"]'::jsonb WHERE id = 'blueprint_nut_pudding';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Chronic Inflammation"]'::jsonb WHERE id = 'lycopene';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Loss of Proteostasis"]'::jsonb WHERE id = 'means_berberine_gda';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'vitamin_d3';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Epigenetic Alterations","Genomic Instability"]'::jsonb WHERE id = 'brecka_mthfr_methylation_support';
UPDATE modalities SET effort_level = 'level_3', cost_tier = 'free', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Epigenetic Alterations","Loss of Proteostasis"]'::jsonb WHERE id = 'omad_fasting';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Loss of Proteostasis","Chronic Inflammation","Stem Cell Exhaustion"]'::jsonb WHERE id = 'ashwagandha_ksm66';
UPDATE modalities SET effort_level = 'level_3', cost_tier = 'moderate', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Chronic Inflammation","Altered Intercellular Communication"]'::jsonb WHERE id = 'blueprint_red_light_therapy';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'free', hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing"]'::jsonb WHERE id = '3115a2bc-af3f-427f-bffa-473cb9173ab1';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'd546b638-20cc-4134-b79d-ff6d530c6761';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction","Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'alpha_lipoic_acid';
UPDATE modalities SET effort_level = 'level_1', cost_tier = 'low', hallmarks_of_aging_impact = '["Mitochondrial Dysfunction"]'::jsonb WHERE id = 'shilajit';