const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');

const envFile = fs.readFileSync('.env.local', 'utf8');
const envVars = {};
envFile.split('\n').forEach(line => {
  const [key, ...values] = line.split('=');
  if (key && values.length > 0) envVars[key.trim()] = values.join('=').trim();
});

const supabaseUrl = envVars['NEXT_PUBLIC_SUPABASE_URL'];
const supabaseKey = envVars['NEXT_PUBLIC_SUPABASE_ANON_KEY'];
const supabase = createClient(supabaseUrl, supabaseKey);

const newModalities = [
  {
    id: 'sulforaphane',
    slug: 'sulforaphane',
    name: 'Sulforaphane (Glucoraphanin + Active Myrosinase)',
    category: 'Supplements & Nutraceuticals',
    modality_type: 'supplement',
    logging_type: 'supplement',
    status: 'active',
    brief_description: 'Generic Nrf2 activator and Phase II detoxification enzyme inducer (generic alternative to BroccoMax).',
    expanded_why: 'Sulforaphane is an isothiocyanate derived from glucoraphanin via the myrosinase enzyme. It triggers Nrf2 pathway activation, driving endogenous production of glutathione, quinone reductase, and heme oxygenase-1 to clear cellular oxidants and toxins.',
    headline_benefit: 'Induces Nrf2 cellular defense & endogenous antioxidant enzymes',
    dose_or_exposure: '17.5 mg – 35 mg active Sulforaphane',
    timing_summary: 'Morning with light meal',
    frequency: 'Daily',
    cadence_layer: 'daily',
    difficulty: 'Very Easy',
    cost_tier: 'Low ($0.50/day)',
    effort_level: 'Minimal',
    time_to_benefit: '2-4 Weeks',
    evidence_quality: 9,
    effect_size_estimate: 'Moderate to Large',
    evidence_summary: 'Robust human and preclinical data showing Nrf2 activation, reduced inflammatory cytokines (IL-6, TNF-a), and enhanced detoxification.',
    safety_level: 'High',
    safety_summary: 'Extremely safe; mild GI distress at very high doses.',
    contraindications: ['Severe thyroid dysfunction without iodine monitoring'],
    primary_outcome: 'Cellular Detoxification & Anti-Inflammatory',
    secondary_outcomes: ['Liver Health', 'DNA Protection', 'Cardiovascular Function'],
    mechanism_of_action: 'Nrf2 nuclear translocation and Phase II cytoprotective gene expression',
    dose_details: {
      starter_dose: 10,
      personalized_target_dose: 17.5,
      blueprint_dose: 17.5,
      unit: 'mg',
      literature_range: { min: 10, max: 60, outlier_upper: 100 },
      starter_notes: 'Start with 10mg daily to verify GI comfort.',
      recommended_notes: '17.5mg active sulforaphane provides optimal Nrf2 induction.',
      blueprint_notes: 'Bryan Johnson 2026 Blueprint dose: 17.5 mg morning.'
    }
  },
  {
    id: 'vitamin-c',
    slug: 'vitamin-c',
    name: 'Vitamin C (Ascorbic Acid / Liposomal)',
    category: 'Supplements & Nutraceuticals',
    modality_type: 'supplement',
    logging_type: 'supplement',
    status: 'active',
    brief_description: 'Essential water-soluble antioxidant, endothelial nitric oxide cofactor, and collagen cross-linking promoter.',
    expanded_why: 'Vitamin C scavenges reactive oxygen species (ROS), regenerates oxidized Vitamin E, and acts as an essential cofactor for prolyl hydroxylase enzymes during collagen synthesis and vascular wall repair.',
    headline_benefit: 'Scavenges cellular oxidants & supports collagen cross-linking',
    dose_or_exposure: '500 mg – 1,000 mg',
    timing_summary: 'Morning',
    frequency: 'Daily',
    cadence_layer: 'daily',
    difficulty: 'Very Easy',
    cost_tier: 'Low ($0.15/day)',
    effort_level: 'Minimal',
    time_to_benefit: 'Immediate',
    evidence_quality: 10,
    effect_size_estimate: 'Moderate',
    evidence_summary: 'Extensively studied essential nutrient for immune defense, endothelial function, and collagen synthesis.',
    safety_level: 'Very High',
    safety_summary: 'Excess excreted in urine; gastrointestinal tolerance limit ~2,000 mg/day.',
    contraindications: ['History of oxalosis / kidney stones at high doses (>2g)'],
    primary_outcome: 'Antioxidant & Collagen Support',
    secondary_outcomes: ['Immune Function', 'Endothelial Health', 'Skin Elasticity'],
    mechanism_of_action: 'Direct ROS neutralization & prolyl hydroxylase enzymatic cofactor',
    dose_details: {
      starter_dose: 250,
      personalized_target_dose: 500,
      blueprint_dose: 500,
      unit: 'mg',
      literature_range: { min: 250, max: 2000, outlier_upper: 5000 },
      starter_notes: '250mg is gentle on the stomach for sensitive individuals.',
      recommended_notes: '500mg daily maintains peak plasma ascorbate saturation.',
      blueprint_notes: 'Bryan Johnson 2026 Blueprint dose: 500 mg morning.'
    }
  },
  {
    id: 'ginger-root',
    slug: 'ginger-root',
    name: 'Ginger Root Extract (Zingiber officinale)',
    category: 'Supplements & Nutraceuticals',
    modality_type: 'supplement',
    logging_type: 'supplement',
    status: 'active',
    brief_description: 'Potent gingerol-rich botanical extract for systemic anti-inflammation, gastric motility, and insulin sensitivity.',
    expanded_why: 'Gingerols and shogaols inhibit cyclooxygenase (COX-2) and 5-lipoxygenase pathways, accelerating gastric emptying and lowering postprandial blood glucose spikes.',
    headline_benefit: 'Soothes GI tract & reduces inflammatory pro-prostaglandins',
    dose_or_exposure: '1,000 mg – 2,200 mg',
    timing_summary: 'Morning with food',
    frequency: 'Daily',
    cadence_layer: 'daily',
    difficulty: 'Very Easy',
    cost_tier: 'Low ($0.25/day)',
    effort_level: 'Minimal',
    time_to_benefit: '1-2 Weeks',
    evidence_quality: 9,
    effect_size_estimate: 'Moderate',
    evidence_summary: 'Multiple RCTs confirm reduced hs-CRP, improved fasting glucose, and enhanced gastric emptying.',
    safety_level: 'High',
    safety_summary: 'Well tolerated; take with food to prevent mild heartburn.',
    contraindications: ['Concurrent high-dose blood thinners (consult physician)'],
    primary_outcome: 'GI Motility & Anti-Inflammatory',
    secondary_outcomes: ['Glycemic Control', 'Joint Comfort', 'Metabolic Rate'],
    mechanism_of_action: 'COX-2/5-LOX inhibition and 5-HT3 receptor modulation',
    dose_details: {
      starter_dose: 500,
      personalized_target_dose: 1000,
      blueprint_dose: 2200,
      unit: 'mg',
      literature_range: { min: 500, max: 3000, outlier_upper: 4000 },
      starter_notes: '500mg with breakfast checks digestive comfort.',
      recommended_notes: '1,000mg daily delivers clinically validated anti-inflammatory benefits.',
      blueprint_notes: 'Bryan Johnson 2026 Blueprint dose: 2.2 g morning.'
    }
  },
  {
    id: 'aged-garlic-extract',
    slug: 'aged-garlic-extract',
    name: 'Aged Garlic Extract (Kyolic / S-Allyl-Cysteine)',
    category: 'Supplements & Nutraceuticals',
    modality_type: 'supplement',
    logging_type: 'supplement',
    status: 'active',
    brief_description: 'Cardioprotective garlic concentrate standardized for S-allyl-cysteine (SAC) to reduce arterial plaque progression.',
    expanded_why: 'Aged Garlic Extract (AGE) increases endothelial nitric oxide production, retards coronary artery calcification, and lowers systemic blood pressure through vascular smooth muscle relaxation.',
    headline_benefit: 'Inhibits arterial calcification & lowers central blood pressure',
    dose_or_exposure: '1,200 mg – 2,400 mg',
    timing_summary: 'Morning & Evening with meals',
    frequency: 'Daily',
    cadence_layer: 'daily',
    difficulty: 'Very Easy',
    cost_tier: 'Low ($0.40/day)',
    effort_level: 'Minimal',
    time_to_benefit: '4-8 Weeks',
    evidence_quality: 9,
    effect_size_estimate: 'Moderate to Large',
    evidence_summary: 'Clinical trial evidence shows significant reductions in low-attenuation soft coronary plaque and arterial stiffness.',
    safety_level: 'High',
    safety_summary: 'Odorless formulation; very high safety profile.',
    contraindications: ['Pre-surgery anti-platelet caution'],
    primary_outcome: 'Cardiovascular & Arterial Elasticity',
    secondary_outcomes: ['Immune Regulation', 'Blood Pressure Control', 'Lipid Protection'],
    mechanism_of_action: 'SAC-mediated endothelial nitric oxide release & hydrogen sulfide gasotransmission',
    dose_details: {
      starter_dose: 600,
      personalized_target_dose: 1200,
      blueprint_dose: 2400,
      unit: 'mg',
      literature_range: { min: 600, max: 2400, outlier_upper: 3600 },
      starter_notes: '600mg morning is a gentle entry dose.',
      recommended_notes: '1,200mg daily supports arterial elasticity and BP regulation.',
      blueprint_notes: 'Bryan Johnson 2026 Blueprint dose: 2.4 g total (1.2g AM / 1.2g PM).'
    }
  },
  {
    id: 'vitamin-k1',
    slug: 'vitamin-k1',
    name: 'Vitamin K1 (Phylloquinone)',
    category: 'Supplements & Nutraceuticals',
    modality_type: 'supplement',
    logging_type: 'supplement',
    status: 'active',
    brief_description: 'Essential dietary Vitamin K form regulating hepatic clotting cascades and microvascular integrity.',
    expanded_why: 'Phylloquinone acts as a cofactor for gamma-glutamyl carboxylase in the liver, converting glutamic acid residues to gamma-carboxyglutamate (Gla) on clotting factors II, VII, IX, and X.',
    headline_benefit: 'Ensures optimal coagulation cascade & microvascular stability',
    dose_or_exposure: '1,000 mcg – 1,500 mcg',
    timing_summary: 'Morning with healthy fats',
    frequency: 'Daily',
    cadence_layer: 'daily',
    difficulty: 'Very Easy',
    cost_tier: 'Low ($0.20/day)',
    effort_level: 'Minimal',
    time_to_benefit: '1-2 Weeks',
    evidence_quality: 9,
    effect_size_estimate: 'Moderate',
    evidence_summary: 'Well-established physiological role in hepatic coagulation factor carboxylation and bone mineralization.',
    safety_level: 'Very High',
    safety_summary: 'No established upper intake limit in healthy individuals.',
    contraindications: ['Warfarin / Coumadin anticoagulation therapy'],
    primary_outcome: 'Microvascular & Coagulation Homeostasis',
    secondary_outcomes: ['Bone Matrix Health', 'Vascular Protection'],
    mechanism_of_action: 'Gamma-glutamyl carboxylase co-factor',
    dose_details: {
      starter_dose: 500,
      personalized_target_dose: 1000,
      blueprint_dose: 1500,
      unit: 'mcg',
      literature_range: { min: 100, max: 2000, outlier_upper: 5000 },
      starter_notes: '500mcg covers dietary gaps for sensitive users.',
      recommended_notes: '1,000mcg ensures full carboxylation of hepatic coagulation factors.',
      blueprint_notes: 'Bryan Johnson 2026 Blueprint dose: 1.5 mg (1,500 mcg) morning.'
    }
  },
  {
    id: 'vitamin-k2-mk4',
    slug: 'vitamin-k2-mk4',
    name: 'Vitamin K2-MK4 (Menatetrenone)',
    category: 'Supplements & Nutraceuticals',
    modality_type: 'supplement',
    logging_type: 'supplement',
    status: 'active',
    brief_description: 'Tissue-specific Vitamin K2 isoform activating osteocalcin and preventing ectopic arterial calcification.',
    expanded_why: 'Menatetrenone (MK-4) carboxylates Matrix Gla Protein (MGP) in arterial walls, actively clearing calcium deposits out of soft arterial tissue and binding it into the bone hydroxyapatite matrix.',
    headline_benefit: 'Directs calcium out of arterial walls into bone matrix',
    dose_or_exposure: '1 mg – 5 mg',
    timing_summary: 'Morning with fat-containing meal',
    frequency: 'Daily',
    cadence_layer: 'daily',
    difficulty: 'Very Easy',
    cost_tier: 'Moderate ($0.60/day)',
    effort_level: 'Minimal',
    time_to_benefit: '4-12 Weeks',
    evidence_quality: 9,
    effect_size_estimate: 'Large',
    evidence_summary: 'Extensive clinical literature (including Japanese osteopenia trials) demonstrating MGP carboxylation and arterial calcification inhibition.',
    safety_level: 'High',
    safety_summary: 'Extremely safe even at high clinical doses (up to 45 mg in prescription trials).',
    contraindications: ['Warfarin / Coumadin therapy'],
    primary_outcome: 'Arterial Decalcification & Bone Mineralization',
    secondary_outcomes: ['Cardiovascular Protection', 'Dental Health'],
    mechanism_of_action: 'Matrix Gla Protein (MGP) and osteocalcin gamma-carboxylation',
    dose_details: {
      starter_dose: 1000,
      personalized_target_dose: 2500,
      blueprint_dose: 5000,
      unit: 'mcg',
      literature_range: { min: 1000, max: 15000, outlier_upper: 45000 },
      starter_notes: '1mg (1,000 mcg) provides foundational MGP activation.',
      recommended_notes: '2.5mg maintains robust arterial decalcification.',
      blueprint_notes: 'Bryan Johnson 2026 Blueprint dose: 5 mg morning.'
    }
  },
  {
    id: 'zinc',
    slug: 'zinc',
    name: 'Zinc Picolinate / Bisglycinate',
    category: 'Supplements & Nutraceuticals',
    modality_type: 'supplement',
    logging_type: 'supplement',
    status: 'active',
    brief_description: 'Essential trace mineral driving thymic function, immune cell proliferation, and genomic DNA repair.',
    expanded_why: 'Zinc acts as a catalytic cofactor for over 300 metalloenzymes and zinc-finger transcription factors, preserving telomere length, thymic hormone activity, and hormonal synthesis.',
    headline_benefit: 'Supports immune thymic involution defense & DNA repair enzymes',
    dose_or_exposure: '15 mg – 30 mg elemental Zinc',
    timing_summary: 'Morning with food',
    frequency: 'Daily',
    cadence_layer: 'daily',
    difficulty: 'Very Easy',
    cost_tier: 'Low ($0.10/day)',
    effort_level: 'Minimal',
    time_to_benefit: '1-2 Weeks',
    evidence_quality: 10,
    effect_size_estimate: 'Moderate',
    evidence_summary: 'Comprehensive trial literature establishing essential role in cell-mediated immunity and testosterone synthesis.',
    safety_level: 'High',
    safety_summary: 'Keep under 40 mg daily to prevent copper depletion.',
    contraindications: ['High-dose copper deficiency without copper supplementation'],
    primary_outcome: 'Immune Resilience & DNA Integrity',
    secondary_outcomes: ['Hormone Production', 'Wound Healing', 'Skin Barrier'],
    mechanism_of_action: 'Metalloenzyme catalysis & zinc-finger DNA binding domain stabilization',
    dose_details: {
      starter_dose: 10,
      personalized_target_dose: 15,
      blueprint_dose: 15,
      unit: 'mg',
      literature_range: { min: 10, max: 30, outlier_upper: 50 },
      starter_notes: '10mg with food avoids any mild nausea.',
      recommended_notes: '15mg elemental zinc maintains optimal thymic immunity.',
      blueprint_notes: 'Bryan Johnson 2026 Blueprint dose: 15 mg morning.'
    }
  },
  {
    id: 'iodine',
    slug: 'iodine',
    name: 'Iodine (as Potassium Iodide)',
    category: 'Supplements & Nutraceuticals',
    modality_type: 'supplement',
    logging_type: 'supplement',
    status: 'active',
    brief_description: 'Essential trace element required for thyroid hormone (T3 and T4) biosynthesis and basal metabolic rate.',
    expanded_why: 'Potassium iodide provides elemental iodine for thyroid peroxidase (TPO) organification into thyroglobulin, maintaining systemic metabolic homeostatic rate.',
    headline_benefit: 'Fuel for thyroid hormone synthesis & metabolic rate balance',
    dose_or_exposure: '125 mcg – 150 mcg',
    timing_summary: 'Morning',
    frequency: 'Daily',
    cadence_layer: 'daily',
    difficulty: 'Very Easy',
    cost_tier: 'Low ($0.05/day)',
    effort_level: 'Minimal',
    time_to_benefit: '2-4 Weeks',
    evidence_quality: 10,
    effect_size_estimate: 'Moderate',
    evidence_summary: 'Definitive medical consensus on iodine requirements for thyroid function.',
    safety_level: 'High',
    safety_summary: 'Do not exceed 500 mcg without medical supervision for autoimmune thyroid disease.',
    contraindications: ['Hashimotos thyroiditis exacerbation (monitor TPO antibodies)'],
    primary_outcome: 'Thyroid & Metabolic Regulation',
    secondary_outcomes: ['Cognitive Function', 'Cellular Energy'],
    mechanism_of_action: 'Thyroid peroxidase (TPO) mediated organification into T3/T4',
    dose_details: {
      starter_dose: 75,
      personalized_target_dose: 125,
      blueprint_dose: 125,
      unit: 'mcg',
      literature_range: { min: 75, max: 300, outlier_upper: 1000 },
      starter_notes: '75mcg is conservative for sensitive thyroid profiles.',
      recommended_notes: '125mcg meets RDA and supports steady thyroid hormone output.',
      blueprint_notes: 'Bryan Johnson 2026 Blueprint dose: 125 mcg morning.'
    }
  },
  {
    id: 'lycopene',
    slug: 'lycopene',
    name: 'Lycopene (Standardized Tomato Extract)',
    category: 'Supplements & Nutraceuticals',
    modality_type: 'supplement',
    logging_type: 'supplement',
    status: 'active',
    brief_description: 'Potent lipophilic carotenoid antioxidant targeting prostate tissue, endothelial lining, and LDL protection.',
    expanded_why: 'Lycopene accumulates selectively in prostate, adrenal, and vascular tissue where it quenches singlet oxygen twice as effectively as beta-carotene and suppresses inflammatory IL-6.',
    headline_benefit: 'Quenches lipophilic ROS, protecting prostate & blood vessel walls',
    dose_or_exposure: '10 mg – 30 mg',
    timing_summary: 'Morning with healthy fats',
    frequency: 'Daily',
    cadence_layer: 'daily',
    difficulty: 'Very Easy',
    cost_tier: 'Low ($0.30/day)',
    effort_level: 'Minimal',
    time_to_benefit: '4-8 Weeks',
    evidence_quality: 9,
    effect_size_estimate: 'Moderate',
    evidence_summary: 'Strong epidemiological and clinical trial links to reduced prostate cancer risk and improved flow-mediated dilation.',
    safety_level: 'Very High',
    safety_summary: 'Non-toxic dietary carotenoid.',
    contraindications: ['None known'],
    primary_outcome: 'Prostate & Endothelial Protection',
    secondary_outcomes: ['LDL Oxidation Defense', 'Skin UV Photoprotection'],
    mechanism_of_action: 'Singlet oxygen quenching & NF-kB pathway down-regulation',
    dose_details: {
      starter_dose: 5,
      personalized_target_dose: 10,
      blueprint_dose: 10,
      unit: 'mg',
      literature_range: { min: 5, max: 30, outlier_upper: 60 },
      starter_notes: '5mg daily with healthy fats for baseline carotenoid support.',
      recommended_notes: '10mg daily provides solid tissue photoprotection and prostate support.',
      blueprint_notes: 'Bryan Johnson 2026 Blueprint dose: 10 mg morning.'
    }
  },
  {
    id: 'heme-iron',
    slug: 'heme-iron',
    name: 'Heme Iron (Proferrin / Polypeptide Heme)',
    category: 'Supplements & Nutraceuticals',
    modality_type: 'supplement',
    logging_type: 'supplement',
    status: 'active',
    brief_description: 'Highly bioavailable metalloporphyrin iron form absorbed directly via HCP-1 without GI distress.',
    expanded_why: 'Heme iron is absorbed intact through the heme carrier protein 1 (HCP-1) pathway without requiring stomach acid ionization, avoiding oxidative free radical formation in the intestinal gut lumen.',
    headline_benefit: 'Restores ferritin and red blood cells without intestinal distress',
    dose_or_exposure: '10 mg',
    timing_summary: 'Morning',
    frequency: 'Daily',
    cadence_layer: 'daily',
    difficulty: 'Very Easy',
    cost_tier: 'Moderate ($0.50/day)',
    effort_level: 'Minimal',
    time_to_benefit: '2-4 Weeks',
    evidence_quality: 9,
    effect_size_estimate: 'Large',
    evidence_summary: 'Clinical studies confirm 3-5x superior bioavailability over ferrous sulfate with minimal gastrointestinal side effects.',
    safety_level: 'High',
    safety_summary: 'Monitor ferritin levels periodically to avoid iron overload.',
    contraindications: ['Hemochromatosis / Iron overload disorders'],
    primary_outcome: 'Oxygen Transport & Ferritin Optimization',
    secondary_outcomes: ['Mitochondrial Energy', 'Physical Endurance'],
    mechanism_of_action: 'HCP-1 receptor-mediated endocytosis of intact porphyrin ring',
    dose_details: {
      starter_dose: 5,
      personalized_target_dose: 10,
      blueprint_dose: 10,
      unit: 'mg',
      literature_range: { min: 5, max: 30, outlier_upper: 60 },
      starter_notes: '5mg is safe for checking ferritin response.',
      recommended_notes: '10mg heme iron maintains steady red blood cell synthesis.',
      blueprint_notes: 'Bryan Johnson 2026 Blueprint dose: 10 mg morning.'
    }
  },
  {
    id: 'cocoa-flavanols',
    slug: 'cocoa-flavanols',
    name: 'Cocoa Flavanols (High-Flavanol Extract)',
    category: 'Supplements & Nutraceuticals',
    modality_type: 'supplement',
    logging_type: 'supplement',
    status: 'active',
    brief_description: 'Standardized monomeric epicatechin extract stimulating endothelial nitric oxide and cerebrovascular blood flow.',
    expanded_why: 'Cocoa flavanols (specifically (-)-epicatechin) activate endothelial nitric oxide synthase (eNOS), increasing arterial elasticity, reducing peripheral vascular resistance, and improving memory performance in cognitive trials.',
    headline_benefit: 'Enhances nitric oxide release & cerebrovascular perfusion',
    dose_or_exposure: '500 mg – 1,000 mg flavanols',
    timing_summary: 'Dinner / Evening',
    frequency: 'Daily',
    cadence_layer: 'daily',
    difficulty: 'Very Easy',
    cost_tier: 'Moderate ($0.70/day)',
    effort_level: 'Minimal',
    time_to_benefit: '2-4 Weeks',
    evidence_quality: 10,
    effect_size_estimate: 'Moderate to Large',
    evidence_summary: 'COSMOS large-scale clinical trial and cognitive studies validate cardiovascular death reduction and flow-mediated dilation improvement.',
    safety_level: 'Very High',
    safety_summary: 'Extremely safe; check for low caffeine content if taken late evening.',
    contraindications: ['Severe hypotension'],
    primary_outcome: 'Endothelial & Cerebrovascular Flow',
    secondary_outcomes: ['Cognitive Function', 'Blood Pressure Control', 'Skin Microcirculation'],
    mechanism_of_action: 'eNOS phosphorylation and Akt pathway stimulation',
    dose_details: {
      starter_dose: 250,
      personalized_target_dose: 500,
      blueprint_dose: 500,
      unit: 'mg',
      literature_range: { min: 250, max: 1000, outlier_upper: 1500 },
      starter_notes: '250mg provides baseline nitric oxide support.',
      recommended_notes: '500mg delivers the exact dose validated in the COSMOS trial.',
      blueprint_notes: 'Bryan Johnson 2026 Blueprint dose: 500 mg dinner.'
    }
  },
  {
    id: 'vitamin-e',
    slug: 'vitamin-e',
    name: 'Vitamin E (Mixed Tocopherols & Tocotrienols)',
    category: 'Supplements & Nutraceuticals',
    modality_type: 'supplement',
    logging_type: 'supplement',
    status: 'active',
    brief_description: 'Full-spectrum lipophilic antioxidant protecting cell membranes and plasma lipids against lipid peroxidation.',
    expanded_why: 'Mixed alpha/gamma-tocopherols and tocotrienols integrate into phospholipid cell membranes, breaking lipid peroxidation chain reactions and protecting polyunsaturated fatty acids from oxidative degradation.',
    headline_benefit: 'Protects cell membranes and circulating lipoproteins from ROS oxidation',
    dose_or_exposure: '67 mg (100 IU)',
    timing_summary: 'Dinner with fat-containing meal',
    frequency: 'Daily',
    cadence_layer: 'daily',
    difficulty: 'Very Easy',
    cost_tier: 'Low ($0.20/day)',
    effort_level: 'Minimal',
    time_to_benefit: '2-4 Weeks',
    evidence_quality: 9,
    effect_size_estimate: 'Moderate',
    evidence_summary: 'Extensive biochemical literature establishing lipid membrane protection and neuroprotection with mixed isomers.',
    safety_level: 'High',
    safety_summary: 'Keep under 400 IU (268 mg) daily for long-term health.',
    contraindications: ['High-dose blood thinning agents (monitor INR/PT)'],
    primary_outcome: 'Cell Membrane Integrity & Lipid Defense',
    secondary_outcomes: ['Skin Health', 'Neuroprotection'],
    mechanism_of_action: 'Peroxyl radical scavenging in lipophilic membrane bi-layers',
    dose_details: {
      starter_dose: 30,
      personalized_target_dose: 67,
      blueprint_dose: 67,
      unit: 'mg',
      literature_range: { min: 30, max: 200, outlier_upper: 400 },
      starter_notes: '30mg provides essential membrane protection.',
      recommended_notes: '67mg (100 IU) maintains ideal cellular Tocopherol ratios.',
      blueprint_notes: 'Bryan Johnson 2026 Blueprint dose: 67 mg (100 IU) dinner.'
    }
  },
  {
    id: 'glucosamine-sulfate',
    slug: 'glucosamine-sulfate',
    name: 'Glucosamine Sulfate 2KCl',
    category: 'Supplements & Nutraceuticals',
    modality_type: 'supplement',
    logging_type: 'supplement',
    status: 'active',
    brief_description: 'Aminosugar substrate for glycosaminoglycan synthesis and nutrient-sensing autophagy activator.',
    expanded_why: 'Glucosamine acts as a building block for joint cartilage extracellular matrix while inhibiting the hexosamine biosynthetic pathway to induce AMPK-mediated cellular autophagy and extend model organism lifespan.',
    headline_benefit: 'Supports joint cartilage matrix & induces autophagy pathways',
    dose_or_exposure: '1,500 mg',
    timing_summary: 'Dinner with food',
    frequency: 'Daily',
    cadence_layer: 'daily',
    difficulty: 'Very Easy',
    cost_tier: 'Low ($0.30/day)',
    effort_level: 'Minimal',
    time_to_benefit: '4-8 Weeks',
    evidence_quality: 9,
    effect_size_estimate: 'Moderate to Large',
    evidence_summary: 'Large human prospective cohort studies (UK Biobank n=466,003) show 15% lower all-cause mortality in regular glucosamine users.',
    safety_level: 'High',
    safety_summary: 'Well-tolerated long-term nutrient.',
    contraindications: ['Severe shellfish allergy (use corn-derived fermentation version)'],
    primary_outcome: 'Joint Cartilage & Lifespan Extension',
    secondary_outcomes: ['Autophagy Induction', 'Cardiovascular Longevity'],
    mechanism_of_action: 'Glycosaminoglycan matrix synthesis & AMPK-dependent autophagy mimetic',
    dose_details: {
      starter_dose: 750,
      personalized_target_dose: 1500,
      blueprint_dose: 1500,
      unit: 'mg',
      literature_range: { min: 750, max: 3000, outlier_upper: 4000 },
      starter_notes: '750mg with dinner for gentle initiation.',
      recommended_notes: '1,500mg daily delivers the clinical joint and lifespan mortality benefit.',
      blueprint_notes: 'Bryan Johnson 2026 Blueprint dose: 1,500 mg dinner.'
    }
  },
  {
    id: 'l-lysine',
    slug: 'l-lysine',
    name: 'L-Lysine',
    category: 'Supplements & Nutraceuticals',
    modality_type: 'supplement',
    logging_type: 'supplement',
    status: 'active',
    brief_description: 'Essential amino acid for collagen cross-linking, viral latency homeostasis, and calcium absorption.',
    expanded_why: 'L-Lysine is incorporated into collagen proteins where lysyl oxidase converts it into reactive aldehydes for covalent intermolecular cross-linking, giving connective tissue structural resilience.',
    headline_benefit: 'Drives structural collagen cross-linking & immune matrix integrity',
    dose_or_exposure: '1,000 mg – 2,000 mg',
    timing_summary: 'Dinner',
    frequency: 'Daily',
    cadence_layer: 'daily',
    difficulty: 'Very Easy',
    cost_tier: 'Low ($0.15/day)',
    effort_level: 'Minimal',
    time_to_benefit: '2-4 Weeks',
    evidence_quality: 9,
    effect_size_estimate: 'Moderate',
    evidence_summary: 'Established essential amino acid role in protein synthesis, intestinal calcium absorption, and viral suppression.',
    safety_level: 'Very High',
    safety_summary: 'Non-toxic essential amino acid.',
    contraindications: ['Renal failure without amino acid restriction monitoring'],
    primary_outcome: 'Collagen Architecture & Immune Health',
    secondary_outcomes: ['Calcium Retention', 'Anxiety Attenuation'],
    mechanism_of_action: 'Lysyl oxidase substrate for covalent collagen triple-helix assembly',
    dose_details: {
      starter_dose: 500,
      personalized_target_dose: 1000,
      blueprint_dose: 1000,
      unit: 'mg',
      literature_range: { min: 500, max: 3000, outlier_upper: 5000 },
      starter_notes: '500mg provides baseline amino acid supplementation.',
      recommended_notes: '1,000mg supports active collagen turnover.',
      blueprint_notes: 'Bryan Johnson 2026 Blueprint dose: 1 g dinner.'
    }
  },
  {
    id: 'curcumin',
    slug: 'curcumin',
    name: 'Curcumin (Bio-Enhanced Turmeric Extract)',
    category: 'Supplements & Nutraceuticals',
    modality_type: 'supplement',
    logging_type: 'supplement',
    status: 'active',
    brief_description: 'Bio-enhanced polyphenolic NF-kB inhibitor, COX-2 down-regulator, and potent anti-inflammatory compound.',
    expanded_why: 'Curcumin suppresses nuclear factor kappa B (NF-kB) signaling, reducing inflammatory cytokines (TNF-alpha, IL-1b, IL-6), preserving synaptic plasticity, and alleviating joint soreness.',
    headline_benefit: 'Suppresses NF-kB inflammatory cascade & joint/neural soreness',
    dose_or_exposure: '1,000 mg (Split Dinner & Bedtime)',
    timing_summary: 'Dinner & Bedtime with healthy fats',
    frequency: 'Daily',
    cadence_layer: 'daily',
    difficulty: 'Very Easy',
    cost_tier: 'Low ($0.35/day)',
    effort_level: 'Minimal',
    time_to_benefit: '2-4 Weeks',
    evidence_quality: 10,
    effect_size_estimate: 'Large',
    evidence_summary: 'Extensive randomized trials showing significant hs-CRP reduction, joint pain relief, and BDNF upregulation.',
    safety_level: 'High',
    safety_summary: 'Very high safety margin; use phospholipid or piperine bio-enhanced extract.',
    contraindications: ['Biliary tract obstruction / gallstones'],
    primary_outcome: 'Systemic Anti-Inflammatory & Joint Health',
    secondary_outcomes: ['Brain BDNF Support', 'Gut Microbiome Alignment'],
    mechanism_of_action: 'NF-kB transcription factor inhibition and IkappaB kinase inactivation',
    dose_details: {
      starter_dose: 500,
      personalized_target_dose: 1000,
      blueprint_dose: 1000,
      unit: 'mg',
      literature_range: { min: 500, max: 2000, outlier_upper: 4000 },
      starter_notes: '500mg with dinner for gentle systemic absorption.',
      recommended_notes: '1,000mg daily delivers optimal systemic anti-inflammatory suppression.',
      blueprint_notes: 'Bryan Johnson 2026 Blueprint dose: 1 g daily (500mg Dinner / 500mg Bed).'
    }
  },
  {
    id: 'genistein',
    slug: 'genistein',
    name: 'Genistein (Soy Isoflavone Extract)',
    category: 'Supplements & Nutraceuticals',
    modality_type: 'supplement',
    logging_type: 'supplement',
    status: 'active',
    brief_description: 'Selective estrogen receptor beta (ER-beta) agonist and protein tyrosine kinase inhibitor for vascular health.',
    expanded_why: 'Genistein binds selectively to ER-beta receptors in blood vessels and bone tissue, inhibiting tyrosine kinases to improve arterial compliance and maintain lipid balance.',
    headline_benefit: 'Selective ER-beta agonist preserving vascular compliance',
    dose_or_exposure: '125 mg',
    timing_summary: 'Dinner',
    frequency: 'Daily',
    cadence_layer: 'daily',
    difficulty: 'Very Easy',
    cost_tier: 'Moderate ($0.45/day)',
    effort_level: 'Minimal',
    time_to_benefit: '4-8 Weeks',
    evidence_quality: 8,
    effect_size_estimate: 'Moderate',
    evidence_summary: 'Clinical trial evidence supporting bone mineral density retention and arterial flow-mediated dilation.',
    safety_level: 'High',
    safety_summary: 'Safe dietary phytoestrogen; monitor in estrogen-sensitive oncological conditions.',
    contraindications: ['Estrogen-receptor positive breast/prostate malignancies'],
    primary_outcome: 'Vascular Compliance & Hormone Support',
    secondary_outcomes: ['Bone Density Maintenance', 'Lipid Profile Balance'],
    mechanism_of_action: 'Selective ER-beta receptor agonism & tyrosine kinase enzyme inhibition',
    dose_details: {
      starter_dose: 50,
      personalized_target_dose: 125,
      blueprint_dose: 125,
      unit: 'mg',
      literature_range: { min: 50, max: 250, outlier_upper: 500 },
      starter_notes: '50mg is a mild introductory dose.',
      recommended_notes: '125mg provides optimal ER-beta vascular binding.',
      blueprint_notes: 'Bryan Johnson 2026 Blueprint dose: 125 mg dinner.'
    }
  },
  {
    id: 'extra-virgin-olive-oil',
    slug: 'extra-virgin-olive-oil',
    name: 'High-Polyphenol Extra Virgin Olive Oil (EVOO)',
    category: 'Supplements & Nutraceuticals',
    modality_type: 'supplement',
    logging_type: 'nutrition',
    status: 'active',
    brief_description: 'Oleocanthal-rich unrefined olive oil acting as a natural COX inhibitor and sirtuin-1 autophagy activator.',
    expanded_why: 'High-polyphenol EVOO supplies oleocanthal (a natural NSAID-like COX-1/COX-2 inhibitor) and hydroxytyrosol, activating SIRT1 and stimulating macroautophagy clearance of cellular waste.',
    headline_benefit: 'Natural oleocanthal COX-inhibition & SIRT1 autophagy induction',
    dose_or_exposure: '15 mL – 30 mL (1-2 tablespoons)',
    timing_summary: 'Dinner / Daily with food',
    frequency: 'Daily',
    cadence_layer: 'daily',
    difficulty: 'Very Easy',
    cost_tier: 'Low ($0.40/day)',
    effort_level: 'Minimal',
    time_to_benefit: 'Immediate',
    evidence_quality: 10,
    effect_size_estimate: 'Large',
    evidence_summary: 'PREDIMED landmark clinical trial proving 30% reduction in major cardiovascular events with high EVOO intake.',
    safety_level: 'Very High',
    safety_summary: 'Whole food dietary staple with exceptional safety profile.',
    contraindications: ['None known'],
    primary_outcome: 'Cardiovascular & Autophagy Mimetic',
    secondary_outcomes: ['Lipid Peroxidation Resistance', 'Metabolic Health'],
    mechanism_of_action: 'Oleocanthal COX inhibition & SIRT1 deacetylase activation',
    dose_details: {
      starter_dose: 15,
      personalized_target_dose: 30,
      blueprint_dose: 30,
      unit: 'mL',
      literature_range: { min: 15, max: 45, outlier_upper: 60 },
      starter_notes: '15 mL (1 tbsp) taken raw or over salad.',
      recommended_notes: '30 mL (2 tbsp) daily matches PREDIMED trial cardio-protective levels.',
      blueprint_notes: 'Bryan Johnson 2026 Blueprint dose: 30 mL (2 tbsp) dinner.'
    }
  },
  {
    id: 'ndga',
    slug: 'ndga',
    name: 'NDGA (Nordihydroguaiaretic Acid)',
    category: 'Supplements & Nutraceuticals',
    modality_type: 'supplement',
    logging_type: 'supplement',
    status: 'active',
    brief_description: 'Creosote-derived polyphenolic lipoxygenase inhibitor shown in ITP studies to extend lifespan in model organisms.',
    expanded_why: 'Nordihydroguaiaretic Acid (NDGA) inhibits 5-lipoxygenase (5-LOX) and suppresses inflammatory arachidonic acid cascades. Validated by the NIH Interventions Testing Program (ITP) for lifespan extension.',
    headline_benefit: 'NIH ITP validated lifespan extension & 5-LOX inflammatory suppression',
    dose_or_exposure: '50 mg',
    timing_summary: 'Bedtime',
    frequency: 'Daily',
    cadence_layer: 'daily',
    difficulty: 'Easy',
    cost_tier: 'Moderate ($0.60/day)',
    effort_level: 'Minimal',
    time_to_benefit: '4-12 Weeks',
    evidence_quality: 8,
    effect_size_estimate: 'Moderate to Large',
    evidence_summary: 'NIH Interventions Testing Program (ITP) verified reproducible male rodent lifespan extension.',
    safety_level: 'Moderate',
    safety_summary: 'Keep doses low (50 mg) and monitor liver enzymes (ALT/AST) periodically.',
    contraindications: ['Active hepatic dysfunction / liver disease'],
    primary_outcome: 'Lifespan Extension & 5-LOX Inhibition',
    secondary_outcomes: ['Lipid Peroxidation Resistance', 'Neuroinflammation Clearance'],
    mechanism_of_action: '5-lipoxygenase (5-LOX) enzymatic inhibition & ROS scavenging',
    dose_details: {
      starter_dose: 25,
      personalized_target_dose: 50,
      blueprint_dose: 50,
      unit: 'mg',
      literature_range: { min: 25, max: 100, outlier_upper: 250 },
      starter_notes: '25mg is a prudent starter dose for checking liver enzyme tolerance.',
      recommended_notes: '50mg matches the low-dose blueprint longevity protocol.',
      blueprint_notes: 'Bryan Johnson 2026 Blueprint dose: 50 mg bedtime.'
    }
  },
  {
    id: 'low-dose-aspirin',
    slug: 'low-dose-aspirin',
    name: 'Low-Dose Aspirin (81mg)',
    category: 'Supplements & Nutraceuticals',
    modality_type: 'supplement',
    logging_type: 'supplement',
    status: 'active',
    brief_description: 'Irreversible COX-1 inhibitor suppressing platelet thromboxane A2 for cardiovascular thrombosis prevention.',
    expanded_why: 'Acetylsalicylic acid (81 mg) acetylates Ser-529 of cyclooxygenase-1 (COX-1), blocking thromboxane A2 synthesis in platelets to prevent micro-thrombi formation and reduce systemic arterial inflammation.',
    headline_benefit: 'Irreversible platelet COX-1 inhibition preventing arterial micro-clots',
    dose_or_exposure: '81 mg (3x per week)',
    timing_summary: 'Bedtime (3x/week)',
    frequency: '3x Weekly',
    cadence_layer: 'weekly',
    difficulty: 'Very Easy',
    cost_tier: 'Low ($0.05/day)',
    effort_level: 'Minimal',
    time_to_benefit: 'Immediate',
    evidence_quality: 10,
    effect_size_estimate: 'Moderate',
    evidence_summary: 'Decades of secondary prevention cardiovascular trial data.',
    safety_level: 'Moderate',
    safety_summary: 'Risk of GI mucosal bleeding; pulsed 3x/week schedule minimizes ulcer risk.',
    contraindications: ['Active peptic ulcer disease', 'Bleeding disorders / Hemophilia'],
    primary_outcome: 'Cardiovascular Thrombosis Protection',
    secondary_outcomes: ['Colorectal Inflammation Protection', 'Platelet Anti-Aggregation'],
    mechanism_of_action: 'Irreversible COX-1 active site acetylation & Thromboxane A2 blockade',
    dose_details: {
      starter_dose: 81,
      personalized_target_dose: 81,
      blueprint_dose: 81,
      unit: 'mg',
      literature_range: { min: 81, max: 325, outlier_upper: 650 },
      starter_notes: '81mg taken 1x per week initially to test gastric tolerance.',
      recommended_notes: '81mg taken 3x per week balances anti-platelet activity with mucosal safety.',
      blueprint_notes: 'Bryan Johnson 2026 Blueprint dose: 81 mg 3x/week bedtime.'
    }
  }
];

async function seed() {
  console.log(`Preparing to insert/upsert ${newModalities.length} modalities...`);

  for (const m of newModalities) {
    const payload = {
      id: m.id,
      slug: m.slug,
      name: m.name,
      category: m.category,
      modality_type: m.modality_type,
      logging_type: m.logging_type,
      status: m.status,
      brief_description: m.brief_description,
      expanded_why: m.expanded_why,
      headline_benefit: m.headline_benefit,
      dose_or_exposure: m.dose_or_exposure,
      timing_summary: m.timing_summary,
      frequency: m.frequency,
      cadence_layer: m.cadence_layer,
      difficulty: m.difficulty,
      cost_tier: m.cost_tier,
      effort_level: m.effort_level,
      time_to_benefit: m.time_to_benefit,
      evidence_quality: m.evidence_quality,
      effect_size_estimate: m.effect_size_estimate,
      evidence_summary: m.evidence_summary,
      safety_level: m.safety_level,
      safety_summary: m.safety_summary,
      contraindications: m.contraindications,
      primary_outcome: m.primary_outcome,
      secondary_outcomes: m.secondary_outcomes,
      mechanism_of_action: m.mechanism_of_action,
      relationships: { dosage_profile: m.dose_details }
    };

    const { error } = await supabase.from('modalities').upsert(payload, { onConflict: 'id' });
    if (error) {
      console.error(`❌ Error inserting ${m.id}:`, error.message);
    } else {
      console.log(`✅ Upserted modality: ${m.name}`);
    }
  }

  console.log('\nAll 19 modalities seeded into Supabase successfully!');
}

seed();
