UPDATE modalities SET hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'continuous_glucose_monitor';
UPDATE modalities SET hallmarks_of_aging_impact = '["Cellular Senescence","Altered Intercellular Communication"]'::jsonb WHERE id = 'apigenin';
UPDATE modalities SET hallmarks_of_aging_impact = '["Stem Cell Exhaustion"]'::jsonb WHERE id = 'bfr_training';
UPDATE modalities SET hallmarks_of_aging_impact = '["Mitochondrial Dysfunction"]'::jsonb WHERE id = 'red_light_photobiomodulation_therapy';
UPDATE modalities SET hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'ashwagandha_ksm_66';
UPDATE modalities SET hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'l_theanine';
UPDATE modalities SET hallmarks_of_aging_impact = '["Disabled Macroautophagy","Cellular Senescence","Stem Cell Exhaustion"]'::jsonb WHERE id = 'longo_5day_fasting_mimicking_diet';
UPDATE modalities SET hallmarks_of_aging_impact = '["Genomic Instability","Epigenetic Alterations","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'sinclair_nmn_tmg';
UPDATE modalities SET hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'box_breathing';
UPDATE modalities SET hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'magnesium_threonate';
UPDATE modalities SET hallmarks_of_aging_impact = '["Loss of Proteostasis","Chronic Inflammation"]'::jsonb WHERE id = 'curcumin';
UPDATE modalities SET hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'cyclic_sighing';
UPDATE modalities SET hallmarks_of_aging_impact = '["Disabled Macroautophagy","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'urolithin_a_mitophagy';
UPDATE modalities SET hallmarks_of_aging_impact = '["Disabled Macroautophagy","Loss of Proteostasis"]'::jsonb WHERE id = 'spermidine_supplement';
UPDATE modalities SET hallmarks_of_aging_impact = '["Cellular Senescence"]'::jsonb WHERE id = 'fisetin';
UPDATE modalities SET hallmarks_of_aging_impact = '["Epigenetic Alterations"]'::jsonb WHERE id = 'sinclair_trans_resveratrol';
UPDATE modalities SET hallmarks_of_aging_impact = '["Mitochondrial Dysfunction"]'::jsonb WHERE id = 'creatine_monohydrate';
UPDATE modalities SET hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'sinclair_metformin_berberine';
UPDATE modalities SET hallmarks_of_aging_impact = '["Disabled Macroautophagy","Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'monk_fast_36h';
UPDATE modalities SET hallmarks_of_aging_impact = '["Disabled Macroautophagy","Stem Cell Exhaustion"]'::jsonb WHERE id = 'extended_fast_48h';
UPDATE modalities SET hallmarks_of_aging_impact = '["Mitochondrial Dysfunction"]'::jsonb WHERE id = 'coq10';
UPDATE modalities SET hallmarks_of_aging_impact = '["Genomic Instability","Epigenetic Alterations","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'nmn';
UPDATE modalities SET hallmarks_of_aging_impact = '["Cellular Senescence"]'::jsonb WHERE id = 'fisetin_quercetin_senolytic_pulse';
UPDATE modalities SET hallmarks_of_aging_impact = '["Genomic Instability","Epigenetic Alterations"]'::jsonb WHERE id = 'nad_precursors';
UPDATE modalities SET hallmarks_of_aging_impact = '["Epigenetic Alterations","Stem Cell Exhaustion"]'::jsonb WHERE id = 'resistance_training';
UPDATE modalities SET hallmarks_of_aging_impact = '["Disabled Macroautophagy","Stem Cell Exhaustion","Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'prolonged_autophagy_fast_72h';
UPDATE modalities SET hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'magnesium_glycinate';
UPDATE modalities SET hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'blue_light_blocking';
UPDATE modalities SET hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'melatonin';
UPDATE modalities SET hallmarks_of_aging_impact = '["Genomic Instability","Chronic Inflammation"]'::jsonb WHERE id = 'glycine_3g';
UPDATE modalities SET hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'acarbose';
UPDATE modalities SET hallmarks_of_aging_impact = '["Cellular Senescence"]'::jsonb WHERE id = 'longo_fisetin_quercetin_senolytic_pulse';
UPDATE modalities SET hallmarks_of_aging_impact = '["Genomic Instability","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'astaxanthin';
UPDATE modalities SET hallmarks_of_aging_impact = '["Mitochondrial Dysfunction"]'::jsonb WHERE id = 'zone_2_cardio';
UPDATE modalities SET hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'intermittent_fasting_18_6';
UPDATE modalities SET hallmarks_of_aging_impact = '["Stem Cell Exhaustion"]'::jsonb WHERE id = 'hyperbaric_oxygen_therapy_hbot';
UPDATE modalities SET hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'means_berberine_gda';
UPDATE modalities SET hallmarks_of_aging_impact = '["Chronic Inflammation","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'cold_water_immersion';
UPDATE modalities SET hallmarks_of_aging_impact = '["Loss of Proteostasis"]'::jsonb WHERE id = 'sauna_exposure';
UPDATE modalities SET hallmarks_of_aging_impact = '["Cellular Senescence"]'::jsonb WHERE id = 'quercetin';
UPDATE modalities SET hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'intermittent_fasting_20_4';
UPDATE modalities SET hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'metformin_daily';
UPDATE modalities SET hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'morning_sunlight';
UPDATE modalities SET hallmarks_of_aging_impact = '["Disabled Macroautophagy","Mitochondrial Dysfunction"]'::jsonb WHERE id = 'urolithin_a';
UPDATE modalities SET hallmarks_of_aging_impact = '["Genomic Instability","Chronic Inflammation"]'::jsonb WHERE id = 'sulforaphane';
UPDATE modalities SET hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'berberine';
UPDATE modalities SET hallmarks_of_aging_impact = '["Epigenetic Alterations"]'::jsonb WHERE id = 'resveratrol_pterostilbene';
UPDATE modalities SET hallmarks_of_aging_impact = '["Deregulated Nutrient Sensing"]'::jsonb WHERE id = 'intermittent_fasting_16_8';
UPDATE modalities SET hallmarks_of_aging_impact = '["Telomere Attrition","Chronic Inflammation"]'::jsonb WHERE id = 'epa_dha_omega3';
UPDATE modalities SET hallmarks_of_aging_impact = '["Altered Intercellular Communication"]'::jsonb WHERE id = 'ashwagandha_ksm66';
UPDATE modalities SET hallmarks_of_aging_impact = '["Mitochondrial Dysfunction"]'::jsonb WHERE id = 'blueprint_red_light_therapy';