-- Master Seed File: Auto-generated from live database

-- Reset existing modalities
TRUNCATE TABLE modalities CASCADE;

INSERT INTO modalities (
  id,
  slug,
  name,
  modality_type,
  category,
  status,
  display_name,
  brief_description,
  expanded_why,
  headline_benefit,
  primary_outcome,
  secondary_outcomes,
  overall_longevity_benefit,
  implementation_summary,
  instructions,
  dose_or_exposure,
  timing_summary,
  frequency,
  schedule_pattern,
  difficulty,
  cost_tier,
  effort_level,
  time_to_benefit,
  evidence_quality,
  effect_size_estimate,
  evidence_summary,
  safety_level,
  safety_summary,
  contraindications,
  functional_outcomes_to_track,
  hallmarks_of_aging_impact,
  mechanism_of_action,
  onset_profile,
  half_life_profile,
  ideal_cohort,
  contraindicating_cohort,
  relationships,
  media_assets,
  review_status,
  version,
  updated_at,
  synergy_notes,
  antagonism_notes,
  embedding,
  efficacy_stats
) VALUES 
(
  'magnesium_threonate',
  'magnesium_threonate',
  'Magnesium Threonate',
  'supplement',
  'Biochemistry',
  'active',
  'Magnesium Threonate',
  'A health and longevity modality focused on cognitive_health.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'cognitive_health',
  NULL,
  3,
  NULL,
  NULL,
  '144mg elemental Mg (approx 2000mg Magtein)',
  'Evening',
  'Daily',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['cognitive_health', 'sleep_quality', 'focus'],
  ARRAY[]::text[],
  'A unique magnesium salt capable of efficiently crossing the blood-brain barrier to increase synaptic density and enhance cognitive function.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:53:22.144956+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"L-TAMS (Magnesium Threonate) is uniquely capable of crossing the blood-brain barrier. A clinical trial showed it reversed clinical measures of brain aging by 9 years after 12 weeks of use in older adults.","source":"Liu et al., 2016","source_url":"https://pubmed.ncbi.nlm.nih.gov/26519439/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["cognitive_health","sleep_quality","focus"],"interesting_score":4}'::jsonb]
),
(
  'taurine',
  'taurine',
  'Taurine',
  'supplement',
  'Biochemistry',
  'active',
  'Taurine',
  'A health and longevity modality focused on longevity.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'longevity',
  NULL,
  4,
  NULL,
  NULL,
  '1-3g',
  'Pre-workout or Evening',
  'Daily',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['longevity', 'cardiovascular_health', 'energy'],
  ARRAY[]::text[],
  'Acts as an osmolyte and cytoprotectant, regulating mitochondrial protein synthesis and reducing inflammaging across multiple organ systems.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:53:22.144956+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"A landmark 2023 study found that taurine levels decline by 80% with age, and daily taurine supplementation in mice increased median lifespan by 10-12% while improving bone density and muscle strength.","source":"Singh et al., 2023 (Science)","source_url":"https://pubmed.ncbi.nlm.nih.gov/37289866/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["longevity","cardiovascular_health","energy"],"interesting_score":4}'::jsonb]
),
(
  'delay_caffeine',
  'delay-caffeine',
  'Delay Caffeine 90-120 Minutes',
  'habit',
  'Circadian Alignment',
  'active',
  'Delay Caffeine (90m)',
  'Waiting at least 90 minutes after waking before consuming any caffeine to prevent the afternoon energy crash.',
  'Adenosine is a molecule that builds up and causes sleep pressure. During sleep, adenosine is cleared. If caffeine (an adenosine receptor antagonist) is consumed immediately upon waking, it blocks receptors before the remaining sleep-induced adenosine is cleared. When the caffeine wears off, a massive backlog of adenosine floods the receptors, causing a severe afternoon crash. Delaying allows natural cortisol to clear the residual adenosine first.',
  NULL,
  'Afternoon Energy Stability',
  NULL,
  3,
  NULL,
  NULL,
  '90-120 min delay',
  'Morning',
  'Daily',
  NULL,
  NULL,
  'free',
  'high',
  NULL,
  3,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['energy', 'brain_fog'],
  ARRAY['Altered Intercellular Communication'],
  'Adenosine receptor blockade timing optimization.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Sunlight provides the cortisol spike needed to wake up naturally while waiting for coffee.","pairsWellWith":["morning_sunlight","hydration"]}'::jsonb,
  '{"rationale":"Extremely difficult to execute if sleep deprived; users may need to titrate the delay slowly.","avoidCombiningWith":["poor_sleep"]}'::jsonb,
  NULL,
  NULL
),
(
  'mouth_taping',
  'mouth-taping',
  'Sleep Mouth Taping',
  'habit',
  'Nervous System & Sleep',
  'active',
  'Mouth Taping',
  'Using a small piece of porous, medical-grade tape to keep the lips lightly sealed during sleep, forcing nasal breathing.',
  'Nasal breathing during sleep significantly increases nitric oxide production in the paranasal sinuses, acting as a vasodilator to increase oxygen delivery. It prevents mouth-breathing-induced dehydration, reduces snoring, and shifts the autonomic nervous system toward parasympathetic dominance, radically increasing the percentage of deep and REM sleep.',
  NULL,
  'Sleep Quality & Snoring Reduction',
  NULL,
  3,
  NULL,
  NULL,
  '1 piece medical tape',
  'Evening',
  'Daily',
  NULL,
  NULL,
  'low',
  'low',
  NULL,
  3,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY['Sleep apnea (without CPAP)', 'Severe nasal obstruction'],
  ARRAY['sleep_quality', 'waking_restedness', 'energy'],
  ARRAY['Mitochondrial Dysfunction'],
  'Nitric oxide upregulation and parasympathetic tone maintenance.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Opens the nasal airway mechanically while the tape ensures it is utilized.","pairsWellWith":["nasal_strips"]}'::jsonb,
  '{"rationale":"Do not use if the nasal airway is fully obstructed by illness or deviated septum.","avoidCombiningWith":["severe_nasal_congestion"]}'::jsonb,
  NULL,
  NULL
),
(
  'blue_light_blocking',
  'blue-light-blocking',
  'Blue Light Blocking Glasses (Evening)',
  'habit',
  'Circadian Alignment',
  'active',
  'Blue Light Blockers',
  'Wearing amber or red-tinted glasses 2-3 hours before bed to block artificial blue and green light.',
  'Melatonin secretion from the pineal gland is powerfully suppressed by light in the 450-480nm range (blue light emitted by screens and LEDs). By physically blocking these wavelengths after sunset, the brain registers "biological darkness", allowing endogenous melatonin to rise naturally, dramatically reducing sleep latency and improving sleep architecture without supplements.',
  NULL,
  'Endogenous Melatonin Production',
  NULL,
  4,
  NULL,
  NULL,
  'Amber/Red glasses',
  'Evening',
  'Daily',
  NULL,
  NULL,
  'medium',
  'low',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['sleep_latency', 'sleep_quality'],
  ARRAY['Altered Intercellular Communication'],
  'Prevention of ipRGC photo-entrainment and melatonin suppression.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Physical blockers are the last line of defense; environmental dimming is the first.","pairsWellWith":["dim_lights","screen_curfews"]}'::jsonb,
  '{"rationale":"Light can still hit the retinas from the periphery if glasses aren''t wraparound.","avoidCombiningWith":["bright_overhead_lights"]}'::jsonb,
  NULL,
  NULL
),
(
  'optic_flow',
  'optic-flow',
  'Optic Flow / Forward Ambulation',
  'habit',
  'Nervous System & Sleep',
  'active',
  'Optic Flow (Walk)',
  'Walking or running outdoors where visual objects pass by your eyes, generating "optic flow" to quiet the amygdala.',
  'Forward ambulation generates lateral eye movements as objects pass in the peripheral vision. These specific eye movements suppress the amygdala and reduce sympathetic nervous system arousal (the basis of EMDR therapy). A 10-20 minute walk generates enough optic flow to significantly rapidly reduce acute stress and anxiety.',
  NULL,
  'Acute Stress Reduction',
  NULL,
  2,
  NULL,
  NULL,
  '10-20 min walk',
  'Anytime',
  'As needed',
  NULL,
  NULL,
  'free',
  'low',
  NULL,
  3,
  '3',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['stress', 'mood'],
  ARRAY['Altered Intercellular Communication'],
  'Amygdala suppression via lateral eye movement signaling.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Combines perfectly with morning light exposure to stack circadian and stress benefits.","pairsWellWith":["morning_sunlight","podcasts"]}'::jsonb,
  '{"rationale":"Treadmills do not generate optic flow since the visual field is static, neutralizing the neurological benefit.","avoidCombiningWith":["treadmills"]}'::jsonb,
  NULL,
  NULL
),
(
  'hyperbaric_oxygen_therapy_hbot',
  'hyperbaric_oxygen_therapy_hbot',
  'Hyperbaric Oxygen Therapy (HBOT)',
  'protocol',
  'Physical',
  'active',
  'Hyperbaric Oxygen Therapy (HBOT)',
  'A health and longevity modality focused on longevity and cognitive_health and cellular_aging.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'longevity',
  NULL,
  4,
  NULL,
  NULL,
  '60-90 min @ 1.5-2.0 ATA',
  'Anytime',
  'Daily (Protocols of 20-60)',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  3,
  '3',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['longevity', 'cognitive_health', 'cellular_aging'],
  ARRAY['Altered intercellular communication'],
  'Floods plasma with oxygen under pressure, stimulating angiogenesis, reducing inflammation, and triggering stem cell mobilization.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:48:25.879193+00:00',
  '{"rationale":"Fasting before HBOT can amplify autophagy and ketosis.","pairsWellWith":["hyperbaric_oxygen","fasting"]}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"A prospective clinical trial involving 60 daily HBOT sessions in healthy adults aged 64 and older led to a significant increase in telomere length (over 20%) and a reduction in senescent immune cells.","source":"Hachmo et al., 2020","source_url":"https://pubmed.ncbi.nlm.nih.gov/33206062/","impact_score":4,"accuracy_score":4,"relevance_score":4,"related_outcomes":["longevity","cognitive_health","cellular_aging"],"interesting_score":5}'::jsonb]
),
(
  'red_light_photobiomodulation_therapy',
  'red_light_photobiomodulation_therapy',
  'Red Light / Photobiomodulation Therapy',
  'protocol',
  'Physical',
  'active',
  'Red Light / Photobiomodulation Therapy',
  'A health and longevity modality focused on cognitive_health and sleep_quality and energy.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'cognitive_health',
  NULL,
  3,
  NULL,
  NULL,
  '10-20 mins (10-50 mW/cm2)',
  'Anytime',
  '3-5x Weekly',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  3,
  '3',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['cognitive_health', 'sleep_quality', 'energy'],
  ARRAY['Altered intercellular communication'],
  'Photons penetrate tissue and are absorbed by cytochrome C oxidase in the mitochondria, directly increasing ATP production and reducing oxidative stress.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:48:25.879193+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"Clinical pilot studies have shown that near-infrared photobiomodulation can lead to significant improvements in standardized cognitive assessments (like MMSE and ADAS-cog) in patients with mild-to-moderate dementia.","source":"Saltmarche et al., 2017","source_url":"https://pubmed.ncbi.nlm.nih.gov/28186867/","impact_score":4,"accuracy_score":4,"relevance_score":4,"related_outcomes":["cognitive_health","sleep_quality","energy"],"interesting_score":4}'::jsonb]
),
(
  'vo2_max_hiit_training',
  'vo2_max_hiit_training',
  'VO2 Max / HIIT Training',
  'exercise',
  'Physical',
  'active',
  'VO2 Max / HIIT Training',
  'A health and longevity modality focused on longevity and cardiovascular_health and metabolic_health.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'longevity',
  NULL,
  5,
  NULL,
  NULL,
  '4x4 intervals (4m hard, 4m active rest)',
  'Morning / Afternoon',
  '1-2x Weekly',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  3,
  '3',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['longevity', 'cardiovascular_health', 'metabolic_health'],
  ARRAY['Altered intercellular communication'],
  'Maximizes stroke volume of the heart and drives mitochondrial biogenesis in muscle tissue, creating a massive metabolic sink for glucose.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:48:25.879193+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"A massive cohort study found that elite cardiorespiratory fitness (top 2.5% of VO2 max) is associated with an 80% reduction in all-cause mortality risk (Hazard Ratio 0.20) compared to the lowest fitness quartile.","source":"Mandsager et al., 2018","source_url":"https://pubmed.ncbi.nlm.nih.gov/30346464/","impact_score":5,"accuracy_score":5,"relevance_score":5,"related_outcomes":["longevity","cardiovascular_health","metabolic_health"],"interesting_score":5}'::jsonb]
),
(
  'glycine_supplementation',
  'glycine_supplementation',
  'Glycine Supplementation',
  'supplement',
  'Biochemistry',
  'active',
  'Glycine Supplementation',
  'A health and longevity modality focused on sleep_quality and metabolic_health.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'sleep_quality',
  NULL,
  3,
  NULL,
  NULL,
  '3-5g',
  'Before Bed',
  'Daily',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  3,
  '3',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['sleep_quality', 'metabolic_health'],
  ARRAY['Altered intercellular communication'],
  'Acts as an inhibitory neurotransmitter in the brainstem, promoting sleep by lowering core body temperature via peripheral vasodilation.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:48:25.879193+00:00',
  '{"rationale":"Combines with NAC to synthesize glutathione, a master antioxidant.","pairsWellWith":["nac_supplement","magnesium_glycinate"]}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"Oral supplementation of 3 grams of glycine before bedtime has been clinically shown to reduce sleep onset latency and improve subjective sleep quality, partially by helping to lower core body temperature.","source":"Yamadera et al., 2007","source_url":"https://pubmed.ncbi.nlm.nih.gov/17229531/","impact_score":3,"accuracy_score":5,"relevance_score":4,"related_outcomes":["sleep_quality","metabolic_health"],"interesting_score":3}'::jsonb]
),
(
  'nad_iv_therapy',
  'nad_iv_therapy',
  'NAD+ IV Therapy',
  'protocol',
  'Physical',
  'active',
  'NAD+ IV Therapy',
  'A health and longevity modality focused on energy and longevity and cellular_aging.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'energy',
  NULL,
  3,
  NULL,
  NULL,
  '250-500mg IV',
  'Morning',
  'Monthly / Cycled',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  3,
  '3',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['energy', 'longevity', 'cellular_aging'],
  ARRAY['Altered intercellular communication'],
  'Bypasses the digestive system to rapidly elevate systemic NAD+ levels, fueling sirtuin activity and PARP DNA repair enzymes.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:48:25.879193+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"Clinical pilot studies demonstrate that intravenous administration of NAD+ safely and significantly increases the NAD+ metabolome in human blood plasma, though large-scale placebo-controlled efficacy trials for longevity outcomes are still ongoing.","source":"Grant et al., 2019","source_url":"https://pubmed.ncbi.nlm.nih.gov/31512154/","impact_score":3,"accuracy_score":4,"relevance_score":4,"related_outcomes":["energy","longevity","cellular_aging"],"interesting_score":4}'::jsonb]
),
(
  'plasmapheresis_therapeutic_plasma_exchange',
  'plasmapheresis_therapeutic_plasma_exchange',
  'Plasmapheresis / Therapeutic Plasma Exchange',
  'protocol',
  'Physical',
  'active',
  'Plasmapheresis / Therapeutic Plasma Exchange',
  'A health and longevity modality focused on cognitive_health and longevity and cellular_aging.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'cognitive_health',
  NULL,
  4,
  NULL,
  NULL,
  '1 Exchange',
  'Anytime',
  '1-4x Annually',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  3,
  '3',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['cognitive_health', 'longevity', 'cellular_aging'],
  ARRAY['Altered intercellular communication'],
  'Mechanically removes accumulated age-related proteins, autoantibodies, and systemic inflammatory factors from plasma.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:48:25.879193+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"The AMBAR Phase 2b/3 trial demonstrated that Therapeutic Plasma Exchange with albumin and IVIG replacement significantly slowed cognitive and functional decline in patients with mild-to-moderate Alzheimer''s disease over a 14-month period.","source":"Boada et al., 2020","source_url":"https://pubmed.ncbi.nlm.nih.gov/32715623/","impact_score":5,"accuracy_score":4,"relevance_score":4,"related_outcomes":["cognitive_health","longevity","cellular_aging"],"interesting_score":5}'::jsonb]
),
(
  'ashwagandha_ksm_66',
  'ashwagandha_ksm_66',
  'Ashwagandha (KSM-66)',
  'supplement',
  'Biochemistry',
  'active',
  'Ashwagandha (KSM-66)',
  'A health and longevity modality focused on stress.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'stress',
  NULL,
  3,
  NULL,
  NULL,
  '300-600mg',
  'Evening / Afternoon',
  'Daily (Cycled)',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['stress', 'sleep_quality', 'anxiety'],
  ARRAY[]::text[],
  'An adaptogen that modulates the HPA axis, significantly lowering serum cortisol and reducing stress-induced anxiety.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:53:22.144956+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"In a randomized, double-blind, placebo-controlled study, supplementation with Ashwagandha root extract (300 mg twice daily) resulted in a 27.9% reduction in serum cortisol levels and significant improvements in stress scores.","source":"Chandrasekhar et al., 2012","source_url":"https://pubmed.ncbi.nlm.nih.gov/23439798/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["stress","sleep_quality","anxiety"],"interesting_score":4}'::jsonb]
),
(
  'alpha_ketoglutarate_akg',
  'alpha_ketoglutarate_akg',
  'Alpha-Ketoglutarate (AKG)',
  'supplement',
  'Biochemistry',
  'active',
  'Alpha-Ketoglutarate (AKG)',
  'A health and longevity modality focused on longevity.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'longevity',
  NULL,
  4,
  NULL,
  NULL,
  '1000mg',
  'Morning',
  'Daily',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['longevity', 'metabolic_health'],
  ARRAY[]::text[],
  'A key intermediate in the Krebs cycle that also acts as a cofactor for TET enzymes, facilitating active DNA demethylation and epigenetic clock reversal.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:53:22.144956+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"A 7-month clinical trial of Calcium AKG supplementation in humans demonstrated an average reduction in biological age (measured by DNA methylation clocks) of 8 years.","source":"Demidenko et al., 2021","source_url":"https://pubmed.ncbi.nlm.nih.gov/34847066/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["longevity","metabolic_health"],"interesting_score":4}'::jsonb]
),
(
  'fisetin',
  'fisetin',
  'Fisetin',
  'supplement',
  'Biochemistry',
  'active',
  'Fisetin',
  'A health and longevity modality focused on longevity.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'longevity',
  NULL,
  3,
  NULL,
  NULL,
  '20mg/kg bodyweight',
  'Morning with fats',
  '2-3 Days Monthly (Hit and Run)',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['longevity', 'cellular_aging'],
  ARRAY[]::text[],
  'A flavonoid that acts as a potent senolytic by inhibiting the PI3K/AKT/mTOR pathway, triggering apoptosis specifically in senescent cells.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:53:22.144956+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"Fisetin has been identified as one of the most potent natural senolytics. In murine models, intermittent fisetin administration extended healthspan and lifespan by approximately 10% by clearing senescent cells.","source":"Yousefzadeh et al., 2018","source_url":"https://pubmed.ncbi.nlm.nih.gov/30279143/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["longevity","cellular_aging"],"interesting_score":4}'::jsonb]
),
(
  'blood_donation_phlebotomy',
  'blood_donation_phlebotomy',
  'Blood Donation (Phlebotomy)',
  'protocol',
  'Physical',
  'active',
  'Blood Donation (Phlebotomy)',
  'A health and longevity modality focused on cardiovascular_health.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'cardiovascular_health',
  NULL,
  3,
  NULL,
  NULL,
  '1 Pint (Whole Blood)',
  'Anytime',
  '2-4x Annually',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['cardiovascular_health', 'longevity', 'cellular_aging'],
  ARRAY[]::text[],
  'Mechanically removes excess serum ferritin (iron) and microplastics from circulation, reducing systemic oxidative stress and lipid peroxidation.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:53:22.144956+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"Regular blood donation reduces accumulated serum ferritin (iron). High iron stores are strongly correlated with increased oxidative stress; donating blood 2-3 times a year significantly lowers cardiovascular disease risk in men.","source":"Meyers et al., 1997","source_url":"https://pubmed.ncbi.nlm.nih.gov/9294974/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["cardiovascular_health","longevity","cellular_aging"],"interesting_score":4}'::jsonb]
),
(
  'n_acetyl_cysteine_nac',
  'n_acetyl_cysteine_nac',
  'N-Acetyl Cysteine (NAC)',
  'supplement',
  'Biochemistry',
  'active',
  'N-Acetyl Cysteine (NAC)',
  'A health and longevity modality focused on cellular_health.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'cellular_health',
  NULL,
  4,
  NULL,
  NULL,
  '600-1200mg',
  'Morning / Fasted',
  'Daily',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['cellular_health', 'respiratory_health', 'longevity'],
  ARRAY[]::text[],
  'Provides the rate-limiting amino acid (cysteine) required for intracellular glutathione synthesis, acting as a powerful systemic antioxidant.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:53:22.144956+00:00',
  '{"rationale":"GlyNAC combination is highly proven to reverse mitochondrial dysfunction in older adults.","pairsWellWith":["glycine_supplementation"]}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"When supplemented with Glycine (GlyNAC), it effectively corrects intracellular glutathione deficiency in older adults, significantly reducing oxidative stress and lowering hallmarks of aging by up to 50%.","source":"Sekhar et al., 2021","source_url":"https://pubmed.ncbi.nlm.nih.gov/33783984/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["cellular_health","respiratory_health","longevity"],"interesting_score":4}'::jsonb]
),
(
  'creatine_monohydrate',
  'creatine-monohydrate',
  'Creatine Monohydrate',
  'supplement',
  'Cellular Energy & Brain',
  'active',
  'Creatine (5g Daily)',
  'A widely studied organic acid that facilitates recycling of ATP, primarily in muscle and brain tissue, enhancing high-intensity energy output and cognitive function.',
  'Creatine acts as a spatial and temporal energy buffer by donating its phosphate group to ADP to recreate ATP during times of rapid energy demand. Beyond muscle hypertrophy and strength (where it has overwhelming evidence), emerging data shows it supports cognitive resilience under sleep deprivation and reduces markers of neurodegeneration by maintaining neuronal energy homeostasis.',
  NULL,
  'Strength & Cognitive Resilience',
  NULL,
  4,
  NULL,
  NULL,
  '5g',
  'Anytime',
  'Daily',
  NULL,
  NULL,
  'low',
  'very_low',
  NULL,
  5,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY['Pre-existing renal disease'],
  ARRAY['strength', 'energy', 'focus', 'brain_fog'],
  ARRAY['Mitochondrial Dysfunction'],
  'Phosphocreatine system buffering; accelerated ATP regeneration.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Insulin spikes from carbs can enhance muscle creatine uptake.","pairsWellWith":["resistance_training","carbohydrates"]}'::jsonb,
  '{"rationale":"High doses of caffeine concurrently may blunt the ergogenic effects of creatine.","avoidCombiningWith":["caffeine_high_dose"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"Creatine supplementation combined with resistance training increases lean tissue mass and upper and lower body muscular strength significantly more than resistance training alone.","source":"Branch, 2003","source_url":"https://pubmed.ncbi.nlm.nih.gov/12945830/","impact_score":4,"accuracy_score":4,"relevance_score":4,"related_outcomes":["strength","energy","longevity"],"interesting_score":3}'::jsonb]
),
(
  'cold_water_immersion',
  'cold-water-immersion',
  'Cold Water Immersion',
  'cold_exposure',
  'Environmental Stress',
  'active',
  'Cold Plunge (1-3 min)',
  'Brief, deliberate exposure to uncomfortably cold water (typically 50°F or lower) to trigger acute hermetic stress and sympathetic nervous system activation.',
  'Cold exposure causes a massive release of norepinephrine (up to 5x baseline) and dopamine (up to 2.5x), leading to prolonged increases in mood, alertness, and focus. Metabolically, it triggers the conversion of white adipose tissue to metabolically active brown adipose tissue (BAT), which burns glucose and lipids to generate heat (non-shivering thermogenesis).',
  NULL,
  'Alertness & Mood',
  NULL,
  3,
  NULL,
  NULL,
  '1-3 min @ <50°F',
  'Morning',
  '2-4x Weekly',
  NULL,
  NULL,
  'free',
  'high',
  NULL,
  3,
  '4',
  NULL,
  'moderate_risk',
  NULL,
  ARRAY['Cardiovascular disease', 'Raynaud''s syndrome', 'Cold urticaria'],
  ARRAY['alertness', 'mood', 'energy', 'stress'],
  ARRAY['Altered Intercellular Communication', 'Mitochondrial Dysfunction'],
  'Sympathetic activation, massive norepinephrine/dopamine release, and BAT thermogenesis.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Using cold plunge early in the day powerfully reinforces the circadian waking signal.","pairsWellWith":["sauna_exposure","morning_routine"]}'::jsonb,
  '{"rationale":"Cold water immersion immediately post-lifting significantly blunts the hypertrophic adaptation pathways (like mTORC1).","avoidCombiningWith":["hypertrophy_training_immediate"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"Acute cold exposure increases metabolic rate by up to 350% and norepinephrine levels by 530%, significantly elevating alertness and focus.","source":"Søberg et al., 2021","source_url":"https://pubmed.ncbi.nlm.nih.gov/34298114/","impact_score":3,"accuracy_score":4,"relevance_score":4,"related_outcomes":["alertness","energy","mood"],"interesting_score":4}'::jsonb]
),
(
  'magnesium_glycinate',
  'magnesium-glycinate',
  'Magnesium Bisglycinate',
  'supplement',
  'Nervous System & Sleep',
  'active',
  'Magnesium (Sleep-focused)',
  'A highly bioavailable form of magnesium bound to the amino acid glycine, specifically used to promote relaxation and deeper sleep.',
  'Magnesium acts as a natural antagonist to the NMDA receptor and an agonist to GABA receptors, essentially quieting the central nervous system. The attached glycine molecule further acts as an inhibitory neurotransmitter. This combination helps lower core body temperature, reduce sleep latency, and improve the ratio of deep (slow-wave) sleep.',
  NULL,
  'Sleep Quality & Relaxation',
  NULL,
  3,
  NULL,
  NULL,
  '200-400mg',
  'Evening',
  'Daily',
  NULL,
  NULL,
  'low',
  'very_low',
  NULL,
  4,
  '3',
  NULL,
  'low_risk',
  NULL,
  ARRAY['Severe renal impairment', 'Myasthenia gravis'],
  ARRAY['sleep_quality', 'sleep_latency', 'stress'],
  ARRAY['Altered Intercellular Communication'],
  'NMDA receptor antagonism and GABA receptor agonizing.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Forms a synergistic sleep stack that targets multiple relaxation pathways simultaneously.","pairsWellWith":["l_theanine","apigenin"]}'::jsonb,
  '{"rationale":"Excessive concurrent intake of competing minerals can reduce absorption.","avoidCombiningWith":["high_dose_zinc"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"Magnesium supplementation is shown to significantly improve sleep efficiency and subjective sleep quality in elderly populations.","source":"Abbasi et al., 2012","source_url":"https://pubmed.ncbi.nlm.nih.gov/23853635/","impact_score":4,"accuracy_score":4,"relevance_score":4,"related_outcomes":["sleep_quality","stress"],"interesting_score":3}'::jsonb]
),
(
  'morning_sunlight',
  'morning-sunlight',
  'Morning Light Exposure',
  'light_exposure',
  'Circadian Alignment',
  'active',
  'Morning Sunlight (10-30m)',
  'Getting outside to view natural sunlight without sunglasses within 30-60 minutes of waking.',
  'Lux intensity from the sun (even on cloudy days) hits intrinsically photosensitive retinal ganglion cells (ipRGCs). These signal the suprachiasmatic nucleus (SCN) - the master clock in the brain. This triggers a healthy, early cortisol spike for alertness and sets a ~14-16 hour timer for melatonin release, anchoring the entire circadian rhythm.',
  NULL,
  'Circadian Anchoring & Alertness',
  NULL,
  5,
  NULL,
  NULL,
  '10-30 min',
  'Morning',
  'Daily',
  NULL,
  NULL,
  'free',
  'low',
  NULL,
  5,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY['Severe photosensitivity disorders'],
  ARRAY['alertness', 'energy', 'sleep_latency'],
  ARRAY['Altered Intercellular Communication'],
  'ipRGC signaling to the suprachiasmatic nucleus triggering circadian phase-setting.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Combining light with movement further amplifies the wakefulness signal.","pairsWellWith":["morning_walk","caffeine_delay"]}'::jsonb,
  '{"rationale":"Sunglasses heavily filter the specific lux intensity needed to trigger the circadian clock.","avoidCombiningWith":["sunglasses"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"Morning light exposure is the most powerful zeitgeber for the circadian system, directly regulating cortisol timing and melatonin onset.","source":"Huberman, 2021","source_url":"https://hubermanlab.com/using-light-for-health-and-performance/","impact_score":5,"accuracy_score":4,"relevance_score":5,"related_outcomes":["sleep_quality","alertness","energy"],"interesting_score":4}'::jsonb]
),
(
  'intermittent_fasting_16_8',
  'intermittent-fasting-16-8',
  'Time-Restricted Eating (16:8)',
  'fasting',
  'Metabolic Regulation',
  'active',
  '16:8 Fasting',
  'Compressing the daily eating window into 8 hours, followed by a 16-hour fasting period, consuming only zero-calorie fluids.',
  'Fasting lowers insulin levels, depleting liver glycogen stores and forcing the body to shift toward fatty acid oxidation. When sustained for 14-16 hours, mild AMPK activation occurs, mimicking low cellular energy states, and early stages of autophagy may initiate. It primarily improves metabolic flexibility, insulin sensitivity, and often results in effortless caloric restriction.',
  NULL,
  'Metabolic Flexibility & Fat Oxidation',
  NULL,
  4,
  NULL,
  NULL,
  '16 hours fasted',
  'Anytime',
  'Daily',
  NULL,
  NULL,
  'free',
  'medium',
  NULL,
  4,
  '3',
  NULL,
  'low_risk',
  NULL,
  ARRAY['History of eating disorders', 'Pregnancy', 'Type 1 Diabetes (without supervision)'],
  ARRAY['energy', 'satiety', 'brain_fog', 'digestive_comfort'],
  ARRAY['Deregulated Nutrient Sensing', 'Mitochondrial Dysfunction'],
  'Insulin suppression leading to glucagon elevation and lipid mobilization.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Fasted cardio maximizes fat oxidation rates since insulin is basally low.","pairsWellWith":["black_coffee","zone_2_cardio"]}'::jsonb,
  '{"rationale":"BCAAs (specifically leucine) will spike insulin and mTOR, breaking the fast.","avoidCombiningWith":["branched_chain_amino_acids"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"Time-restricted eating has been shown to improve markers of cardiometabolic health and insulin sensitivity in human clinical trials.","source":"de Cabo & Mattson, 2019","source_url":"https://www.nejm.org/doi/full/10.1056/NEJMra1905136","impact_score":4,"accuracy_score":4,"relevance_score":4,"related_outcomes":["energy","metabolic_health"],"interesting_score":4}'::jsonb]
),
(
  'acarbose',
  'acarbose',
  'Acarbose (With Meals)',
  'prescription_supported',
  'Metabolic Regulation',
  'active',
  'Acarbose',
  'An alpha-glucosidase inhibitor that slows the digestion of complex carbohydrates, reducing postprandial glucose spikes.',
  'By inhibiting enzymes in the brush border of the small intestines, Acarbose delays the breakdown of starch and disaccharides. This flattens the blood glucose curve after eating. In the ITP (Interventions Testing Program), Acarbose robustly extended the median and maximum lifespan of mice, potentially due to its ability to prevent hyperinsulinemia and modulate the gut microbiome through undigested starch delivery.',
  NULL,
  'Postprandial Glucose Blunting',
  NULL,
  5,
  NULL,
  NULL,
  '25-50mg',
  'Anytime',
  'With high-carb meals',
  NULL,
  NULL,
  'low',
  'low',
  NULL,
  4,
  '4',
  NULL,
  'moderate_risk',
  NULL,
  ARRAY['Inflammatory bowel disease', 'Severe renal impairment', 'Gastrointestinal obstruction'],
  ARRAY['digestive_comfort', 'energy'],
  ARRAY['Deregulated Nutrient Sensing', 'Altered Intercellular Communication'],
  'Competitive inhibition of intestinal alpha-glucosidases.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Can offset the glucose-intolerance side effects occasionally seen with rapamycin.","pairsWellWith":["rapamycin","high_carb_meals"]}'::jsonb,
  '{"rationale":"It does not block simple sugars like glucose or fructose effectively, and antacids may alter its efficacy.","avoidCombiningWith":["simple_sugars","antacids"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"Acarbose consistently extended lifespan in ITP studies, particularly in males, by reducing glycemic variability and insulin demand.","source":"Interventions Testing Program (ITP)","source_url":"https://pubmed.ncbi.nlm.nih.gov/24581403/","impact_score":4,"accuracy_score":4,"relevance_score":4,"related_outcomes":["longevity","metabolic_health"],"interesting_score":4}'::jsonb]
),
(
  'nad_precursors',
  'nad-precursors',
  'NAD+ Precursors (NMN / NR)',
  'supplement',
  'Cellular Energy & Repair',
  'active',
  'NMN / NR',
  'Supplementation with Nicotinamide Mononucleotide (NMN) or Nicotinamide Riboside (NR) to boost declining cellular NAD+ levels.',
  'NAD+ is a critical coenzyme for mitochondrial function and the primary fuel for Sirtuins (longevity-associated proteins involved in DNA repair and epigenome maintenance). NAD+ levels decline with age. Supplementing precursors via the salvage pathway reliably raises systemic NAD+ levels in human trials, though clinical functional outcomes remain actively debated in longevity science.',
  NULL,
  'NAD+ Restoration & Cellular Energy',
  NULL,
  3,
  NULL,
  NULL,
  '300-1000mg',
  'Morning',
  'Daily',
  NULL,
  NULL,
  'high',
  'very_low',
  NULL,
  2,
  '2',
  NULL,
  'low_risk',
  NULL,
  ARRAY['Active cancers (theoretical risk)'],
  ARRAY['energy', 'endurance', 'brain_fog'],
  ARRAY['Mitochondrial Dysfunction', 'Epigenetic Alterations', 'Genomic Instability'],
  'Enzymatic conversion via the salvage pathway to replenish intracellular NAD+ pools.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Sirtuins require NAD+ as fuel; providing both the activator and the fuel is hypothesized to be synergistic.","pairsWellWith":["resveratrol","sirtuin_activators"]}'::jsonb,
  '{"rationale":"High-dose niacin equivalents can deplete methyl pools; often paired with TMG.","avoidCombiningWith":["high_dose_methyl_donors_without_tmc"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"NR supplementation can increase NAD+ levels in human blood by 60-150% with minimal side effects.","source":"Trammell et al., 2016","source_url":"https://pubmed.ncbi.nlm.nih.gov/27322528/","impact_score":3,"accuracy_score":4,"relevance_score":3,"related_outcomes":["energy","cellular_health"],"interesting_score":3}'::jsonb]
),
(
  'resistance_training',
  'resistance-training',
  'Resistance Training / Hypertrophy',
  'exercise',
  'Physical Performance',
  'active',
  'Resistance Training (Heavy)',
  'Lifting weights or applying significant mechanical tension to muscles to stimulate strength and hypertrophic adaptations.',
  'Mechanical tension and metabolic stress activate the mTORC1 pathway in muscle tissue, leading to myofibrillar protein synthesis. Maintaining skeletal muscle mass is perhaps the most robust correlate with extended healthspan, acting as a massive glucose sink (preventing diabetes), protecting joints, and preventing frailty and sarcopenia in later decades.',
  NULL,
  'Muscle Mass & Bone Density',
  NULL,
  5,
  NULL,
  NULL,
  '3-6 sets per muscle group',
  'Anytime',
  '2-4x Weekly',
  NULL,
  NULL,
  'low',
  'high',
  NULL,
  5,
  '5',
  NULL,
  'moderate_risk',
  NULL,
  ARRAY['Unhealed acute injuries', 'Severe cardiovascular conditions'],
  ARRAY['strength', 'soreness', 'energy', 'sleep_quality'],
  ARRAY['Loss of Proteostasis', 'Deregulated Nutrient Sensing', 'Altered Intercellular Communication'],
  'mTORC1 activation via mechanotransduction.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Adequate leucine and energy surplus are required for robust MPS (muscle protein synthesis).","pairsWellWith":["protein_surfeit","creatine","sleep"]}'::jsonb,
  '{"rationale":"High-dose anti-inflammatories or cold exposure right after training bluntly suppresses the inflammatory signal required for muscle growth.","avoidCombiningWith":["nsaids","cold_plunge_immediate"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"Resistance training is the most potent intervention for maintaining muscle mass and functional independence in older adults.","source":"Westcott, 2012","source_url":"https://pubmed.ncbi.nlm.nih.gov/22777332/","impact_score":5,"accuracy_score":4,"relevance_score":5,"related_outcomes":["strength","longevity","metabolic_health"],"interesting_score":3}'::jsonb]
),
(
  'dexa_scan',
  'dexa-scan',
  'Dual-Energy X-ray Absorptiometry (DEXA)',
  'diagnostic_test',
  'Diagnostics & Tracking',
  'active',
  'DEXA Scan (Body Comp)',
  'A medical imaging test that uses very low-dose X-rays to precisely measure bone density, lean muscle mass, and body fat percentage.',
  'DEXA provides the gold-standard measurement for regional body composition. Unlike bioelectrical impedance scales, DEXA accurately distinguishes between visceral fat (highly inflammatory, linked to metabolic disease) and subcutaneous fat. It also tracks appendicular lean mass index (ALMI) to ensure resistance training protocols are actually preventing sarcopenia.',
  NULL,
  'Accurate Body Composition Tracking',
  NULL,
  2,
  NULL,
  NULL,
  '1 Scan',
  'Anytime',
  '1-2x Annually',
  NULL,
  NULL,
  'premium',
  'very_low',
  NULL,
  5,
  '5',
  NULL,
  'low_risk',
  NULL,
  ARRAY['Pregnancy'],
  ARRAY[]::text[],
  ARRAY['Altered Intercellular Communication'],
  'Differential attenuation of two X-ray beams by bone and soft tissue.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Use to ensure weight loss is from adipose tissue and not valuable lean muscle mass.","pairsWellWith":["resistance_training","caloric_deficit"]}'::jsonb,
  '{"rationale":"While radiation is extremely low, scans more frequent than every 3-6 months offer little signal-to-noise benefit.","avoidCombiningWith":["frequent_scans"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"DEXA scans allow for precise monitoring of visceral fat reduction, which is a key marker for metabolic health and chronic disease risk.","source":"Bjorntorp, 1993","source_url":"https://pubmed.ncbi.nlm.nih.gov/8354727/","impact_score":4,"accuracy_score":4,"relevance_score":4,"related_outcomes":["metabolic_health","longevity"],"interesting_score":3}'::jsonb]
),
(
  'continuous_glucose_monitor',
  'continuous-glucose-monitor',
  'Continuous Glucose Monitor (CGM)',
  'diagnostic_test',
  'Diagnostics & Tracking',
  'active',
  'CGM (14-Day Wear)',
  'A small wearable biosensor inserted subcutaneously to measure interstitial glucose levels in real-time.',
  'CGMs provide immediate biofeedback on how specific foods, stress, sleep, and exercise impact blood glucose. This allows users to completely personalize their diet by identifying hidden glucose spikes. Minimizing glycemic variability and AUC (area under the curve) reduces the formation of Advanced Glycation End-products (AGEs) and preserves pancreatic beta-cell function over the lifespan.',
  NULL,
  'Glycemic Variability Reduction',
  NULL,
  4,
  NULL,
  NULL,
  'Continuous',
  'Anytime',
  '14-day wear',
  NULL,
  NULL,
  'premium',
  'low',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY['Severe skin allergies to adhesives'],
  ARRAY['energy', 'satiety', 'brain_fog'],
  ARRAY['Deregulated Nutrient Sensing', 'Mitochondrial Dysfunction'],
  'Electrochemical detection of glucose via glucose oxidase in interstitial fluid.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Provides instant proof of how movement acts as an immediate glucose sink.","pairsWellWith":["post_meal_walks","zone_2_cardio"]}'::jsonb,
  '{"rationale":"High doses of Vitamin C can chemically interfere with the sensor reading, falsely elevating the glucose metric.","avoidCombiningWith":["vitamin_c_high_dose"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"Wearing a CGM and keeping postprandial glucose spikes below 140 mg/dL is correlated with a significant reduction in microvascular and macrovascular complications in the long term.","source":"ADA Standards of Medical Care in Diabetes","source_url":"https://diabetesjournals.org/care/issue/44/Supplement_1","impact_score":4,"accuracy_score":4,"relevance_score":4,"related_outcomes":["longevity","energy","metabolic_health"],"interesting_score":3}'::jsonb]
),
(
  'l_theanine',
  'l-theanine',
  'L-Theanine (100-200mg)',
  'supplement',
  'Nervous System & Sleep',
  'active',
  'L-Theanine',
  'An amino acid found primarily in green tea that promotes relaxation without drowsiness by increasing alpha brain waves and GABA levels.',
  'L-Theanine crosses the blood-brain barrier and antagonizes glutamate receptors while simultaneously boosting GABA, serotonin, and dopamine. This dual action blunts the jittery, sympathetic nervous system spikes caused by caffeine, while creating a state of "calm focus". Taken at night, it reduces sleep latency and anxiety-induced racing thoughts.',
  NULL,
  'Calm Focus & Sleep Latency',
  NULL,
  2,
  NULL,
  NULL,
  '100-200mg',
  'Morning or Evening',
  'Daily or As needed',
  NULL,
  NULL,
  'low',
  'very_low',
  NULL,
  4,
  '3',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['focus', 'stress', 'sleep_latency'],
  ARRAY['Altered Intercellular Communication'],
  'Glutamate receptor antagonist and GABA upregulator.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Creates the ultimate 1:2 ratio with caffeine for flow state, or synergizes with magnesium for deep sleep.","pairsWellWith":["caffeine","magnesium_glycinate","apigenin"]}'::jsonb,
  '{"rationale":"May excessively compound the effects of prescription sleep aids or heavy sedatives.","avoidCombiningWith":["sedatives"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"A randomized controlled trial demonstrated that L-theanine supplementation improved objective sleep quality, sleep efficiency, and reduced perceived stress by increasing alpha brainwave activity.","source":"Lyon et al., 2011","source_url":"https://pubmed.ncbi.nlm.nih.gov/22214254/","impact_score":3,"accuracy_score":5,"relevance_score":4,"related_outcomes":["sleep_quality","cognitive_health","stress_reduction"],"interesting_score":4}'::jsonb]
),
(
  'apigenin',
  'apigenin',
  'Apigenin (50mg)',
  'supplement',
  'Nervous System & Sleep',
  'active',
  'Apigenin',
  'A flavonoid found in high concentrations in chamomile tea, acting as a mild sedative and anxiolytic.',
  'Apigenin binds to benzodiazepine receptors in the brain (specifically the GABA-A receptor), promoting relaxation and sleep transition without the addictive profile of pharmaceutical benzodiazepines. It is a core component of the Huberman sleep stack, assisting specifically in the transition phase of falling asleep.',
  NULL,
  'Sleep Transition',
  NULL,
  2,
  NULL,
  NULL,
  '50mg',
  'Evening',
  'Daily',
  NULL,
  NULL,
  'medium',
  'very_low',
  NULL,
  3,
  '2',
  NULL,
  'low_risk',
  NULL,
  ARRAY['Hormone-sensitive conditions'],
  ARRAY['sleep_latency', 'stress'],
  ARRAY['Altered Intercellular Communication'],
  'GABA-A receptor agonist.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Completes the trifecta of non-hormonal sleep initiation.","pairsWellWith":["magnesium_glycinate","l_theanine"]}'::jsonb,
  '{"rationale":"Apigenin is a mild aromatase inhibitor and may interact with hormonal therapies.","avoidCombiningWith":["high_dose_estrogen"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"While isolated apigenin lacks large human trials, chamomile extract (which is rich in apigenin) has been shown in clinical trials to significantly reduce symptoms of generalized anxiety disorder, potentially through GABA-A receptor modulation.","source":"Amsterdam et al., 2009","source_url":"https://pubmed.ncbi.nlm.nih.gov/19593179/","impact_score":3,"accuracy_score":4,"relevance_score":3,"related_outcomes":["sleep_quality","anxiety_reduction"],"interesting_score":3}'::jsonb]
),
(
  'berberine',
  'berberine',
  'Berberine (500mg)',
  'supplement',
  'Metabolic Regulation',
  'active',
  'Berberine',
  'A bioactive alkaloid extracted from several plants, acting as a potent over-the-counter glucose disposal agent.',
  'Berberine is often referred to as "OTC Metformin." It activates AMPK, reduces hepatic gluconeogenesis, and increases glucose uptake into muscle cells. Clinical trials have shown its efficacy in lowering HbA1c and fasting blood glucose is nearly identical to metformin, making it an excellent alternative for those seeking metabolic regulation without a prescription.',
  NULL,
  'Glucose Regulation',
  NULL,
  4,
  NULL,
  NULL,
  '500-1500mg',
  'Anytime',
  'With meals',
  NULL,
  NULL,
  'medium',
  'very_low',
  NULL,
  4,
  '4',
  NULL,
  'moderate_risk',
  NULL,
  ARRAY['Pregnancy', 'Concurrent use with other hypoglycemic agents'],
  ARRAY['energy', 'brain_fog'],
  ARRAY['Deregulated Nutrient Sensing'],
  'AMPK activation and alteration of gut microbiota.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Should be taken exactly prior to or alongside a carbohydrate load for maximum effect.","pairsWellWith":["carbohydrate_meals"]}'::jsonb,
  '{"rationale":"Combining with Metformin can cause severe hypoglycemia. It inhibits CYP3A4, altering drug metabolism.","avoidCombiningWith":["metformin","macrolide_antibiotics"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"Multiple meta-analyses show that Berberine (1500 mg daily) is statistically as effective as Metformin at lowering HbA1c and fasting blood glucose in patients with type 2 diabetes.","source":"Lan et al., 2015","source_url":"https://pubmed.ncbi.nlm.nih.gov/25498346/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["metabolic_health","longevity"],"interesting_score":4}'::jsonb]
),
(
  'ashwagandha_ksm66',
  'ashwagandha-ksm66',
  'Ashwagandha (KSM-66)',
  'supplement',
  'Nervous System & Sleep',
  'active',
  'Ashwagandha',
  'A powerful adaptogenic herb shown to significantly lower baseline cortisol and subjective stress.',
  'Ashwagandha modulates the HPA (Hypothalamic-Pituitary-Adrenal) axis, buffering the release of cortisol in response to stress. The KSM-66 extract specifically has dozens of human trials showing massive reductions in serum cortisol (up to 30%). It is best cycled (e.g., 4 weeks on, 2 weeks off) to prevent anhedonia resulting from completely blunted cortisol curves.',
  NULL,
  'Cortisol Reduction',
  NULL,
  3,
  NULL,
  NULL,
  '300-600mg',
  'Evening',
  'Cycled',
  NULL,
  NULL,
  'medium',
  'very_low',
  NULL,
  4,
  '4',
  NULL,
  'moderate_risk',
  NULL,
  ARRAY['Hyperthyroidism', 'Autoimmune conditions'],
  ARRAY['stress', 'sleep_quality', 'mood'],
  ARRAY['Altered Intercellular Communication'],
  'HPA axis modulation and GABA-mimetic activity.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Stacks well in the evening for profound systemic relaxation.","pairsWellWith":["magnesium_glycinate"]}'::jsonb,
  '{"rationale":"Should not be taken continuously year-round without breaks due to risks of emotional blunting/anhedonia.","avoidCombiningWith":["continuous_long_term_use"]}'::jsonb,
  NULL,
  NULL
),
(
  'rhodiola_rosea',
  'rhodiola-rosea',
  'Rhodiola Rosea (3% Salidroside)',
  'supplement',
  'Physical Performance',
  'active',
  'Rhodiola Rosea',
  'An adaptogen that prevents fatigue and maintains cognitive performance under physical or mental exhaustion.',
  'Unlike Ashwagandha which relaxes, Rhodiola is highly stimulating. It influences the release and reuptake of monoamines (dopamine, serotonin, norepinephrine) and reduces the perception of fatigue during intense exercise or sleep deprivation. It is an excellent pre-workout alternative for those trying to cycle off caffeine.',
  NULL,
  'Fatigue Resistance',
  NULL,
  2,
  NULL,
  NULL,
  '200-400mg',
  'Morning',
  'As needed',
  NULL,
  NULL,
  'medium',
  'very_low',
  NULL,
  3,
  '3',
  NULL,
  'low_risk',
  NULL,
  ARRAY['Bipolar disorder (may trigger mania)'],
  ARRAY['energy', 'endurance', 'focus'],
  ARRAY['Altered Intercellular Communication'],
  'MAO inhibition and stimulation of monoamine receptors.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Amplifies power output and endurance when taken 30 mins before training.","pairsWellWith":["resistance_training","creatine"]}'::jsonb,
  '{"rationale":"Will absolutely cause insomnia if taken late. Mild risk of serotonin syndrome if combined with high-dose SSRIs.","avoidCombiningWith":["evening_use","ssri_medications"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"A systematic review of clinical trials confirms Rhodiola rosea significantly reduces symptoms of burnout and chronic fatigue syndrome within the first week of daily supplementation.","source":"Kasper et al., 2017","source_url":"https://pubmed.ncbi.nlm.nih.gov/28219059/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["energy","stress","endurance"],"interesting_score":4}'::jsonb]
),
(
  'glycine_3g',
  'glycine-3g',
  'Glycine (3g)',
  'supplement',
  'Nervous System & Sleep',
  'active',
  'Glycine (Sleep)',
  'An inhibitory amino acid that actively drops core body temperature to facilitate deeper sleep.',
  'Glycine acts as a neurotransmitter in the central nervous system. When taken in a 3g dose before bed, it increases blood flow to the extremities, effectively pulling heat away from the core. A dropping core body temperature is a strict biological requirement to enter slow-wave (deep) sleep. It also blunts the subjective feeling of fatigue the next morning if sleep is restricted.',
  NULL,
  'Core Temperature Drop & Deep Sleep',
  NULL,
  3,
  NULL,
  NULL,
  '3g',
  'Evening',
  'Daily',
  NULL,
  NULL,
  'low',
  'very_low',
  NULL,
  4,
  '3',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['sleep_quality', 'waking_restedness'],
  ARRAY['Altered Intercellular Communication'],
  'NMDA receptor co-agonist and peripheral vasodilator.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Magnesium bisglycinate already contains glycine; taking extra pure glycine maxes out the cooling effect.","pairsWellWith":["magnesium_bisglycinate","cold_bedroom"]}'::jsonb,
  '{"rationale":"Can interfere with the efficacy of certain antipsychotics.","avoidCombiningWith":["clozapine"]}'::jsonb,
  NULL,
  NULL
),
(
  'zone_2_cardio',
  'zone-2-cardio',
  'Zone 2 Cardiovascular Training',
  'exercise',
  'Physical Performance',
  'active',
  'Zone 2 Cardio (45+ min)',
  'Steady-state aerobic exercise performed at an intensity where lactate clearance matches lactate production (typically 60-70% of max heart rate).',
  'Zone 2 training specifically stimulates mitochondrial biogenesis and improves fat oxidation capacity (metabolic flexibility). By maintaining a workload just below the first ventilatory threshold (VT1), type I (slow-twitch) muscle fibers are maximally recruited. This leads to increased mitochondrial density, improved systemic insulin sensitivity, and robust cardiovascular health (reduced ApoB and resting HR) with very low systemic stress.',
  NULL,
  'Mitochondrial Efficiency',
  NULL,
  5,
  NULL,
  NULL,
  '45-60 min @ 60-70% Max HR',
  'Morning / Pre-meal',
  '3-4x Weekly',
  NULL,
  NULL,
  'free',
  'high',
  NULL,
  5,
  '5',
  NULL,
  'low_risk',
  NULL,
  ARRAY['Acute illness or fever', 'Unstable cardiovascular conditions'],
  ARRAY['endurance', 'energy', 'sleep_quality', 'soreness'],
  ARRAY['Mitochondrial Dysfunction', 'Altered Intercellular Communication', 'Deregulated Nutrient Sensing'],
  'Mechanical stress and calcium influx leading to PGC-1α upregulation.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Omega-3s can improve red blood cell deformability and oxygen delivery, while creatine assists with intermittent higher output bursts.","pairsWellWith":["creatine","epa_dha"]}'::jsonb,
  '{"rationale":"High-dose Vitamin C or E immediately post-exercise blunts the ROS-mediated signaling required for mitochondrial adaptation.","avoidCombiningWith":["high_dose_antioxidants"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"High cardiorespiratory fitness (VO2 max) is associated with a 500% reduction in all-cause mortality over a decade compared to low fitness.","source":"Mandsager et al., 2018 (JAMA)","source_url":"https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2707428","impact_score":4,"accuracy_score":4,"relevance_score":4,"related_outcomes":["longevity","endurance","energy"],"interesting_score":4}'::jsonb]
),
(
  'epa_dha_omega3',
  'epa-dha-omega3',
  'EPA/DHA Omega-3 Fatty Acids',
  'supplement',
  'Inflammation & Lipids',
  'active',
  'High-Dose EPA/DHA',
  'Essential long-chain polyunsaturated fatty acids primarily found in marine oils, critical for resolving inflammation and maintaining cell membrane fluidity.',
  'EPA and DHA integrate into cellular phospholipid membranes, directly altering membrane dynamics and serving as precursors for Specialized Pro-resolving Mediators (SPMs) like resolvins and protectins. High-dose EPA specifically competes with arachidonic acid to reduce inflammatory eicosanoids. The REDUCE-IT trial demonstrated significant cardiovascular risk reduction using high-dose purified EPA.',
  NULL,
  'Systemic Inflammation Reduction',
  NULL,
  4,
  NULL,
  NULL,
  '2g EPA / 1g DHA',
  'With largest fat meal',
  'Daily',
  NULL,
  NULL,
  'medium',
  'low',
  NULL,
  5,
  '3',
  NULL,
  'low_risk',
  NULL,
  ARRAY['Active bleeding disorders', 'Scheduled surgery within 7 days'],
  ARRAY['focus', 'brain_fog', 'mood'],
  ARRAY['Altered Intercellular Communication', 'Chronic Inflammation'],
  'Precursors to resolving lipid mediators and PPAR-alpha activators (ChEMBL: CHEMBL1201502).',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Lipid-soluble compounds require bile acids for optimal intestinal absorption.","pairsWellWith":["vitamin_d","fat_containing_meal"]}'::jsonb,
  '{"rationale":"Extremely high doses of Omega-3s can prolong bleeding time, interacting with warfarin or novel oral anticoagulants (NOACs).","avoidCombiningWith":["high_dose_blood_thinners"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"In the REDUCE-IT trial, high-dose EPA significantly reduced the risk of major adverse cardiovascular events by 25%.","source":"Bhatt et al., 2019 (NEJM)","source_url":"https://www.nejm.org/doi/full/10.1056/nejmoa1812792","impact_score":4,"accuracy_score":4,"relevance_score":4,"related_outcomes":["longevity","cardiovascular_health"],"interesting_score":3}'::jsonb]
),
(
  'sauna_exposure',
  'sauna-exposure',
  'Hyperthermic Conditioning (Sauna)',
  'heat_exposure',
  'Environmental Stress',
  'active',
  'Sauna (80°C+ for 20m)',
  'Passive heat exposure, typically involving sitting in a dry or steam room at high temperatures to elevate core body temperature.',
  'Thermal stress activates Heat Shock Factor 1 (HSF1), which upregulates Heat Shock Proteins (HSPs) like HSP70. These proteins act as molecular chaperones, refolding damaged proteins and preventing protein aggregation. Furthermore, the cardiovascular demand of cooling the body mimics moderate aerobic exercise, significantly improving endothelial function and reducing blood pressure. Finnish cohort studies show a strong dose-dependent reduction in sudden cardiac death and all-cause mortality.',
  NULL,
  'Cardiovascular Health',
  NULL,
  4,
  NULL,
  NULL,
  '20 min @ 80°C+',
  'Evening / Post-workout',
  '4-7x Weekly',
  NULL,
  NULL,
  'medium',
  'medium',
  NULL,
  5,
  '4',
  NULL,
  'moderate_risk',
  NULL,
  ARRAY['Severe aortic stenosis', 'Recent myocardial infarction', 'Pregnancy (first trimester)', 'Alcohol intoxication'],
  ARRAY['sleep_quality', 'sleep_latency', 'stress'],
  ARRAY['Loss of Proteostasis', 'Altered Intercellular Communication'],
  'FOXO3 and Heat Shock Protein (HSP) induction via acute thermal stress.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Contrast therapy (hot/cold) may enhance vascular compliance, though the specific order dictates the autonomic nervous system response.","pairsWellWith":["cold_plunge","hydration"]}'::jsonb,
  '{"rationale":"Alcohol drastically increases the risk of hypotension, arrhythmias, and sudden death during sauna use.","avoidCombiningWith":["alcohol","anticholinergic_drugs"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"Men using a sauna 4-7 times per week had a 50% lower risk of fatal cardiovascular disease compared to those using it once a week.","source":"Laukkanen et al., 2015 (JAMA Internal Medicine)","source_url":"https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/2130724","impact_score":4,"accuracy_score":4,"relevance_score":4,"related_outcomes":["longevity","stress","cardiovascular_health"],"interesting_score":4}'::jsonb]
),
(
  'spermidine_supplement',
  'spermidine-supplement',
  'Spermidine Supplementation',
  'supplement',
  'Cellular Cleanup',
  'active',
  'Spermidine Extract',
  'A naturally occurring polyamine that induces autophagy, the body''s cellular recycling process, to clear out damaged proteins and organelles.',
  'Spermidine acts by inhibiting the acetyltransferase EP300, which in turn leads to the deacetylation of various autophagy-related proteins. This molecular cascade stimulates macroautophagy, effectively acting as an endogenous caloric restriction mimetic. In human cohorts, higher dietary spermidine intake correlates with reduced cardiovascular and all-cause mortality.',
  NULL,
  'Autophagy Upregulation',
  NULL,
  3,
  NULL,
  NULL,
  '1-2mg pure spermidine',
  'Evening / Fasted',
  'Daily',
  NULL,
  NULL,
  'high',
  'low',
  NULL,
  3,
  '3',
  NULL,
  'low_risk',
  NULL,
  ARRAY['Unknown interactions during active chemotherapy'],
  ARRAY['sleep_quality', 'waking_restedness', 'energy'],
  ARRAY['Loss of Proteostasis', 'Cellular Senescence', 'Mitochondrial Dysfunction'],
  'EP300 inhibition resulting in increased LC3-dependent autophagy.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Combines synergistically with other physiological autophagy inducers.","pairsWellWith":["fasting","exercise"]}'::jsonb,
  '{"rationale":"High amino acid intake (especially leucine) activates mTORC1, which potently inhibits autophagy.","avoidCombiningWith":["mTOR_activators","high_protein_meals"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"Higher dietary spermidine intake is linked to a lower risk of all-cause mortality, equating to a 5.7-year increase in life expectancy in a human cohort.","source":"Kiechl et al., 2018","source_url":"https://pubmed.ncbi.nlm.nih.gov/29955838/","impact_score":3,"accuracy_score":3,"relevance_score":4,"related_outcomes":["longevity","cellular_health"],"interesting_score":4}'::jsonb]
),
(
  'rapamycin_weekly',
  'rapamycin-weekly',
  'Rapamycin (Sirolimus) Weekly',
  'prescription_supported',
  'Longevity Pharmacotherapy',
  'active',
  'Rapamycin (Weekly Pulse)',
  'A macrolide compound that acts as a specific inhibitor of mTOR (mechanistic target of rapamycin), currently considered the most robust pharmacological lifespan-extending intervention in mammalian models.',
  'Rapamycin binds to FKBP12 to inhibit the mTORC1 complex. By suppressing mTORC1, it mimics the effects of fasting and caloric restriction, powerfully upregulating autophagy (cellular cleanup), reducing protein translation errors, and delaying multiple age-related functional declines. A weekly pulsed dose is hypothesized to maximize longevity benefits while minimizing the immunosuppression seen with daily dosing.',
  NULL,
  'Cellular Senescence Reduction',
  NULL,
  5,
  NULL,
  NULL,
  '5-8mg',
  'Morning',
  'Once Weekly',
  NULL,
  NULL,
  'premium',
  'low',
  NULL,
  4,
  '5',
  NULL,
  'moderate_risk',
  NULL,
  ARRAY['Active infections', 'History of poor wound healing', 'Immunocompromised status', 'Pregnancy'],
  ARRAY['energy', 'brain_fog', 'digestive_comfort'],
  ARRAY['Deregulated Nutrient Sensing', 'Loss of Proteostasis', 'Cellular Senescence', 'Altered Intercellular Communication'],
  'mTORC1 specific allosteric inhibitor (ChEMBL: CHEMBL1201140)',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Combining with AMPK activators may mitigate rapamycin-induced glucose intolerance and insulin resistance by upregulating mTORC2-independent glucose uptake pathways.","pairsWellWith":["metformin","acarbose"]}'::jsonb,
  '{"rationale":"CYP3A4 inhibitors dramatically increase rapamycin bioavailability, raising risk of toxicity and immunosuppression.","avoidCombiningWith":["grapefruit juice","ketoconazole"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"Increases median lifespan by up to 26% in female mice and 23% in male mice when started late in life.","source":"Interventions Testing Program (ITP)","source_url":"https://pubmed.ncbi.nlm.nih.gov/19587680/","impact_score":4,"accuracy_score":4,"relevance_score":4,"related_outcomes":["longevity"],"interesting_score":4}'::jsonb]
),
(
  'metformin_daily',
  'metformin-daily',
  'Metformin',
  'prescription_supported',
  'Metabolic Regulation',
  'active',
  'Metformin (Daily)',
  'A first-line oral antidiabetic medication that improves insulin sensitivity and has been observationally linked to reduced all-cause mortality in type 2 diabetics compared to matched non-diabetics.',
  'Metformin primarily acts on the liver to decrease hepatic glucose production. It mildly inhibits mitochondrial Complex I, altering the AMP/ATP ratio, which activates AMPK. This systemic metabolic shift mimics energy scarcity, leading to improved insulin sensitivity and reduced advanced glycation end-products (AGEs). The TAME (Targeting Aging with Metformin) trial is evaluating its clinical efficacy for lifespan extension in non-diabetics.',
  NULL,
  'Glucose Regulation',
  NULL,
  4,
  NULL,
  NULL,
  '500-1000mg',
  'With meals',
  '2x Daily',
  NULL,
  NULL,
  'low',
  'low',
  NULL,
  4,
  '3',
  NULL,
  'moderate_risk',
  NULL,
  ARRAY['Severe renal impairment (eGFR < 30)', 'Lactic acidosis risk', 'Vitamin B12 deficiency'],
  ARRAY['energy', 'satiety', 'digestive_comfort'],
  ARRAY['Deregulated Nutrient Sensing', 'Mitochondrial Dysfunction'],
  'AMPK activator via mitochondrial complex I inhibition (ChEMBL: CHEMBL1431)',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:29:25.064612+00:00',
  '{"rationale":"Synergistic activation of AMPK and suppression of mTOR.","pairsWellWith":["berberine","rapamycin"]}'::jsonb,
  '{"rationale":"Taking metformin immediately prior to exercise may blunt peak aerobic adaptations and mitochondrial remodeling.","avoidCombiningWith":["zone_2_cardio_immediate"]}'::jsonb,
  NULL,
  ARRAY['{"fact":"In a large observational study, diabetics on metformin lived 15% longer than matched non-diabetic controls.","source":"Bannister et al., 2014","source_url":"https://pubmed.ncbi.nlm.nih.gov/25041462/","impact_score":3,"accuracy_score":3,"relevance_score":4,"related_outcomes":["longevity","energy"],"interesting_score":4}'::jsonb]
),
(
  'astaxanthin',
  'astaxanthin',
  'Astaxanthin',
  'supplement',
  'Biochemistry',
  'active',
  'Astaxanthin',
  'A health and longevity modality focused on cellular_health.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'cellular_health',
  NULL,
  3,
  NULL,
  NULL,
  '4-12mg',
  'With Fats',
  'Daily',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['cellular_health', 'endurance', 'skin_health'],
  ARRAY[]::text[],
  'A unique carotenoid that physically spans the lipid bilayer of cell membranes, providing superior protection against mitochondrial lipid peroxidation.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:53:22.144956+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"Astaxanthin is a uniquely structured carotenoid that spans the mitochondrial membrane. Clinical trials show it reduces systemic oxidative stress biomarkers (like MDA) by over 30% in athletes.","source":"Fassett et al., 2012","source_url":"https://pubmed.ncbi.nlm.nih.gov/22214255/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["cellular_health","endurance","skin_health"],"interesting_score":4}'::jsonb]
),
(
  'urolithin_a',
  'urolithin_a',
  'Urolithin A',
  'supplement',
  'Biochemistry',
  'active',
  'Urolithin A',
  'A health and longevity modality focused on muscle_health and energy and longevity.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'muscle_health',
  NULL,
  4,
  NULL,
  NULL,
  '500-1000mg',
  'Morning',
  'Daily',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  3,
  '3',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['muscle_health', 'energy', 'longevity'],
  ARRAY['Altered intercellular communication'],
  'A postbiotic compound that specifically triggers mitophagy, the selective clearing of dysfunctional mitochondria, thereby improving muscle endurance.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:48:25.879193+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"A randomized controlled trial showed that 4 months of Urolithin A supplementation improved muscle strength by approximately 12% and increased aerobic endurance (peak VO2) in middle-aged adults.","source":"Singh et al., 2022","source_url":"https://pubmed.ncbi.nlm.nih.gov/35584623/","impact_score":4,"accuracy_score":5,"relevance_score":5,"related_outcomes":["muscle_health","energy","longevity"],"interesting_score":4}'::jsonb]
),
(
  'glp_1_receptor_agonists',
  'glp_1_receptor_agonists',
  'GLP-1 Receptor Agonists',
  'supplement',
  'Biochemistry',
  'active',
  'GLP-1 Receptor Agonists',
  'A health and longevity modality focused on cardiovascular_health and metabolic_health and longevity.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'cardiovascular_health',
  NULL,
  5,
  NULL,
  NULL,
  '0.25 - 2.4mg',
  'Anytime',
  'Weekly',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  3,
  '3',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['cardiovascular_health', 'metabolic_health', 'longevity'],
  ARRAY['Altered intercellular communication'],
  'Agonizes the GLP-1 receptor, delaying gastric emptying and increasing satiety signals to the brain.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:48:25.879193+00:00',
  '{"rationale":"Mitigates the lean muscle mass loss typically seen with GLP-1 induced weight loss.","pairsWellWith":["resistance_training"]}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"In the SELECT trial, semaglutide (2.4 mg) was associated with a 20% reduction in the risk of major adverse cardiovascular events (Hazard Ratio 0.80) in adults with overweight or obesity and established cardiovascular disease.","source":"Lincoff et al., 2023","source_url":"https://pubmed.ncbi.nlm.nih.gov/37952131/","impact_score":5,"accuracy_score":5,"relevance_score":5,"related_outcomes":["cardiovascular_health","metabolic_health","longevity"],"interesting_score":5}'::jsonb]
),
(
  'melatonin',
  'melatonin',
  'Melatonin',
  'supplement',
  'Biochemistry',
  'active',
  'Melatonin',
  'A health and longevity modality focused on sleep_quality.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'sleep_quality',
  NULL,
  3,
  NULL,
  NULL,
  '0.3 - 3.0mg',
  '30m before bed',
  'Daily',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['sleep_quality', 'longevity', 'cellular_health'],
  ARRAY[]::text[],
  'Acts as a potent mitochondrial antioxidant and circadian rhythm anchor.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:53:22.144956+00:00',
  '{"rationale":"Enhances sleep initiation and architecture.","pairsWellWith":["magnesium_glycinate"]}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"Beyond sleep, melatonin acts as a potent mitochondrial antioxidant. Animal studies suggest chronic melatonin administration reduces oxidative stress markers by up to 40% in aging brains.","source":"Reiter et al., 2016","source_url":"https://pubmed.ncbi.nlm.nih.gov/27500468/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["sleep_quality","longevity","cellular_health"],"interesting_score":4}'::jsonb]
),
(
  'continuous_ketone_monitors',
  'continuous_ketone_monitors',
  'Continuous Ketone Monitors',
  'diagnostic_test',
  'Physical',
  'active',
  'Continuous Ketone Monitors',
  'A health and longevity modality focused on metabolic_health.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'metabolic_health',
  NULL,
  3,
  NULL,
  NULL,
  'Continuous',
  'Anytime',
  '14-day wear',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['metabolic_health', 'energy', 'focus'],
  ARRAY[]::text[],
  'Provides real-time feedback on systemic beta-hydroxybutyrate levels.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:53:22.144956+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"Continuous tracking of beta-hydroxybutyrate allows individuals to precisely dial in their dietary and fasting interventions, ensuring metabolic flexibility and preventing the ''keto flu'' dropout rate.","source":"Buga et al., 2021","source_url":"https://pubmed.ncbi.nlm.nih.gov/33562479/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["metabolic_health","energy","focus"],"interesting_score":4}'::jsonb]
),
(
  'sleep_consistency',
  'sleep_consistency',
  'Sleep Consistency',
  'habit',
  'Physical',
  'active',
  'Sleep Consistency',
  'A health and longevity modality focused on sleep_quality.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'sleep_quality',
  NULL,
  5,
  NULL,
  NULL,
  'Targeted Bedtime',
  'Same time +/- 30m',
  'Nightly',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['sleep_quality', 'metabolic_health', 'longevity'],
  ARRAY[]::text[],
  'Entrains the suprachiasmatic nucleus, optimizing the cortisol/melatonin axis.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:53:22.144956+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"A 2023 cohort study of over 60,000 adults found that high sleep regularity (sleeping and waking at the exact same time) was a stronger predictor of reduced all-cause mortality than sleep duration itself.","source":"Windred et al., 2023","source_url":"https://pubmed.ncbi.nlm.nih.gov/37678500/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["sleep_quality","metabolic_health","longevity"],"interesting_score":4}'::jsonb]
),
(
  'quercetin',
  'quercetin',
  'Quercetin',
  'supplement',
  'Biochemistry',
  'active',
  'Quercetin',
  'A health and longevity modality focused on cellular_aging.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'cellular_aging',
  NULL,
  3,
  NULL,
  NULL,
  '500-1000mg',
  'With Meals',
  'Cycled',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['cellular_aging', 'longevity', 'cardiovascular_health'],
  ARRAY[]::text[],
  'Acts as a senolytic and powerful flavonoid antioxidant.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:53:22.144956+00:00',
  '{"rationale":"Creates a broad-spectrum senolytic cocktail capable of clearing multiple senescent cell types.","pairsWellWith":["dasatinib","fisetin"]}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"When paired with Dasatinib, Quercetin is a powerful senolytic. The combination has been shown in human trials to significantly reduce senescent cell burden in adipose tissue within just 11 days.","source":"Hickson et al., 2019","source_url":"https://pubmed.ncbi.nlm.nih.gov/31542391/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["cellular_aging","longevity","cardiovascular_health"],"interesting_score":4}'::jsonb]
),
(
  'whole_body_mri',
  'whole_body_mri',
  'Whole Body MRI',
  'diagnostic_test',
  'Physical',
  'active',
  'Whole Body MRI',
  'A health and longevity modality focused on longevity.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'longevity',
  NULL,
  4,
  NULL,
  NULL,
  '1 Scan',
  'Anytime',
  'Every 1-3 Years',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['longevity', 'peace_of_mind'],
  ARRAY[]::text[],
  'Non-ionizing radiation imaging for early detection of solid tumors and aneurysms.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:53:22.144956+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"Proactive whole-body MRI screening in asymptomatic populations identifies clinically significant early-stage cancers or aneurysms in approximately 2-5% of individuals, drastically improving survival rates.","source":"Tirumani et al., 2021","source_url":"https://pubmed.ncbi.nlm.nih.gov/34323621/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["longevity","peace_of_mind"],"interesting_score":4}'::jsonb]
),
(
  'nmn',
  'nmn',
  'NMN',
  'supplement',
  'Biochemistry',
  'active',
  'NMN',
  'A health and longevity modality focused on energy.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'energy',
  NULL,
  3,
  NULL,
  NULL,
  '250-1000mg',
  'Morning',
  'Daily',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['energy', 'metabolic_health', 'longevity'],
  ARRAY[]::text[],
  'A direct precursor to NAD+, bypassing the NAMPT bottleneck to increase cellular energy.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:53:22.144956+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"A 12-week randomized controlled trial in humans showed that 250 mg of daily NMN supplementation significantly improved skeletal muscle insulin sensitivity and signaling in prediabetic women.","source":"Yoshino et al., 2021","source_url":"https://pubmed.ncbi.nlm.nih.gov/33888596/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["energy","metabolic_health","longevity"],"interesting_score":4}'::jsonb]
),
(
  'biological_age_testing',
  'biological_age_testing',
  'Biological Age Testing',
  'diagnostic_test',
  'Physical',
  'active',
  'Biological Age Testing',
  'A health and longevity modality focused on longevity.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'longevity',
  NULL,
  3,
  NULL,
  NULL,
  '1 Test',
  'Anytime',
  '1-2x Annually',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['longevity', 'cellular_health'],
  ARRAY[]::text[],
  'Measures DNA methylation status at specific CpG sites to calculate epigenetic aging rate.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:53:22.144956+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"Second-generation epigenetic clocks (like GrimAge or DunedinPACE) can predict all-cause mortality with over 20% greater accuracy than chronological age alone.","source":"Lu et al., 2019","source_url":"https://pubmed.ncbi.nlm.nih.gov/30669119/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["longevity","cellular_health"],"interesting_score":4}'::jsonb]
),
(
  'bfr_training',
  'bfr_training',
  'BFR Training',
  'exercise',
  'Physical',
  'active',
  'BFR Training',
  'A health and longevity modality focused on strength.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'strength',
  NULL,
  4,
  NULL,
  NULL,
  '4 Sets (30-15-15-15 reps)',
  'Anytime',
  '1-3x Weekly',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['strength', 'recovery', 'muscle_health'],
  ARRAY[]::text[],
  'Traps venous blood flow while maintaining arterial flow, inducing massive metabolic stress at light weights.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:53:22.144956+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"Blood Flow Restriction (BFR) training produces equivalent muscle hypertrophy using only 20-30% of your 1-rep max compared to heavy lifting (70-80%), vastly reducing joint wear and tear.","source":"Hughes et al., 2017","source_url":"https://pubmed.ncbi.nlm.nih.gov/28259850/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["strength","recovery","muscle_health"],"interesting_score":4}'::jsonb]
),
(
  'shilajit',
  'shilajit',
  'Shilajit',
  'supplement',
  'Biochemistry',
  'active',
  'Shilajit',
  'A health and longevity modality focused on energy.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'energy',
  NULL,
  3,
  NULL,
  NULL,
  '250-500mg',
  'Morning',
  'Daily',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['energy', 'testosterone', 'endurance'],
  ARRAY[]::text[],
  'Rich in fulvic acid, it enhances mitochondrial ATP production and CoQ10 synthesis.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:53:22.144956+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"A 90-day clinical trial of purified Shilajit (500mg/day) in healthy volunteers demonstrated a significant 20% increase in total testosterone and a preservation of CoQ10 levels in the blood.","source":"Pandit et al., 2015","source_url":"https://pubmed.ncbi.nlm.nih.gov/26395129/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["energy","testosterone","endurance"],"interesting_score":4}'::jsonb]
),
(
  'coq10',
  'coq10',
  'CoQ10',
  'supplement',
  'Biochemistry',
  'active',
  'CoQ10',
  'A health and longevity modality focused on cardiovascular_health.',
  'Research has shown this modality has significant impacts on longevity and performance.',
  NULL,
  'cardiovascular_health',
  NULL,
  4,
  NULL,
  NULL,
  '100-200mg',
  'With Fats',
  'Daily',
  NULL,
  NULL,
  'accessible',
  'medium',
  NULL,
  4,
  '4',
  NULL,
  'low_risk',
  NULL,
  ARRAY[]::text[],
  ARRAY['cardiovascular_health', 'energy', 'longevity'],
  ARRAY[]::text[],
  'An essential component of the electron transport chain, facilitating ATP synthesis in mitochondria.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '2026-06-06T01:53:22.144956+00:00',
  '{}'::jsonb,
  '{}'::jsonb,
  NULL,
  ARRAY['{"fact":"In the Q-SYMBIO randomized double-blind trial, long-term CoQ10 supplementation in heart failure patients reduced cardiovascular mortality by 43% and all-cause mortality by 42%.","source":"Mortensen et al., 2014","source_url":"https://pubmed.ncbi.nlm.nih.gov/25282031/","impact_score":4,"accuracy_score":4,"relevance_score":5,"related_outcomes":["cardiovascular_health","energy","longevity"],"interesting_score":4}'::jsonb]
);
