-- Migration: 0009_new_20_modalities.sql
-- Adds 20 new highly-researched modalities

INSERT INTO modalities (
  id,
  slug,
  name,
  modality_type,
  category,
  status,
  display_name,
  brief_description,
  expanded_why,
  primary_outcome,
  overall_longevity_benefit,
  dose_or_exposure,
  timing_summary,
  frequency,
  cost_tier,
  effort_level,
  evidence_quality,
  effect_size_estimate,
  safety_level,
  functional_outcomes_to_track,
  hallmarks_of_aging_impact,
  mechanism_of_action,
  efficacy_stats,
  updated_at
) VALUES 
(
  'l_tyrosine',
  'l-tyrosine',
  'L-Tyrosine',
  'supplement',
  'Biochemistry',
  'active',
  'L-Tyrosine',
  'An amino acid precursor to dopamine, norepinephrine, and epinephrine, used to enhance cognitive performance under acute stress or sleep deprivation.',
  'Tyrosine is a conditionally essential amino acid. During periods of intense stress, cold exposure, or sleep deprivation, catecholamine reserves (dopamine/norepinephrine) are rapidly depleted. Supplementing L-Tyrosine reliably replenishes these neurotransmitters, preserving working memory and focus when they would otherwise degrade.',
  'cognitive_health',
  2,
  '500-1000mg',
  'Morning or 30-60m pre-stressor',
  'As needed',
  'accessible',
  'low',
  4,
  '3',
  'low_risk',
  ARRAY['', 'energy', 'stress']::text[],
  '["Altered Intercellular Communication"]'::jsonb,
  'Catecholamine precursor; bypasses rate-limiting tyrosine hydroxylase step during systemic depletion to restore neurotransmitter pools.',
  '[]'::jsonb,
  NOW()
),
(
  'lithium_orotate',
  'lithium-orotate',
  'Lithium Orotate (Micro-dose)',
  'supplement',
  'Longevity & Neurology',
  'active',
  'Lithium Orotate (Micro-dose)',
  'Micro-dosed lithium (1-5mg) to support neuroprotection, mood stabilization, and stimulate autophagy.',
  'While high-dose lithium carbonate is a psychiatric drug, nutritional micro-dosing (orotate) mimics natural trace amounts found in groundwater in long-lived populations (Blue Zones). It acts as a powerful neuroprotectant, upregulates BDNF, and inhibits GSK-3 beta, a primary longevity target pathway.',
  'longevity',
  4,
  '1-5mg elemental Lithium',
  'Evening',
  'Daily',
  'accessible',
  'low',
  3,
  '4',
  'low_risk',
  ARRAY['', 'longevity', 'sleep_quality']::text[],
  '["Loss of Proteostasis","Altered Intercellular Communication"]'::jsonb,
  'Inhibition of Glycogen Synthase Kinase-3 beta (GSK-3β), up-regulation of Brain-Derived Neurotrophic Factor (BDNF), and induction of autophagy.',
  '[]'::jsonb,
  NOW()
),
(
  'collagen_peptides',
  'collagen-peptides',
  'Collagen Peptides',
  'supplement',
  'Tissue & Joint Health',
  'active',
  'Collagen Peptides',
  'Hydrolyzed collagen proteins to support skin elasticity, bone density, and tendon/ligament remodeling.',
  'Collagen synthesis declines by roughly 1% per year after age 25. Oral supplementation of specific bioactive peptides provides high concentrations of glycine, proline, and hydroxyproline, which stimulate fibroblasts and chondrocytes to synthesize new structural matrices in skin and joints.',
  'joint_health',
  3,
  '10-20g',
  'Morning or Pre-workout (with Vitamin C)',
  'Daily',
  'accessible',
  'low',
  4,
  '3',
  'low_risk',
  ARRAY['', 'skin_elasticity', 'recovery']::text[],
  '["Extracellular Matrix Dysregulation","Loss of Proteostasis"]'::jsonb,
  'Provides specific dipeptides (Pro-Hyp) that act as signaling molecules at fibroblast receptors to upregulate endogenous collagen synthesis.',
  '[]'::jsonb,
  NOW()
),
(
  'hyaluronic_acid_oral',
  'hyaluronic-acid-oral',
  'Oral Hyaluronic Acid',
  'supplement',
  'Tissue & Joint Health',
  'active',
  'Oral Hyaluronic Acid',
  'High molecular weight oral HA to maintain cellular hydration, joint lubrication, and skin viscoelasticity.',
  'Hyaluronic acid binds up to 1000x its weight in water. Endogenous production drops drastically with age. Contrary to early belief, high molecular weight HA is digested by gut microbiota into shorter chain polymers that are highly bioavailable, actively migrating to joints and skin to restore synovial fluid and dermal moisture.',
  'joint_health',
  3,
  '100-200mg',
  'Morning',
  'Daily',
  'accessible',
  'low',
  3,
  '3',
  'low_risk',
  ARRAY['', 'skin_elasticity']::text[],
  '["Extracellular Matrix Dysregulation"]'::jsonb,
  'Microbial fermentation in the gut yields oligosaccharides that bind to CD44 receptors, stimulating synovial fibroblasts to synthesize new high-molecular-weight HA.',
  '[]'::jsonb,
  NOW()
),
(
  'methylene_blue',
  'methylene-blue',
  'Methylene Blue (Low-Dose)',
  'supplement',
  'Longevity & Neurology',
  'active',
  'Methylene Blue (Low-Dose)',
  'A synthetic dye acting as a highly potent mitochondrial electron donor to increase ATP production and cognitive function.',
  'At ultra-low, USP-grade doses, Methylene Blue bypasses dysfunctional complexes in the mitochondrial electron transport chain (specifically Complexes I-III), acting as an alternative electron carrier. This uniquely increases ATP production while actively consuming reactive oxygen species (ROS), making it a remarkable cognitive enhancer and anti-aging compound.',
  'energy',
  4,
  '0.5 - 2mg / kg of bodyweight',
  'Morning',
  'Pulsed (e.g. 5 days on, 2 off)',
  'premium',
  'medium',
  3,
  '4',
  'moderate_risk',
  ARRAY['', 'focus', 'brain_fog']::text[],
  '["Mitochondrial Dysfunction"]'::jsonb,
  'Alternative electron carrier in the mitochondrial ETC; potent antioxidant; mild MAO inhibitor at higher doses.',
  '[]'::jsonb,
  NOW()
),
(
  'alpha_lipoic_acid',
  'alpha-lipoic-acid',
  'Alpha-Lipoic Acid (ALA)',
  'supplement',
  'Biochemistry',
  'active',
  'Alpha-Lipoic Acid (ALA)',
  'A universal, both water- and fat-soluble antioxidant that recycles other antioxidants and acts as an insulin sensitizer.',
  'ALA is a mitochondrial co-enzyme critical for energy metabolism. It uniquely crosses the blood-brain barrier and can neutralize free radicals in virtually every tissue. It powerfully chelates heavy metals and has strong clinical data for reducing peripheral neuropathy and increasing cellular glucose uptake.',
  'metabolic_health',
  4,
  '300-600mg (Na-R-ALA preferred)',
  'Before meals',
  'Daily',
  'accessible',
  'low',
  4,
  '4',
  'low_risk',
  ARRAY['', 'energy']::text[],
  '["Mitochondrial Dysfunction","Deregulated Nutrient Sensing"]'::jsonb,
  'Cofactor for mitochondrial alpha-ketoacid dehydrogenases; direct radical scavenger; upregulates AMPK signaling leading to enhanced GLUT4 translocation.',
  '[]'::jsonb,
  NOW()
),
(
  'myo_inositol',
  'myo-inositol',
  'Myo-Inositol',
  'supplement',
  'Nervous System & Sleep',
  'active',
  'Myo-Inositol',
  'A carbohydrate compound essential for cell signaling, promoting deep sleep, reducing anxiety, and sensitizing insulin receptors.',
  'Often referred to informally as Vitamin B8, Myo-inositol acts as an intracellular secondary messenger. It heavily modulates serotonin and dopamine signaling, significantly shortening sleep latency. It is also an established, elite intervention for insulin resistance (specifically in PCOS) via its role in phosphoinositide signaling.',
  'sleep_quality',
  3,
  '1-2g for sleep, up to 4g for metabolism',
  '30m before bed',
  'Daily',
  'accessible',
  'low',
  4,
  '4',
  'low_risk',
  ARRAY['', 'mood', 'glucose_levels']::text[],
  '["Deregulated Nutrient Sensing","Altered Intercellular Communication"]'::jsonb,
  'Precursor to PIP3; acts as a second messenger in insulin and neurotransmitter (serotonin/dopamine) signal transduction pathways.',
  '[]'::jsonb,
  NOW()
),
(
  'phosphatidylserine',
  'phosphatidylserine',
  'Phosphatidylserine',
  'supplement',
  'Biochemistry',
  'active',
  'Phosphatidylserine',
  'A major phospholipid in the brain that actively blunts cortisol and supports cognitive function and memory retention.',
  'Phosphatidylserine makes up 15% of the lipid pool in the brain. Supplementation has a unique, clinically proven ability to blunt exercise-induced and stress-induced cortisol spikes. It is widely used to prevent neurodegeneration and enhance athletic recovery by regulating HPA axis hyper-activation.',
  'stress',
  3,
  '300-600mg',
  'Post-workout or Evening',
  'Daily',
  'accessible',
  'low',
  4,
  '3',
  'low_risk',
  ARRAY['', 'recovery', 'cognitive_health']::text[],
  '["Altered Intercellular Communication"]'::jsonb,
  'Integrates into neuronal cell membranes, enhancing receptor fluidity and signaling; dampens ACTH release from the pituitary gland.',
  '[]'::jsonb,
  NOW()
),
(
  'vitamin_k2_mk7',
  'vitamin-k2-mk7',
  'Vitamin K2 (MK-7)',
  'supplement',
  'Tissue & Joint Health',
  'active',
  'Vitamin K2 (MK-7)',
  'An essential vitamin that activates proteins responsible for directing calcium into bones and away from vascular tissue.',
  'If you take Vitamin D3 or consume calcium without K2, calcium risks depositing in arterial walls (atherosclerosis). Vitamin K2 activates Osteocalcin (to pull calcium into bones) and Matrix GLA Protein (to prevent calcium buildup in arteries). It is a non-negotiable longevity compound for cardiovascular and skeletal health.',
  'cardiovascular_health',
  5,
  '100-300mcg',
  'Morning (with fat)',
  'Daily',
  'accessible',
  'low',
  5,
  '4',
  'low_risk',
  ARRAY['', 'bone_density']::text[],
  '["Altered Intercellular Communication"]'::jsonb,
  'Serves as an essential cofactor for the enzyme gamma-glutamyl carboxylase, which carboxylates and activates Osteocalcin and Matrix Gla-Protein (MGP).',
  '[]'::jsonb,
  NOW()
),
(
  'vitamin_d3',
  'vitamin-d3',
  'Vitamin D3 (Cholecalciferol)',
  'supplement',
  'Biochemistry',
  'active',
  'Vitamin D3 (Cholecalciferol)',
  'A secosteroid hormone precursor essential for immune regulation, bone density, mood, and broad longevity markers.',
  'D3 acts on over 1,000 different genes. Due to modern indoor lifestyles, upwards of 70% of the population is deficient. Optimized levels (40-60 ng/mL) are powerfully correlated with reduced all-cause mortality, drastically lower autoimmune risk, and preserved testosterone/hormonal function.',
  'longevity',
  5,
  '2000-5000 IU',
  'Morning (with fat)',
  'Daily',
  'free',
  'very_low',
  5,
  '5',
  'low_risk',
  ARRAY['', 'mood', 'longevity']::text[],
  '["Genomic Instability","Altered Intercellular Communication"]'::jsonb,
  'Converts to calcitriol in the kidneys, which binds to the nuclear Vitamin D Receptor (VDR), directly regulating the transcription of ~5% of the human genome.',
  '[]'::jsonb,
  NOW()
),
(
  'tongkat_ali',
  'tongkat-ali',
  'Tongkat Ali',
  'supplement',
  'Biochemistry',
  'active',
  'Tongkat Ali',
  'A potent Southeast Asian adaptogen (Eurycoma longifolia) that liberates bound testosterone and regulates cortisol.',
  'Tongkat Ali strongly influences the endocrine system. By lowering sex-hormone-binding globulin (SHBG), it frees up active/free testosterone. It also has a profound anti-estrogenic effect and noticeably shifts the cortisol-to-testosterone ratio into an anabolic state, making it elite for vitality, libido, and stress resilience.',
  'hormonal_health',
  3,
  '400mg',
  'Morning',
  'Daily (Pulse 5 on, 2 off)',
  'accessible',
  'low',
  4,
  '4',
  'low_risk',
  ARRAY['', 'recovery', 'stress']::text[],
  '["Altered Intercellular Communication"]'::jsonb,
  'Stimulates the release of free testosterone from its binding proteins (SHBG) and reduces cortisol production in the adrenal glands.',
  '[]'::jsonb,
  NOW()
),
(
  'lions_mane',
  'lions-mane',
  'Lion''s Mane Mushroom',
  'supplement',
  'Longevity & Neurology',
  'active',
  'Lion''s Mane Mushroom',
  'A medicinal mushroom that contains hericenones and erinacines, which stimulate Nerve Growth Factor (NGF) production.',
  'Lion’s Mane is one of the only natural compounds capable of crossing the blood-brain barrier to directly stimulate the synthesis of NGF. It promotes profound neuroplasticity, enhances myelination, and demonstrates clinical efficacy in improving mild cognitive impairment and combating neurodegenerative aging.',
  'cognitive_health',
  4,
  '1000-2000mg (Dual Extract)',
  'Morning or Afternoon',
  'Daily',
  'accessible',
  'low',
  3,
  '3',
  'low_risk',
  ARRAY['', 'memory', 'brain_fog']::text[],
  '["Altered Intercellular Communication"]'::jsonb,
  'Active compounds (erinacines) cross the blood-brain barrier to stimulate the synthesis of Nerve Growth Factor (NGF) and Brain-Derived Neurotrophic Factor (BDNF).',
  '[]'::jsonb,
  NOW()
),
(
  'l_citrulline',
  'l-citrulline',
  'L-Citrulline',
  'supplement',
  'Tissue & Joint Health',
  'active',
  'L-Citrulline',
  'An amino acid that powerfully elevates arginine levels and systemic nitric oxide, improving endothelial function and blood flow.',
  'Unlike L-Arginine, which is heavily degraded by the liver, L-Citrulline easily bypasses hepatic metabolism and converts to arginine in the kidneys. This creates a massive, sustained spike in Nitric Oxide, lowering blood pressure, massively improving exercise pump/endurance, and supporting cardiovascular longevity.',
  'cardiovascular_health',
  4,
  '3-6g',
  '30-60m Pre-workout',
  'Daily or Pre-exercise',
  'accessible',
  'low',
  4,
  '4',
  'low_risk',
  ARRAY['', 'energy', 'recovery']::text[],
  '["Altered Intercellular Communication"]'::jsonb,
  'Converts to L-arginine in the kidneys, driving the endothelial nitric oxide synthase (eNOS) pathway to produce nitric oxide (NO) for vasodilation.',
  '[]'::jsonb,
  NOW()
),
(
  'tudca',
  'tudca',
  'TUDCA',
  'supplement',
  'Biochemistry',
  'active',
  'TUDCA',
  'A highly hydrophilic bile acid that protects the liver and resolves systemic Endoplasmic Reticulum (ER) stress.',
  'TUDCA (Tauroursodeoxycholic acid) is a chemical chaperone. When cells undergo immense metabolic stress, misfolded proteins accumulate in the ER, causing cell death. TUDCA physically stabilizes these proteins, halting apoptosis. It drastically lowers liver enzymes, improves insulin sensitivity, and acts as a profound cellular protectant.',
  'cellular_health',
  4,
  '250-500mg',
  'With meals',
  'Daily',
  'premium',
  'low',
  4,
  '4',
  'low_risk',
  ARRAY['', 'metabolic_health']::text[],
  '["Loss of Proteostasis","Mitochondrial Dysfunction"]'::jsonb,
  'Acts as a chemical chaperone in the Endoplasmic Reticulum, enhancing protein folding capacity and preventing Unfolded Protein Response (UPR)-mediated apoptosis.',
  '[]'::jsonb,
  NOW()
),
(
  'l_carnosine',
  'l-carnosine',
  'L-Carnosine',
  'supplement',
  'Longevity & Neurology',
  'active',
  'L-Carnosine',
  'A naturally occurring dipeptide that buffers acid in muscles and prevents the formation of Advanced Glycation End-products (AGEs).',
  'Carnosine acts as an intracellular pH buffer, massively increasing physical endurance. More importantly for longevity, it acts as a sacrificial sink for sugar molecules, preventing them from binding to and permanently damaging tissue proteins (glycation), thus fighting arterial stiffness and skin aging.',
  'cellular_health',
  4,
  '500-1000mg',
  'Morning or Pre-workout',
  'Daily',
  'accessible',
  'low',
  3,
  '3',
  'low_risk',
  ARRAY['', 'energy', 'skin_elasticity']::text[],
  '["Loss of Proteostasis","Macromolecular Damage"]'::jsonb,
  'Scavenges reactive oxygen species (ROS) and reactive aldehydes; buffers intracellular protons (H+); inhibits cross-linking of proteins (anti-glycation).',
  '[]'::jsonb,
  NOW()
),
(
  'resveratrol_pterostilbene',
  'resveratrol-pterostilbene',
  'Resveratrol / Pterostilbene',
  'supplement',
  'Longevity & Neurology',
  'active',
  'Resveratrol / Pterostilbene',
  'Polyphenols that mimic caloric restriction by activating SIRT1, promoting DNA repair and mitochondrial biogenesis.',
  'Made famous by David Sinclair, these polyphenols act as "accelerators" for Sirtuins (the longevity genes). While Resveratrol is poorly bioavailable, taking it with a fat source or opting for its methylated cousin (Pterostilbene) dramatically increases absorption. They work synergistically with NAD+ precursors to repair DNA.',
  'longevity',
  5,
  '500-1000mg',
  'Morning (with fat source like yogurt)',
  'Daily',
  'accessible',
  'low',
  3,
  '3',
  'low_risk',
  ARRAY['', 'cellular_health']::text[],
  '["Epigenetic Alterations","Mitochondrial Dysfunction","Genomic Instability"]'::jsonb,
  'Allosteric activator of SIRT1, leading to deacetylation of target proteins (like PGC-1α), enhancing mitochondrial biogenesis and DNA repair.',
  '[]'::jsonb,
  NOW()
),
(
  'sulforaphane',
  'sulforaphane',
  'Sulforaphane',
  'supplement',
  'Biochemistry',
  'active',
  'Sulforaphane',
  'A highly potent Nrf2 activator derived from broccoli sprouts that turns on the body''s ultimate antioxidant defense system.',
  'Instead of taking direct antioxidants (like Vitamin C), Sulforaphane activates the Nrf2 pathway, a master regulator that turns on over 200 cytoprotective genes. This creates a sustained, multi-day boost in glutathione production, radically decreasing inflammation and detoxifying environmental carcinogens.',
  'cellular_health',
  5,
  '10-20mg (or via Broccoli Sprouts)',
  'Morning',
  'Daily',
  'accessible',
  'low',
  4,
  '4',
  'low_risk',
  ARRAY['', 'cellular_health', 'immune_function']::text[],
  '["Genomic Instability","Loss of Proteostasis"]'::jsonb,
  'Interacts with Keap1, freeing Nrf2 to translocate to the nucleus where it binds to Antioxidant Response Elements (ARE), upregulating phase II detoxification enzymes.',
  '[]'::jsonb,
  NOW()
),
(
  'gaba',
  'gaba',
  'GABA',
  'supplement',
  'Nervous System & Sleep',
  'active',
  'GABA',
  'The primary inhibitory neurotransmitter in the brain; used to decrease sleep latency and reduce acute anxiety.',
  'GABA acts as the brain''s brake pedal. While large molecules struggle to cross the blood-brain barrier, supplementary GABA binds to enteric nervous system receptors in the gut, sending a vagus nerve signal to the brain to downregulate the central nervous system, making it highly effective for falling asleep.',
  'sleep_quality',
  2,
  '100-300mg',
  '30m before bed or acute stress',
  'As needed',
  'accessible',
  'low',
  3,
  '3',
  'low_risk',
  ARRAY['', 'stress', 'mood']::text[],
  '["Altered Intercellular Communication"]'::jsonb,
  'Binds to GABA-A and GABA-B receptors (predominantly peripherally and in the ENS), inducing hyperpolarization of neurons and dampening excitability.',
  '[]'::jsonb,
  NOW()
),
(
  'bacopa_monnieri',
  'bacopa-monnieri',
  'Bacopa Monnieri',
  'supplement',
  'Longevity & Neurology',
  'active',
  'Bacopa Monnieri',
  'An ancient Ayurvedic adaptogen proven in modern clinical trials to significantly enhance memory retention and recall speed.',
  'Bacopa contains Bacosides, which actively repair damaged neurons and promote dendritic proliferation. Unlike caffeine which offers acute stimulation, Bacopa builds up over 4-6 weeks to fundamentally improve the hardware of the brain, making it one of the most reliable memory-enhancing nootropics.',
  'cognitive_health',
  3,
  '300mg (standardized to 50% Bacosides)',
  'Morning (with fat)',
  'Daily',
  'accessible',
  'low',
  4,
  '4',
  'low_risk',
  ARRAY['', 'memory', 'brain_fog']::text[],
  '["Altered Intercellular Communication"]'::jsonb,
  'Enhances kinase activity, neuronal synthesis, and restoration of synaptic activity; highly antioxidant in the hippocampus.',
  '[]'::jsonb,
  NOW()
),
(
  'alpha_gpc',
  'alpha-gpc',
  'Alpha-GPC',
  'supplement',
  'Longevity & Neurology',
  'active',
  'Alpha-GPC',
  'A highly bioavailable choline donor that crosses the blood-brain barrier to rapidly synthesize acetylcholine.',
  'Acetylcholine is the neurotransmitter responsible for focus, learning, and muscular power output. Alpha-GPC provides a direct building block for this, resulting in an acute, noticeable spike in concentration and physical power during workouts. It’s also heavily researched for preventing cognitive decline.',
  'cognitive_health',
  3,
  '300-600mg',
  'Pre-workout or Pre-deep work',
  'Daily or As needed',
  'accessible',
  'low',
  4,
  '4',
  'low_risk',
  ARRAY['', 'energy', 'strength']::text[],
  '["Altered Intercellular Communication"]'::jsonb,
  'Acts as a direct precursor to acetylcholine synthesis and incorporates into cell membranes as phosphatidylcholine.',
  '[]'::jsonb,
  NOW()
);
