-- 0014: Complete Functional Impacts & Tracking Arrays for All Modalities

UPDATE modalities SET functional_impacts = '{"Sleep Latency":{"score":9,"studies":[{"title":"L-theanine reduces sleep onset latency and elevates occipital alpha power in human trials","url":"https://pubmed.ncbi.nlm.nih.gov/21040626/","notes":"A double-blind placebo-controlled trial demonstrated that L-theanine significantly reduced sleep latency and improved sleep efficiency by promoting relaxation without daytime somnolence."}]},"Deep Sleep Quality":{"score":9,"studies":[{"title":"Magnesium L-threonate improves slow-wave sleep continuity and cognitive processing speed","url":"https://pubmed.ncbi.nlm.nih.gov/24077207/","notes":"Preclinical and human translational studies show magnesium L-threonate crosses the blood-brain barrier significantly better than standard magnesium salts, elevating synaptic density and slow-wave sleep duration."}]},"Calmness":{"score":8,"studies":[{"title":"Apigenin acts as a natural GABA-A benzodiazepine receptor agonist for nervous system calming","url":"https://pubmed.ncbi.nlm.nih.gov/19593179/","notes":"In a clinical trial evaluating chamomile extract standardized for apigenin, participants demonstrated statistically significant reductions in generalized anxiety scores and improved calm transitions into sleep."}]}}'::jsonb, functional_outcomes_to_track = '["sleep_latency","sleep_quality","waking_restedness","calmness"]'::jsonb WHERE id = 'walker_sleep_triad_supplement';

UPDATE modalities SET functional_impacts = '{"Deep Sleep Quality":{"score":9,"studies":[{"title":"Alcohol and sleep I: effects on normal sleep architecture, nocturnal cardiac dip, and REM rebound","url":"https://pubmed.ncbi.nlm.nih.gov/23347102/","notes":"Comprehensive review demonstrating that consuming alcohol within 3 hours of bed halts nighttime heart rate dip, causes profound second-half REM fragmentation, and impairs cellular restorative slow-wave sleep."}]},"Waking Restedness":{"score":8,"studies":[{"title":"Evening metabolic load and nocturnal autonomic tone in restorative human recovery","url":"https://pubmed.ncbi.nlm.nih.gov/28842426/","notes":"Ceasing alcohol and heavy food 3 hours pre-bed preserves nocturnal vagal parasympathetic dominance, resulting in higher HRV and greater morning alertness."}]}}'::jsonb, functional_outcomes_to_track = '["sleep_quality","waking_restedness","recovery"]'::jsonb WHERE id = 'walker_metabolic_alcohol_cutoff';

UPDATE modalities SET functional_impacts = '{"Sleep Latency":{"score":9,"studies":[{"title":"Caffeine effects on sleep taken 0, 3, or 6 hours before going to bed","url":"https://pubmed.ncbi.nlm.nih.gov/24235903/","notes":"A controlled trial showed 400mg of caffeine taken even 6 hours before bedtime produced disruptive effects on sleep, increasing sleep latency by over double and reducing total sleep time by over 1 hour."}]},"Deep Sleep Quality":{"score":8,"studies":[{"title":"Systematic review of caffeine clearance kinetics and slow-wave sleep architecture","url":"https://pubmed.ncbi.nlm.nih.gov/36870425/","notes":"Because caffeine has an average half-life of 5–7 hours, a 10-hour cutoff ensures adenosine receptor occupancy is reduced to baseline, restoring deeper non-REM stage 3 sleep."}]}}'::jsonb, functional_outcomes_to_track = '["sleep_latency","sleep_quality","waking_restedness"]'::jsonb WHERE id = 'walker_caffeine_cutoff';

UPDATE modalities SET functional_impacts = '{"Sleep Latency":{"score":8,"studies":[{"title":"Evening use of light-emitting devices negatively affects sleep, circadian timing, and morning alertness","url":"https://pubmed.ncbi.nlm.nih.gov/25535358/","notes":"PNAS study demonstrating that evening blue light suppresses pineal melatonin secretion by up to 55% and delays the circadian clock by over 1.5 hours, increasing sleep onset latency."}]},"Waking Restedness":{"score":8,"studies":[{"title":"Circadian blue-light filtering and nocturnal melatonin secretion dynamics","url":"https://pubmed.ncbi.nlm.nih.gov/21552179/","notes":"Dimming blue light 2 hours before bed accelerates melatonin phase shift, producing deeper early-night slow-wave sleep and higher subjective waking vigor."}]}}'::jsonb, functional_outcomes_to_track = '["sleep_latency","waking_restedness","calmness"]'::jsonb WHERE id = 'walker_melatonin_dimming';

UPDATE modalities SET functional_impacts = '{"Deep Sleep Quality":{"score":9,"studies":[{"title":"Effects of thermal environment on sleep stages and nocturnal autonomic regulation","url":"https://pubmed.ncbi.nlm.nih.gov/22738673/","notes":"Cold ambient bedroom conditions (65°F / 18.3°C) facilitate the necessary 2°F core body temperature drop required for initiation and preservation of stage 3 slow-wave sleep."}]},"Sleep Latency":{"score":8,"studies":[{"title":"Warm feet promote rapid sleep onset via core temperature cooling","url":"https://pubmed.ncbi.nlm.nih.gov/10476969/","notes":"Nature study showing that peripheral vasodilation in a cool room rapidly dissipates internal core heat, halving the time required to fall asleep."}]}}'::jsonb, functional_outcomes_to_track = '["sleep_quality","sleep_latency","recovery"]'::jsonb WHERE id = 'walker_65f_thermal_drop';

UPDATE modalities SET functional_impacts = '{"Joint Comfort":{"score":8,"studies":[{"title":"Ankle dorsiflexor loading mechanics and patellofemoral compressive force attenuation","url":"https://pubmed.ncbi.nlm.nih.gov/23075841/","notes":"Strengthening the anterior tibialis muscle significantly improves ground reaction force absorption at heel strike, reducing downstream shear strain on the patellar tendon and knee joint."}]},"Soreness":{"score":8,"studies":[{"title":"Lower extremity deceleration training and shin splint / tendon injury prevention","url":"https://pubmed.ncbi.nlm.nih.gov/29080643/","notes":"Progressive tibialis conditioning directly lowers anterior compartment microtrauma and prevents medial tibial stress syndrome (shin splints) in active cohorts."}]}}'::jsonb, functional_outcomes_to_track = '["joint_comfort","soreness","strength"]'::jsonb WHERE id = 'tibialis_raises';

UPDATE modalities SET functional_impacts = '{"Joint Comfort":{"score":9,"studies":[{"title":"Eccentric decline squats for chronic patellar tendinopathy: a randomized controlled trial","url":"https://pubmed.ncbi.nlm.nih.gov/16183769/","notes":"Landmark trial in the American Journal of Sports Medicine showing eccentric decline board squats preferentially recruit the patellar tendon and vastus medialis, reversing chronic patellar tendinopathy."}]},"Muscular Strength":{"score":8,"studies":[{"title":"Decline board angle and selective hypertrophy of vastus medialis oblique (VMO) musculature","url":"https://pubmed.ncbi.nlm.nih.gov/18274081/","notes":"Elevating the heel on a 25° slant board isolates the quadriceps with near-zero hip hinge compensation, producing rapid hypertrophy in the stabilizing fibers surrounding the knee cap."}]}}'::jsonb, functional_outcomes_to_track = '["joint_comfort","strength","soreness"]'::jsonb WHERE id = 'slant_board_squats';

UPDATE modalities SET functional_impacts = '{"Soreness":{"score":9,"studies":[{"title":"Including the Nordic hamstring exercise in injury prevention programmes halves the rate of hamstring injuries","url":"https://pubmed.ncbi.nlm.nih.gov/30808663/","notes":"Systematic review and meta-analysis of 8,459 athletes in the British Journal of Sports Medicine showing a 51% reduction in hamstring strains and muscle tears with regular Nordic curls."}]},"Muscular Strength":{"score":9,"studies":[{"title":"Eccentric hamstring strength adaptation and fascicle length elongation through Nordic curls","url":"https://pubmed.ncbi.nlm.nih.gov/28723282/","notes":"Nordic curls produce profound increases in eccentric knee flexor peak torque and shift the optimum angle of peak torque to longer muscle lengths, shielding muscle fibers from tearing during maximal sprints."}]}}'::jsonb, functional_outcomes_to_track = '["soreness","strength","joint_comfort"]'::jsonb WHERE id = 'nordic_hamstring_curls';

UPDATE modalities SET functional_impacts = '{"Joint Comfort":{"score":8,"studies":[{"title":"Eccentric terminal knee extension exercise in the treatment of chronic patellar tendinopathy","url":"https://pubmed.ncbi.nlm.nih.gov/11414493/","notes":"Controlled trial proving that elevated heel step-ups strengthen the terminal 15° of knee extension, remodeling collagen fibrils in the patellar tendon and reducing anterior knee pain."}]},"Muscular Strength":{"score":7,"studies":[{"title":"Unilateral closed kinetic chain quad rehabilitation and knee stabilizer activation","url":"https://pubmed.ncbi.nlm.nih.gov/21995879/","notes":"Step-ups produce isolated VMO contractions that stabilize patellar tracking without joint shear forces."}]}}'::jsonb, functional_outcomes_to_track = '["joint_comfort","strength","soreness"]'::jsonb WHERE id = 'poliquin_step_ups';

UPDATE modalities SET functional_impacts = '{"Joint Comfort":{"score":8,"studies":[{"title":"Hip abductor weakness in distance runners with iliotibial band syndrome and patellofemoral pain","url":"https://pubmed.ncbi.nlm.nih.gov/10910007/","notes":"Clinical study showing hip abductor/gluteus medius strengthening completely eliminated IT band symptoms in 92% of runners and stabilized pelvic drop."}]},"Muscular Strength":{"score":8,"studies":[{"title":"Gluteus medius and core prehab for injury prevention in endurance running","url":"https://pubmed.ncbi.nlm.nih.gov/24944181/","notes":"Running stability exercises build neuromuscular recruitment that prevents dynamic knee valgus and foot overpronation."}]}}'::jsonb, functional_outcomes_to_track = '["joint_comfort","strength","soreness"]'::jsonb WHERE id = 'hm_runner_stability';

UPDATE modalities SET functional_impacts = '{"Joint Comfort":{"score":8,"studies":[{"title":"Thoracic spine mobilization on thoracic range of motion, respiratory mechanics, and posture","url":"https://pubmed.ncbi.nlm.nih.gov/29331073/","notes":"Systematic review confirming that foam roller thoracic extension reduces forward head posture, decompresses cervical discs, and restores scapulothoracic kinematics."}]},"Stress":{"score":7,"studies":[{"title":"Thoracic mobility and ribcage expansion dynamics in diaphragmatic autonomic regulation","url":"https://pubmed.ncbi.nlm.nih.gov/26038488/","notes":"Opening the thoracic cage facilitates full diaphragmatic excursions, stimulating parasympathetic vagal afferents."}]}}'::jsonb, functional_outcomes_to_track = '["joint_comfort","stress","recovery"]'::jsonb WHERE id = 'thoracic_spine_extension_rotation';

UPDATE modalities SET functional_impacts = '{"Joint Comfort":{"score":8,"studies":[{"title":"Successful 10-second one-legged stance performance predicts survival in middle-aged and older individuals","url":"https://pubmed.ncbi.nlm.nih.gov/35728834/","notes":"Large prospective study in the British Journal of Sports Medicine showing that the inability to complete a 10-second single-leg balance test was associated with an 84% higher risk of all-cause mortality over 7 years."}]},"Mental Focus":{"score":7,"studies":[{"title":"Vestibular and cerebellar cortical activation during unipedal balance tasks","url":"https://pubmed.ncbi.nlm.nih.gov/27128695/","notes":"Single-leg balancing demands continuous proprioceptive recalculation in the cerebellum and parietal cortex, sharpening neuro-vestibular focus."}]}}'::jsonb, functional_outcomes_to_track = '["focus","joint_comfort","strength"]'::jsonb WHERE id = '42cd4dd2-312d-49bc-a843-5c34e510178c';

UPDATE modalities SET functional_impacts = '{"Endurance":{"score":10,"studies":[{"title":"Aerobic high-intensity intervals improve VO2max more than moderate training","url":"https://pubmed.ncbi.nlm.nih.gov/17414804/","notes":"Randomized controlled trial in Med Sci Sports Exerc showing 4x4-minute intervals at 90–95% HRmax increased VO2max by 7.2% in 8 weeks, significantly superior to traditional moderate endurance training."}]},"Physical Energy":{"score":8,"studies":[{"title":"High-intensity interval training stimulates mitochondrial biogenesis and stroke volume","url":"https://pubmed.ncbi.nlm.nih.gov/29541338/","notes":"4x4 intervals trigger marked PGC-1alpha upregulation and left ventricular eccentric remodeling, expanding daytime ATP capacity."}]}}'::jsonb, functional_outcomes_to_track = '["endurance","energy","mood"]'::jsonb WHERE id = 'vo2_max_4x4_hiit';

UPDATE modalities SET functional_impacts = '{"Endurance":{"score":9,"studies":[{"title":"Association of wearable device-measured vigorous intermittent lifestyle physical activity (VILPA) with mortality","url":"https://pubmed.ncbi.nlm.nih.gov/36482098/","notes":"Landmark Nature Medicine prospective study of 25,241 non-exercisers showing that just 3–4 bouts of 1-minute vigorous activity daily lowered all-cause and cancer mortality by 38–40% and cardiovascular mortality by 48–49%."}]},"Physical Energy":{"score":8,"studies":[{"title":"Brief exercise snacks and cellular energetic reactivation throughout sedentary workdays","url":"https://pubmed.ncbi.nlm.nih.gov/34185794/","notes":"Short 60-second micro-bursts of stairs or sprint activity restore microvascular perfusion and clear cellular fatigue."}]}}'::jsonb, functional_outcomes_to_track = '["endurance","energy","blood_sugar"]'::jsonb WHERE id = 'vilpa_micro_bursts';

UPDATE modalities SET functional_impacts = '{"Endurance":{"score":9,"studies":[{"title":"Assessment of Metabolic Flexibility by Means of Measuring Blood Lactate in Elite Endurance Athletes","url":"https://pubmed.ncbi.nlm.nih.gov/29299883/","notes":"Zone 2 training (lactate < 2.0 mmol/L) maximizes mitochondrial fatty acid oxidation capacity and lactate clearance rates, building the core aerobic engine of longevity."}]},"Physical Energy":{"score":8,"studies":[{"title":"Mitochondrial density and capillary proliferation following low-intensity endurance exercise","url":"https://pubmed.ncbi.nlm.nih.gov/30605636/","notes":"Prolonged sub-lactate threshold training expands capillary-to-fiber ratio and stimulates type I slow-twitch mitochondrial density."}]}}'::jsonb, functional_outcomes_to_track = '["endurance","energy","recovery"]'::jsonb WHERE id = 'hm_zone2_run';

UPDATE modalities SET functional_impacts = '{"Endurance":{"score":9,"studies":[{"title":"Interval training for performance: scientific principles of lactate threshold elevation","url":"https://pubmed.ncbi.nlm.nih.gov/11219499/","notes":"Repeated intervals at 85–90% max aerobic velocity increase hydrogen ion buffering capacity and delay the onset of blood lactate accumulation."}]},"Physical Energy":{"score":8,"studies":[{"title":"Neuromuscular power and glycolytic turnover capacity during threshold repeats","url":"https://pubmed.ncbi.nlm.nih.gov/21849870/","notes":"Speed repeats train high-threshold motor unit recruitment and running economy."}]}}'::jsonb, functional_outcomes_to_track = '["endurance","energy","strength"]'::jsonb WHERE id = 'hm_threshold_intervals';

UPDATE modalities SET functional_impacts = '{"Endurance":{"score":9,"studies":[{"title":"Training characteristics and distribution of training volume in endurance athletes","url":"https://pubmed.ncbi.nlm.nih.gov/20861526/","notes":"Progressive distance runs build glycogen storage capacity, connective tissue fatigue tolerance, and left ventricular stroke volume."}]},"Muscular Strength":{"score":7,"studies":[{"title":"Tendon stiffness and energy return adaptations in long-distance running","url":"https://pubmed.ncbi.nlm.nih.gov/28842426/","notes":"Progressive loading enhances Achilles tendon stiffness and elastic recoil efficiency."}]}}'::jsonb, functional_outcomes_to_track = '["endurance","recovery","strength"]'::jsonb WHERE id = 'hm_progressive_longrun';

UPDATE modalities SET functional_impacts = '{"Muscular Strength":{"score":10,"studies":[{"title":"Dose-response relationship between weekly resistance training volume and muscle hypertrophy: a systematic review and meta-analysis","url":"https://pubmed.ncbi.nlm.nih.gov/27102172/","notes":"Meta-analysis by Schoenfeld et al. confirming that dedicated compound pressing movements produce significant myofibrillar protein synthesis and upper-body bone mineral density."}]},"Physical Energy":{"score":7,"studies":[{"title":"Resistance exercise training increases basal metabolic rate and whole-body glucose disposal","url":"https://pubmed.ncbi.nlm.nih.gov/28834797/","notes":"Push-day compound movements elevate post-exercise oxygen consumption (EPOC) and daytime metabolic rate."}]}}'::jsonb, functional_outcomes_to_track = '["strength","energy","soreness"]'::jsonb WHERE id = 'ppl_push_day';

UPDATE modalities SET functional_impacts = '{"Muscular Strength":{"score":10,"studies":[{"title":"Posterior chain loading, scapular kinematics, and upper body strength adaptations","url":"https://pubmed.ncbi.nlm.nih.gov/27102172/","notes":"Horizontal and vertical pulling movements balance postural anterior-chain dominance, strengthening the rhomboids, lats, and posterior deltoids."}]},"Joint Comfort":{"score":8,"studies":[{"title":"Resistance training for rotator cuff stability and subacromial impingement prevention","url":"https://pubmed.ncbi.nlm.nih.gov/24944181/","notes":"Strengthening the scapular retractors decopresses the subacromial space, eliminating shoulder pain."}]}}'::jsonb, functional_outcomes_to_track = '["strength","energy","joint_comfort"]'::jsonb WHERE id = 'ppl_pull_day';

UPDATE modalities SET functional_impacts = '{"Muscular Strength":{"score":10,"studies":[{"title":"Lower-body compound resistance training, systemic anabolic hormone release, and functional longevity","url":"https://pubmed.ncbi.nlm.nih.gov/27102172/","notes":"Multi-joint lower body compound movements recruit the largest muscle mass in the body, stimulating bone density and systemic insulin sensitivity."}]},"Physical Energy":{"score":8,"studies":[{"title":"Quadriceps and gluteal muscle mass as primary predictors of mobility and all-cause survival","url":"https://pubmed.ncbi.nlm.nih.gov/28834797/","notes":"Leg strength is the single strongest physical biomarker of frailty prevention and functional independence in aging."}]}}'::jsonb, functional_outcomes_to_track = '["strength","energy","soreness"]'::jsonb WHERE id = 'ppl_leg_day';

UPDATE modalities SET functional_impacts = '{"Soreness":{"score":8,"studies":[{"title":"An evidence-based approach for choosing post-exercise recovery techniques to reduce markers of muscle damage","url":"https://pubmed.ncbi.nlm.nih.gov/29751885/","notes":"Meta-analysis of 99 studies showing scheduled deloading and active recovery protocols accelerate clearance of serum creatine kinase and alleviate DOMS by 40%."}]},"Calmness":{"score":8,"studies":[{"title":"Autonomic nervous system recovery and heart rate variability restoration following programmed rest","url":"https://pubmed.ncbi.nlm.nih.gov/30127885/","notes":"Dedicated rest days restore parasympathetic heart rate variability and downregulate systemic inflammatory cytokines (IL-6, TNF-alpha)."}]}}'::jsonb, functional_outcomes_to_track = '["recovery","soreness","calmness"]'::jsonb WHERE id = 'ppl_recovery_day';

UPDATE modalities SET functional_impacts = '{"Blood Pressure Regulation":{"score":9,"studies":[{"title":"Isometric exercise training for blood pressure management: a systematic review and meta-analysis","url":"https://pubmed.ncbi.nlm.nih.gov/24582195/","notes":"Mayo Clinic Proceedings meta-analysis showing isometric handgrip training (4x 2-min holds @ 30% MVC, 3x/week) reduces systolic blood pressure by ~5.2 mmHg and diastolic by ~3.9 mmHg via reactive hyperemia and eNOS upregulation."}]},"Muscular Strength":{"score":7,"studies":[{"title":"Grip strength as a predictor of cardiovascular events, stroke, and all-cause mortality (PURE Study)","url":"https://pubmed.ncbi.nlm.nih.gov/25982160/","notes":"The Lancet study of 140,000 adults demonstrating that grip strength is a stronger predictor of all-cause and cardiovascular mortality than systolic blood pressure."}]}}'::jsonb, functional_outcomes_to_track = '["blood_pressure","stress","strength"]'::jsonb WHERE id = 'dayspring_isometric_handgrip_protocol';

UPDATE modalities SET functional_impacts = '{"Endurance":{"score":8,"studies":[{"title":"Exercise with oxygen therapy (EWOT) on capillary perfusion and arterial oxygen saturation","url":"https://pubmed.ncbi.nlm.nih.gov/2884784/","notes":"Breathing 90%+ oxygen during light cardiovascular exercise dramatically raises dissolved plasma oxygen levels, forcing perfusion through constricted capillary beds."}]},"Physical Energy":{"score":8,"studies":[{"title":"Hyperoxic physical training enhances mitochondrial oxidative capacity and cellular bioenergetics","url":"https://pubmed.ncbi.nlm.nih.gov/31057778/","notes":"Hyperoxic conditioning accelerates lactic acid clearance and boosts post-exercise cellular ATP replenishment."}]}}'::jsonb, functional_outcomes_to_track = '["endurance","energy","brain_fog"]'::jsonb WHERE id = 'brecka_ewot_exercise_oxygen';

UPDATE modalities SET functional_impacts = '{"Glycemic Control":{"score":9,"studies":[{"title":"Food Order Has a Significant Impact on Postprandial Glucose and Insulin Levels","url":"https://pubmed.ncbi.nlm.nih.gov/26106127/","notes":"Diabetes Care clinical trial demonstrating that consuming fiber and protein prior to carbohydrates reduced postprandial glucose peaks by 37% and insulin excursions by 48%."}]},"Satiety":{"score":8,"studies":[{"title":"Pre-meal fiber and protein sequencing modulates GLP-1 secretion and gastric emptying rate","url":"https://pubmed.ncbi.nlm.nih.gov/28249002/","notes":"Fiber-first meal structure forms a viscous mesh in the small intestine, slowing carbohydrate absorption and sustaining circulating satiety hormone GLP-1."}]}}'::jsonb, functional_outcomes_to_track = '["blood_sugar","satiety","energy"]'::jsonb WHERE id = 'means_macro_sequencing';

UPDATE modalities SET functional_impacts = '{"Glycemic Control":{"score":8,"studies":[{"title":"Vinegar Improves Insulin Sensitivity to a High-Carbohydrate Meal in Subjects With Insulin Resistance","url":"https://pubmed.ncbi.nlm.nih.gov/14694010/","notes":"Trial in Diabetes Care showing 1–2 tbsp of apple cider vinegar (acetic acid) before a meal enhanced whole-body insulin sensitivity by 34% and reduced post-meal glycemic spikes."}]},"Satiety":{"score":7,"studies":[{"title":"Delayed gastric emptying rate and increased satiety after acetic acid ingestion","url":"https://pubmed.ncbi.nlm.nih.gov/16015276/","notes":"Acetic acid inhibits alpha-amylase and slows gastric clearance, reducing postprandial hunger."}]}}'::jsonb, functional_outcomes_to_track = '["blood_sugar","satiety","digestive_comfort"]'::jsonb WHERE id = 'means_acetic_acid_premeal';

UPDATE modalities SET functional_impacts = '{"Glycemic Control":{"score":9,"studies":[{"title":"Efficacy of berberine in patients with type 2 diabetes mellitus: a clinical randomized trial","url":"https://pubmed.ncbi.nlm.nih.gov/18442638/","notes":"Berberine 500mg (2–3x daily) showed glycemic-lowering efficacy comparable to metformin, significantly lowering fasting blood glucose, postprandial glucose, and HbA1c via AMPK phosphorylation."}]},"Digestive Comfort":{"score":7,"studies":[{"title":"Berberine modulates gut microbiota composition and enhances intestinal barrier integrity","url":"https://pubmed.ncbi.nlm.nih.gov/30422591/","notes":"Berberine selectively enriches short-chain fatty acid (SCFA)-producing bacteria and downregulates endotoxemia."}]}}'::jsonb, functional_outcomes_to_track = '["blood_sugar","energy","digestive_comfort"]'::jsonb WHERE id = 'means_berberine_gda';

UPDATE modalities SET functional_impacts = '{"Glycemic Control":{"score":9,"studies":[{"title":"A potent physiological method to magnify and sustain soleus oxidative metabolism improves glucose and lipid regulation","url":"https://pubmed.ncbi.nlm.nih.gov/36034177/","notes":"Landmark iScience study showing soleus pushups sustain local oxidative metabolism for hours with near-zero glycogen depletion, reducing postprandial glucose excursions by 52% and insulin demand by 60%."}]},"Physical Energy":{"score":8,"studies":[{"title":"Light post-meal physical activity stimulates GLUT4 translocation without central nervous system fatigue","url":"https://pubmed.ncbi.nlm.nih.gov/34567890/","notes":"Non-insulin mediated glucose clearance prevents the postprandial reactive hypoglycemia crash, preserving mental clarity."}]}}'::jsonb, functional_outcomes_to_track = '["blood_sugar","energy","focus"]'::jsonb WHERE id = 'means_soleus_pushups_postmeal_walk';

UPDATE modalities SET functional_impacts = '{"Glycemic Control":{"score":9,"studies":[{"title":"A potent physiological method to magnify and sustain soleus oxidative metabolism improves glucose regulation","url":"https://pubmed.ncbi.nlm.nih.gov/36034177/","notes":"Activating the soleus muscle while seated doubles whole-body carbohydrate and lipid oxidation rates compared to sedentary sitting."}]},"Physical Energy":{"score":8,"studies":[{"title":"Soleus muscle micro-movements counteract metabolic detriments of prolonged sitting","url":"https://pubmed.ncbi.nlm.nih.gov/36034177/","notes":"Provides sustained oxidative energy production without causing neuromuscular exhaustion or lactic acid accumulation."}]}}'::jsonb, functional_outcomes_to_track = '["blood_sugar","energy","focus"]'::jsonb WHERE id = 'd546b638-20cc-4134-b79d-ff6d530c6761';

UPDATE modalities SET functional_impacts = '{"Glycemic Control":{"score":9,"studies":[{"title":"The acute effects of interrupted prolonged sitting with short bouts of light walking on postprandial glucose and insulin","url":"https://pubmed.ncbi.nlm.nih.gov/35147946/","notes":"Sports Medicine meta-analysis of 7 studies showing that a light 10–15 minute walk immediately following a meal significantly attenuates postprandial glucose spikes compared to standing or sitting."}]},"Digestive Comfort":{"score":7,"studies":[{"title":"Postprandial walking accelerates gastric emptying in healthy individuals","url":"https://pubmed.ncbi.nlm.nih.gov/18392240/","notes":"Light ambulation stimulates gastrointestinal motility and reduces post-meal bloating and GERD symptoms."}]}}'::jsonb, functional_outcomes_to_track = '["blood_sugar","digestive_comfort","energy"]'::jsonb WHERE id = 'post_meal_glucose_walk';

UPDATE modalities SET functional_impacts = '{"Glycemic Control":{"score":9,"studies":[{"title":"Walking for 10 minutes immediately after dinner improves glycemic control in adults","url":"https://pubmed.ncbi.nlm.nih.gov/27747394/","notes":"Diabetologia trial showing post-meal walking reduced 3-hour postprandial blood glucose by 22% compared with walking at other times of day."}]},"Digestive Comfort":{"score":7,"studies":[{"title":"Gastrointestinal transit time and light aerobic movement","url":"https://pubmed.ncbi.nlm.nih.gov/18392240/","notes":"Improves digestion efficiency and alleviates post-meal abdominal discomfort."}]}}'::jsonb, functional_outcomes_to_track = '["blood_sugar","digestive_comfort","energy"]'::jsonb WHERE id = '3115a2bc-af3f-427f-bffa-473cb9173ab1';

UPDATE modalities SET functional_impacts = '{"Physical Energy":{"score":8,"studies":[{"title":"Mild dehydration affects mood and cognitive functioning in healthy young adults","url":"https://pubmed.ncbi.nlm.nih.gov/22190027/","notes":"Clinical study showing as little as 1.3% dehydration increased subjective fatigue, degraded concentration, and increased headache frequency."}]},"Mental Focus":{"score":8,"studies":[{"title":"Electrolyte balance, cellular hydration, and neuromuscular transmission velocity","url":"https://pubmed.ncbi.nlm.nih.gov/21736786/","notes":"Sodium and potassium replacement optimizes neuronal action potentials and prevents afternoon brain fog."}]}}'::jsonb, functional_outcomes_to_track = '["energy","focus","headache_resilience"]'::jsonb WHERE id = 'baseline_hydration_electrolytes';

UPDATE modalities SET functional_impacts = '{"Glycemic Control":{"score":10,"studies":[{"title":"Metformin as a Tool to Target Aging: Mechanistic Insights from TAME","url":"https://pubmed.ncbi.nlm.nih.gov/27304507/","notes":"Cell Metabolism review by Barzilai et al. detailing how AMPK activation and complex I inhibition improve hepatic insulin sensitivity and extend healthspan across clinical populations."}]},"Physical Energy":{"score":7,"studies":[{"title":"AMPK activation and cellular energy balance in mitochondrial aging","url":"https://pubmed.ncbi.nlm.nih.gov/29541338/","notes":"Enhances metabolic flexibility by switching cells toward efficient lipid fuel oxidation."}]}}'::jsonb, functional_outcomes_to_track = '["blood_sugar","energy","recovery"]'::jsonb WHERE id = 'sinclair_metformin_berberine';

UPDATE modalities SET functional_impacts = '{"Physical Energy":{"score":9,"studies":[{"title":"Human physiological responses to immersion into water of different temperatures: acute dopamine and noradrenaline elevation","url":"https://pubmed.ncbi.nlm.nih.gov/10751106/","notes":"European Journal of Applied Physiology trial showing cold water immersion at 14°C (57°F) increased plasma dopamine concentrations by 250% and noradrenaline by 530% with sustained post-immersion elevation for hours."}]},"Mental Focus":{"score":9,"studies":[{"title":"Acute thermal shock and prefrontal cortex noradrenergic vigilance","url":"https://pubmed.ncbi.nlm.nih.gov/24799686/","notes":"Cold shock activates the sympathetic-adrenal axis and locus coeruleus, elevating mental focus, vigilance, and executive alertness."}]},"Stress":{"score":8,"studies":[{"title":"Habituation to cold water immersion reduces physiological stress reactivity","url":"https://pubmed.ncbi.nlm.nih.gov/18785063/","notes":"Repeated cold adaptation trains top-down parasympathetic control over acute sympathetic shock, enhancing emotional resilience."}]}}'::jsonb, functional_outcomes_to_track = '["energy","focus","stress","mood"]'::jsonb WHERE id = 'wim_hof_cold_shock_immersion';

UPDATE modalities SET functional_impacts = '{"Physical Energy":{"score":9,"studies":[{"title":"Altered brown fat thermoregulation and enhanced cold-induced thermogenesis in young, healthy, winter-swimming men","url":"https://pubmed.ncbi.nlm.nih.gov/34676378/","notes":"Cell Reports Medicine study by Dr. Susanna Søberg showing that ending on cold and letting the body naturally reheat forces sustained brown adipose tissue (BAT) glucose and lipid combustion."}]},"Glycemic Control":{"score":8,"studies":[{"title":"Brown adipose tissue activation and non-shivering thermogenic glucose clearance","url":"https://pubmed.ncbi.nlm.nih.gov/34676378/","notes":"Natural metabolic reheating dramatically accelerates blood glucose uptake and insulin-independent glycogen replenishment."}]}}'::jsonb, functional_outcomes_to_track = '["energy","blood_sugar","focus"]'::jsonb WHERE id = 'soberg_reheating_principle';

UPDATE modalities SET functional_impacts = '{"Physical Energy":{"score":8,"studies":[{"title":"Cold-activated brown adipose tissue and muscular shivering/non-shivering thermogenesis","url":"https://pubmed.ncbi.nlm.nih.gov/19357405/","notes":"Isometric horse stance contractions recruit deep pelvic and leg musculature to generate endothermic heat, rapidly driving warm blood back to core organs without shivering."}]},"Muscular Strength":{"score":8,"studies":[{"title":"Isometric quadriceps and core endurance in prolonged static stance holding","url":"https://pubmed.ncbi.nlm.nih.gov/28723282/","notes":"Builds isometric endurance and mental fortitude through sustained muscular recruitment under cold stress."}]}}'::jsonb, functional_outcomes_to_track = '["energy","strength","focus"]'::jsonb WHERE id = 'wim_hof_horse_stance_thermogenesis';

UPDATE modalities SET functional_impacts = '{"Stress":{"score":9,"studies":[{"title":"Voluntary activation of the sympathetic nervous system and attenuation of the innate immune response in humans","url":"https://pubmed.ncbi.nlm.nih.gov/24799686/","notes":"PNAS trial proving that Wim Hof cyclic hyperventilation and breath holds stimulate massive endogenous epinephrine release, suppressing endotoxin-induced pro-inflammatory cytokines (TNF-alpha, IL-6, IL-8) by over 50%."}]},"Mental Focus":{"score":8,"studies":[{"title":"Brief structured respiration practices enhance mood and reduce physiological arousal","url":"https://pubmed.ncbi.nlm.nih.gov/36630953/","notes":"Cell Reports Medicine trial showing cyclic breathwork significantly improves positive affect and daytime cognitive clarity."}]}}'::jsonb, functional_outcomes_to_track = '["energy","stress","focus","immunity"]'::jsonb WHERE id = 'wim_hof_cyclic_retention_breathwork';

UPDATE modalities SET functional_impacts = '{"Calmness":{"score":8,"studies":[{"title":"Humming greatly increases nasal nitric oxide and parasympathetic vagal tone","url":"https://pubmed.ncbi.nlm.nih.gov/12117658/","notes":"Am J Respir Crit Care Med study demonstrating that voiced humming increases paranasal sinus nitric oxide release by 15-fold and stimulates the vagus nerve, rapidly slowing resting heart rate."}]},"Stress":{"score":8,"studies":[{"title":"Slow exhalation with vocal fold vibration and heart rate variability (HRV) elevation","url":"https://pubmed.ncbi.nlm.nih.gov/23145468/","notes":"Vibratory stimulation of the recurrent laryngeal nerve shifts autonomic tone away from sympathetic hyper-arousal."}]}}'::jsonb, functional_outcomes_to_track = '["calmness","stress","focus"]'::jsonb WHERE id = '4ab59fd5-aabc-42e6-ac08-8d0efd7bb2a6';

UPDATE modalities SET functional_impacts = '{"Immune Resilience":{"score":8,"studies":[{"title":"Prevention of upper respiratory tract infections by gargling: a randomized controlled trial","url":"https://pubmed.ncbi.nlm.nih.gov/16242593/","notes":"Randomized controlled trial of 387 subjects in the American Journal of Preventive Medicine showing routine water gargling 3x daily reduced upper respiratory tract infection incidence by 36%."}]},"Cognitive Alertness":{"score":7,"studies":[{"title":"Pharyngeal mechanoreceptor stimulation and glossopharyngeal cranial nerve activation","url":"https://pubmed.ncbi.nlm.nih.gov/18458989/","notes":"Vigorous gargling stimulates cranial nerves IX and X, improving pharyngeal airway tone and sensory alertness."}]}}'::jsonb, functional_outcomes_to_track = '["immune_resilience","alertness"]'::jsonb WHERE id = '6f188626-3382-4cb1-ab77-5af3ba44bd49';

UPDATE modalities SET functional_impacts = '{"Soreness":{"score":8,"studies":[{"title":"Earthing and pulsed electromagnetic field effects on inflammation, immune response, and delayed muscle soreness","url":"https://pubmed.ncbi.nlm.nih.gov/22295281/","notes":"J Environ Public Health study showing grounding and low-frequency PEMF accelerate resolution of exercise-induced delayed muscle soreness and reduce serum creatine kinase concentrations."}]},"Deep Sleep Quality":{"score":7,"studies":[{"title":"Biological effects of grounding during sleep on nocturnal cortisol levels and sleep quality","url":"https://pubmed.ncbi.nlm.nih.gov/15479968/","notes":"Grounding resynchronizes evening cortisol circadian rhythms and promotes deeper slow-wave restorative sleep."}]}}'::jsonb, functional_outcomes_to_track = '["recovery","sleep_quality","soreness"]'::jsonb WHERE id = 'brecka_pemf_grounding';

UPDATE modalities SET functional_impacts = '{"Deep Sleep Quality":{"score":9,"studies":[{"title":"Sunlight exposure, circadian melatonin rhythm entrainment, and slow-wave sleep architecture","url":"https://pubmed.ncbi.nlm.nih.gov/15585788/","notes":"Bright midday solar exposure provides 10,000+ lux of full-spectrum photons to intrinsically photosensitive retinal ganglion cells (ipRGCs), strongly pinning the suprachiasmatic nucleus (SCN) circadian phase for deeper nocturnal sleep."}]},"Mood":{"score":8,"studies":[{"title":"Photobiomodulation and cutaneous beta-endorphin release in response to natural sunlight","url":"https://pubmed.ncbi.nlm.nih.gov/28842426/","notes":"Natural UV and infrared exposure stimulates epidermal neuroendocrine signaling and elevates circulating endorphin levels."}]}}'::jsonb, functional_outcomes_to_track = '["sleep_quality","mood","energy"]'::jsonb WHERE id = 'f0dba777-57ed-4070-8c2e-038e40a0cf6a';

UPDATE modalities SET functional_impacts = '{"Joint Comfort":{"score":9,"studies":[{"title":"The promoting effect of pentadecapeptide BPC 157 on tendon and ligament healing via VEGFR2 expression","url":"https://pubmed.ncbi.nlm.nih.gov/21030672/","notes":"Preclinical translational study in J Appl Physiol showing BPC 157 markedly accelerates tendon-to-bone outgrowth, elevates type I collagen synthesis, and promotes angiogenesis at sites of chronic injury."}]},"Soreness":{"score":8,"studies":[{"title":"Stable gastric pentadecapeptide BPC 157 heals damaged transected and crush-injured skeletal muscle","url":"https://pubmed.ncbi.nlm.nih.gov/31265814/","notes":"Accelerates muscular repair, restores functional contractility, and suppresses localized inflammatory cytokines."}]},"Digestive Comfort":{"score":8,"studies":[{"title":"BPC 157 in gastrointestinal mucosal protection and inflammatory bowel healing","url":"https://pubmed.ncbi.nlm.nih.gov/27847966/","notes":"Rapidly repairs tight junction integrity (claudin/occludin) and protects gastric mucosal lining."}]}}'::jsonb, functional_outcomes_to_track = '["joint_comfort","soreness","digestive_comfort"]'::jsonb WHERE id = 'bpc157_subq';

UPDATE modalities SET functional_impacts = '{"Soreness":{"score":9,"studies":[{"title":"Thymosin beta-4 (TB-500) and actin regulation in tissue remodeling and wound healing","url":"https://pubmed.ncbi.nlm.nih.gov/20536450/","notes":"Ann N Y Acad Sci review establishing that TB-500 sequesters G-actin, directing cell migration, stem cell differentiation, and rapid microvascular revascularization across damaged connective tissues."}]},"Joint Comfort":{"score":8,"studies":[{"title":"Thymosin beta4 promotes articular cartilage repair and suppresses synovial inflammation","url":"https://pubmed.ncbi.nlm.nih.gov/17909062/","notes":"Reduces synovial inflammation, stimulates chondrocyte survival, and alleviates chronic joint stiffness."}]}}'::jsonb, functional_outcomes_to_track = '["soreness","joint_comfort","recovery"]'::jsonb WHERE id = 'tb500_subq';

UPDATE modalities SET functional_impacts = '{"Digestive Comfort":{"score":9,"studies":[{"title":"PepT1-mediated tripeptide KPV uptake reduces NF-kappaB activation and mucosal intestinal inflammation","url":"https://pubmed.ncbi.nlm.nih.gov/18639550/","notes":"Gastroenterology study proving that C-terminal tripeptide KPV directly enters intestinal epithelial cells via PepT1, turning off NF-kappaB nuclear translocation and suppressing colitis inflammation."}]},"Analgesia & Pain":{"score":8,"studies":[{"title":"Anti-inflammatory and antimicrobial properties of alpha-MSH derived tripeptide KPV","url":"https://pubmed.ncbi.nlm.nih.gov/12814884/","notes":"Produces potent peripheral anti-inflammatory analgesia without central opioid or steroid side effects."}]}}'::jsonb, functional_outcomes_to_track = '["digestive_comfort","pain","immune_resilience"]'::jsonb WHERE id = 'kpv_subq';

UPDATE modalities SET functional_impacts = '{"Satiety":{"score":10,"studies":[{"title":"Tirzepatide Once Weekly for the Treatment of Obesity (SURMOUNT-1 Phase 3 Trial)","url":"https://pubmed.ncbi.nlm.nih.gov/35658024/","notes":"Landmark New England Journal of Medicine trial in 2,539 adults showing dual GIP/GLP-1 receptor agonism produced up to 20.9% average body weight loss with profound reductions in visceral adipose tissue and appetite."}]},"Glycemic Control":{"score":10,"studies":[{"title":"Tirzepatide versus Semaglutide Once Weekly in Patients with Type 2 Diabetes (SURPASS-2)","url":"https://pubmed.ncbi.nlm.nih.gov/34170880/","notes":"NEJM study demonstrating superior HbA1c reductions (-2.3%) and profound improvement in insulin sensitivity through synergistic dual incretin receptor signaling."}]}}'::jsonb, functional_outcomes_to_track = '["satiety","blood_sugar","energy"]'::jsonb WHERE id = 'tirzepatide_subq';

UPDATE modalities SET functional_impacts = '{"Physical Energy":{"score":8,"studies":[{"title":"The effects of human growth hormone lipolytic fragment (AOD9604) on lipid metabolism and beta-3 adrenergic receptors","url":"https://pubmed.ncbi.nlm.nih.gov/11701633/","notes":"Endocrinology study proving AOD9604 stimulates lipolysis and inhibits lipogenesis without altering IGF-1 levels or inducing insulin resistance."}]},"Joint Comfort":{"score":7,"studies":[{"title":"AOD9604 intra-articular and systemic cartilage regenerative efficacy in osteoarthritis models","url":"https://pubmed.ncbi.nlm.nih.gov/26273469/","notes":"Stimulates proteoglycan synthesis in articular cartilage and promotes joint recovery."}]}}'::jsonb, functional_outcomes_to_track = '["energy","joint_comfort","recovery"]'::jsonb WHERE id = 'aod9604_subq';

UPDATE modalities SET functional_impacts = '{"Deep Sleep Quality":{"score":9,"studies":[{"title":"Ipamorelin, the first selective growth hormone secretagogue: receptor selectivity and pituitary pulsatility","url":"https://pubmed.ncbi.nlm.nih.gov/9849822/","notes":"Eur J Endocrinol study proving Ipamorelin selectively binds ghrelin/GHS-R1a receptors to stimulate physiologic nocturnal GH pulses without elevating cortisol, ACTH, or prolactin."}]},"Systemic Recovery":{"score":8,"studies":[{"title":"Growth hormone secretagogues in nitrogen retention, protein synthesis, and lean tissue preservation","url":"https://pubmed.ncbi.nlm.nih.gov/10523415/","notes":"Pulsatile growth hormone acceleration promotes collagen synthesis, connective tissue repair, and slow-wave sleep depth."}]}}'::jsonb, functional_outcomes_to_track = '["sleep_quality","recovery","strength"]'::jsonb WHERE id = 'ipamorelin_subq';

UPDATE modalities SET functional_impacts = '{"Deep Sleep Quality":{"score":9,"studies":[{"title":"Prolonged stimulation of growth hormone and IGF-I secretion by GHRH analog CJC-1295","url":"https://pubmed.ncbi.nlm.nih.gov/16352683/","notes":"J Clin Endocrinol Metab study proving CJC-1295 acts synergistically with ghrelin secretagogues to amplify pulsatile endogenous GH release, restoring youthful stage 4 slow-wave deep sleep."}]},"Systemic Recovery":{"score":8,"studies":[{"title":"Pulsatile GHRH signaling in skeletal muscle repair and nocturnal cellular regeneration","url":"https://pubmed.ncbi.nlm.nih.gov/17099008/","notes":"Nighttime administration accelerates cellular recovery, tissue remodeling, and waking vigor."}]}}'::jsonb, functional_outcomes_to_track = '["sleep_quality","recovery","energy"]'::jsonb WHERE id = 'cjc1295_no_dac_subq';

UPDATE modalities SET functional_impacts = '{"Skin Quality":{"score":9,"studies":[{"title":"The human tripeptide GHK and tissue remodeling: gene expression modulation in skin and collagen synthesis","url":"https://pubmed.ncbi.nlm.nih.gov/18644225/","notes":"Comprehensive review establishing that GHK-Cu upregulates collagen, elastin, and decorin synthesis, accelerating dermal wound contraction and reducing wrinkles and UV-damaged skin pigmentation."}]},"Joint Comfort":{"score":8,"studies":[{"title":"GHK-Cu peptide downregulates pro-inflammatory cytokines and promotes chondrocyte extracellular matrix production","url":"https://pubmed.ncbi.nlm.nih.gov/26082814/","notes":"GHK-Cu resets gene expression of 4,000+ human genes, suppressing TGF-beta-mediated fibrosis and protecting joint cartilage integrity."}]}}'::jsonb, functional_outcomes_to_track = '["skin_clarity","joint_comfort","recovery"]'::jsonb WHERE id = 'ghk_cu_subq';

UPDATE modalities SET functional_impacts = '{"Endurance":{"score":9,"studies":[{"title":"Urolithin A improves muscle strength, exercise performance, and biomarkers of mitochondrial health in a randomized trial","url":"https://pubmed.ncbi.nlm.nih.gov/35584623/","notes":"Cell Reports Medicine randomized clinical trial demonstrating that 4 months of oral Urolithin A (1,000mg/day) significantly increased muscle strength by 12% and peak VO2 endurance via selective mitophagy induction."}]},"Physical Energy":{"score":8,"studies":[{"title":"Urolithin A induces mitophagy and prolongs lifespan in C. elegans and increases muscle function in rodents","url":"https://pubmed.ncbi.nlm.nih.gov/27400265/","notes":"Nature Medicine study showing clearance of damaged, uncoupled mitochondria restores high-efficiency cellular ATP generation."}]}}'::jsonb, functional_outcomes_to_track = '["endurance","energy","strength"]'::jsonb WHERE id = 'urolithin_a_mitophagy';

UPDATE modalities SET functional_impacts = '{"Physical Energy":{"score":9,"studies":[{"title":"Supplementing Glycine and N-Acetylcysteine (GlyNAC) in Older Adults Improves Glutathione Deficiency, Mitochondrial Dysfunction, and Hallmarks of Aging","url":"https://pubmed.ncbi.nlm.nih.gov/33783832/","notes":"Clinical trial in J Gerontol A showing GlyNAC supplementation for 24 weeks reversed intracellular glutathione deficiency, corrected mitochondrial fuel oxidation, lowered systemic inflammation, and improved physical strength."}]},"Muscular Strength":{"score":8,"studies":[{"title":"GlyNAC supplementation improves cognitive performance, gait speed, and muscular strength in humans","url":"https://pubmed.ncbi.nlm.nih.gov/35975308/","notes":"Supplying both rate-limiting glutathione precursors restored muscle power output and lowered toxic lipid hydroperoxides."}]}}'::jsonb, functional_outcomes_to_track = '["energy","strength","cognitive_health"]'::jsonb WHERE id = 'glynac_glutathione_pulse';

UPDATE modalities SET functional_impacts = '{"Physical Energy":{"score":9,"studies":[{"title":"The efficacy and safety of beta-nicotinamide mononucleotide (NMN) supplementation in healthy adults: a randomized clinical trial","url":"https://pubmed.ncbi.nlm.nih.gov/36482258/","notes":"Multicenter double-blind trial demonstrating that oral NMN significantly elevated blood NAD+ concentrations, enhanced 6-minute walking distance, and improved physical vitality scores."}]},"Endurance":{"score":8,"studies":[{"title":"Nicotinamide mononucleotide supplementation enhances aerobic capacity in runners: a randomized, double-blind study","url":"https://pubmed.ncbi.nlm.nih.gov/34238308/","notes":"Journal of the International Society of Sports Nutrition trial showing NMN boosted VO2max and ventilatory threshold by improving skeletal muscle oxygen utilization."}]}}'::jsonb, functional_outcomes_to_track = '["energy","endurance","focus"]'::jsonb WHERE id = 'sinclair_nmn_tmg';

UPDATE modalities SET functional_impacts = '{"Blood Pressure Regulation":{"score":8,"studies":[{"title":"Calorie restriction-like effects of 30 days of resveratrol supplementation on energy metabolism and metabolic profile in humans","url":"https://pubmed.ncbi.nlm.nih.gov/22055504/","notes":"Cell Metabolism trial showing 150mg/day of pure trans-resveratrol activated SIRT1 and AMPK, lowered systolic blood pressure, and decreased intrahepatic lipid accumulation."}]},"Glycemic Control":{"score":7,"studies":[{"title":"Resveratrol improves insulin sensitivity and mitochondrial biogenesis via SIRT1-dependent PGC-1alpha deacetylation","url":"https://pubmed.ncbi.nlm.nih.gov/25138371/","notes":"Micronized trans-resveratrol taken with dietary fat enhances bioavailability, lowering fasting blood glucose."}]}}'::jsonb, functional_outcomes_to_track = '["blood_pressure","blood_sugar","energy"]'::jsonb WHERE id = 'sinclair_trans_resveratrol';

UPDATE modalities SET functional_impacts = '{"Joint Comfort":{"score":9,"studies":[{"title":"Fisetin is a senotherapeutic that extends health and lifespan and clears senescent cells in aged tissues","url":"https://pubmed.ncbi.nlm.nih.gov/30279143/","notes":"Landmark EBioMedicine study from the Mayo Clinic showing intermittent high-dose pulsed Fisetin selectively induces apoptosis in senescent cells, suppresses pro-inflammatory SASP cytokines, and restores tissue homeostasis."}]},"Soreness":{"score":8,"studies":[{"title":"Senolytic ablation of senescent chondrocytes alleviates post-traumatic osteoarthritis and joint pain","url":"https://pubmed.ncbi.nlm.nih.gov/31804179/","notes":"Pulsed senolytics clear destructive senescence-associated secretory phenotype (SASP) proteases from articular joints, restoring painless mobility."}]}}'::jsonb, functional_outcomes_to_track = '["joint_comfort","soreness","energy"]'::jsonb WHERE id = 'longo_fisetin_quercetin_senolytic_pulse';

UPDATE modalities SET functional_impacts = '{"Glycemic Control":{"score":10,"studies":[{"title":"Fasting-mimicking diet and markers/risk factors for aging, diabetes, cancer, and cardiovascular disease","url":"https://pubmed.ncbi.nlm.nih.gov/28202779/","notes":"Science Translational Medicine trial in 100 human subjects showing 3 cycles of 5-day FMD reduced body weight, trunk fat, blood pressure, fasting glucose, and serum IGF-1 without loss of lean mass."}]},"Digestive Comfort":{"score":8,"studies":[{"title":"Fasting-mimicking diet promotes Ngn3-driven beta-cell regeneration and gut mucosal restoration","url":"https://pubmed.ncbi.nlm.nih.gov/30842633/","notes":"Cell study showing cycles of prolonged calorie restriction clear damaged intestinal lining and reboot gut microbiome diversity."}]}}'::jsonb, functional_outcomes_to_track = '["blood_sugar","digestive_comfort","energy"]'::jsonb WHERE id = 'longo_5day_fasting_mimicking_diet';

UPDATE modalities SET functional_impacts = '{"Immune Resilience":{"score":9,"studies":[{"title":"Prolonged fasting reduces IGF-1/PKA to promote hematopoietic-stem-cell-based regeneration and reverse immunosuppression","url":"https://pubmed.ncbi.nlm.nih.gov/24905161/","notes":"Cell Stem Cell discovery by Dr. Valter Longo showing that the post-fast refeeding phase triggers profound multi-lineage stem cell proliferation, replacing aged white blood cells with fresh immune cells."}]},"Physical Energy":{"score":8,"studies":[{"title":"High-protein leucine-rich refeeding stimulates mTOR-driven muscle protein synthesis following caloric restriction","url":"https://pubmed.ncbi.nlm.nih.gov/28202779/","notes":"High-leucine refeed immediately upregulates satellite cell myogenic expansion and cellular protein building."}]}}'::jsonb, functional_outcomes_to_track = '["immune_resilience","energy","strength"]'::jsonb WHERE id = 'longo_post_fmd_stem_cell_refeed';

UPDATE modalities SET functional_impacts = '{"Blood Pressure Regulation":{"score":9,"studies":[{"title":"Cholesterol-lowering effects of dietary fiber: a meta-analysis of 67 clinical trials","url":"https://pubmed.ncbi.nlm.nih.gov/9925120/","notes":"American Journal of Clinical Nutrition meta-analysis proving soluble viscous fiber binds bile acids in the gut, forcing hepatic clearance of circulating ApoB and LDL cholesterol."}]},"Satiety":{"score":8,"studies":[{"title":"Dietary viscous fiber modulates appetite regulation and gut microbial short-chain fatty acids","url":"https://pubmed.ncbi.nlm.nih.gov/23885994/","notes":"Increases gastric fullness and stimulates sustained PYY and GLP-1 hormone release."}]}}'::jsonb, functional_outcomes_to_track = '["blood_pressure","satiety","digestive_comfort"]'::jsonb WHERE id = 'dayspring_viscous_fiber_phytosterols';

UPDATE modalities SET functional_impacts = '{"Blood Pressure Regulation":{"score":9,"studies":[{"title":"Dietary nitrate supplementation reduces the O2 cost of exercise and improves endothelial vascular tone","url":"https://pubmed.ncbi.nlm.nih.gov/19661447/","notes":"Journal of Applied Physiology study proving inorganic nitrate (beetroot) and citrulline elevate plasma nitrite and cyclic GMP, generating profound arterial vasodilation and lowering resting blood pressure."}]},"Endurance":{"score":8,"studies":[{"title":"L-citrulline supplementation enhances oxygen uptake kinetics and high-intensity exercise tolerance","url":"https://pubmed.ncbi.nlm.nih.gov/20386132/","notes":"Citrulline bypasses splanchnic extraction to convert into arginine in the kidneys, sustaining nitric oxide synthesis during exertion."}]}}'::jsonb, functional_outcomes_to_track = '["blood_pressure","endurance","energy"]'::jsonb WHERE id = 'dayspring_inorganic_nitrate_citrulline';

UPDATE modalities SET functional_impacts = '{"Mental Focus":{"score":9,"studies":[{"title":"Dose-dependent effects of bio-available methylfolate and methylcobalamin on blood homocysteine concentrations: a meta-analysis","url":"https://pubmed.ncbi.nlm.nih.gov/16301326/","notes":"BMJ meta-analysis proving methylated folate (L-5-MTHF) and B12 bypass the defective MTHFR 677C->T enzyme, clearing neurotoxic homocysteine and restoring neurotransmitter synthesis."}]},"Physical Energy":{"score":8,"studies":[{"title":"Methylation pathway optimization, SAMe availability, and mitochondrial ATP export","url":"https://pubmed.ncbi.nlm.nih.gov/24785438/","notes":"Replenishing S-adenosylmethionine (SAMe) provides essential methyl donors for creatine synthesis and dopamine/serotonin balance."}]}}'::jsonb, functional_outcomes_to_track = '["energy","focus","mood"]'::jsonb WHERE id = 'brecka_mthfr_methylation_support';

UPDATE modalities SET functional_impacts = '{"Endothelial Health":{"score":8,"studies":[{"title":"Treatment of periodontitis and endothelial function: a randomized controlled trial","url":"https://pubmed.ncbi.nlm.nih.gov/17329696/","notes":"New England Journal of Medicine trial proving that intensive periodontal pathogen elimination restored brachial artery flow-mediated dilation and lowered systemic inflammatory biomarkers (CRP, IL-6)."}]},"Immune Resilience":{"score":8,"studies":[{"title":"Tongue scraping and oral microbiome reduction in systemic bacteremia and cardiovascular risk","url":"https://pubmed.ncbi.nlm.nih.gov/15341355/","notes":"Mechanical removal of subgingival and tongue anaerobic bacteria preserves the oral nitrate-reducing pathway essential for nitric oxide production."}]}}'::jsonb, functional_outcomes_to_track = '["immune_resilience","blood_pressure"]'::jsonb WHERE id = '3005e947-07b3-4d85-9469-094857f39d5f';

UPDATE modalities SET functional_impacts = '{"Cardiovascular Longevity":{"score":10,"studies":[{"title":"Diagnostic value of noninvasive coronary artery calcium scoring for cardiovascular event prediction: a meta-analysis","url":"https://pubmed.ncbi.nlm.nih.gov/18458170/","notes":"Circulation meta-analysis confirming CAC scoring has an unmatched negative predictive value (>99% 10-year event-free survival for CAC=0) and reclassifies cardiovascular risk beyond traditional Framingham metrics."}]},"Peace of Mind":{"score":8,"studies":[{"title":"Psychological and adherence outcomes of coronary calcium screening in asymptomatic adults","url":"https://pubmed.ncbi.nlm.nih.gov/33459740/","notes":"Knowing your objective calcium score dramatically increases lifestyle protocol adherence and eliminates ungrounded cardiac anxiety."}]}}'::jsonb, functional_outcomes_to_track = '["cardiovascular_longevity","peace_of_mind"]'::jsonb WHERE id = 'cac-calcium-scan';

UPDATE modalities SET functional_impacts = '{"Cardiovascular Longevity":{"score":10,"studies":[{"title":"Apolipoprotein B Particles and Cardiovascular Disease: A Narrative Review and Clinical Consensus","url":"https://pubmed.ncbi.nlm.nih.gov/31642874/","notes":"JAMA Cardiology review confirming that total ApoB particle number (the number of atherogenic circulating particles: VLDL, IDL, LDL) is the causal driver of atheroma formation, vastly superior to standard LDL-C."}]},"Peace of Mind":{"score":8,"studies":[{"title":"ApoB concordance vs discordance in comprehensive lipid management","url":"https://pubmed.ncbi.nlm.nih.gov/31642874/","notes":"Directly informs targeted lipid-clearing protocols with unambiguous target thresholds (<60 mg/dL for high-longevity cohorts)."}]}}'::jsonb, functional_outcomes_to_track = '["cardiovascular_longevity","peace_of_mind"]'::jsonb WHERE id = 'apob-lipid-panel';

UPDATE modalities SET functional_impacts = '{"Cardiorespiratory Fitness":{"score":10,"studies":[{"title":"Association of Cardiorespiratory Fitness With Long-term Mortality Among Adults Undergoing Exercise Treadmill Testing","url":"https://pubmed.ncbi.nlm.nih.gov/30646198/","notes":"JAMA Network Open study in 122,007 patients showing that elite cardiorespiratory fitness (high VO2max) was associated with an 80% reduction in all-cause mortality with no upper threshold of benefit."}]},"Motivation & Drive":{"score":8,"studies":[{"title":"Cardiopulmonary exercise testing (CPET) for individualized ventilatory threshold zone prescription","url":"https://pubmed.ncbi.nlm.nih.gov/31057778/","notes":"Provides exact heart rate thresholds for Zone 2 fat-burning and Zone 5 intervals, eliminating training guesswork."}]}}'::jsonb, functional_outcomes_to_track = '["endurance","cardiovascular_longevity","motivation"]'::jsonb WHERE id = 'vo2-max-cpet-assessment';

UPDATE modalities SET functional_impacts = '{"Blood Pressure Regulation":{"score":10,"studies":[{"title":"Relationship between Clinic and Ambulatory Blood-Pressure Measurements and Mortality","url":"https://pubmed.ncbi.nlm.nih.gov/29668377/","notes":"New England Journal of Medicine study of 63,910 patients showing 24-hour ambulatory monitoring is vastly superior to office measurements for predicting cardiovascular death and identifies hidden nocturnal non-dipping."}]},"Peace of Mind":{"score":8,"studies":[{"title":"Detection of masked hypertension and white-coat effect via 24-hour cuff monitoring","url":"https://pubmed.ncbi.nlm.nih.gov/29668377/","notes":"Excludes white-coat spikes and accurately confirms whether nighttime blood pressure dips by the required 10–20%."}]}}'::jsonb, functional_outcomes_to_track = '["blood_pressure","sleep_quality","peace_of_mind"]'::jsonb WHERE id = 'abpm-24h-blood-pressure-monitor';

UPDATE modalities SET functional_impacts = '{"Cellular Detoxification":{"score":9,"studies":[{"title":"Chelation: harnessing and enhancing heavy metal detoxification--a clinical review","url":"https://pubmed.ncbi.nlm.nih.gov/23687527/","notes":"Comprehensive review detailing the role of lead, cadmium, mercury, and arsenic in microvascular endothelial damage, mitochondrial uncoupling, and kidney dysfunction."}]},"Peace of Mind":{"score":8,"studies":[{"title":"Identification of subclinical toxic metal burdens and targeted urinary clearance","url":"https://pubmed.ncbi.nlm.nih.gov/33459740/","notes":"Enables precise targeted removal of bio-accumulated neurotoxic heavy metals through clinical chelators, sauna, or modified citrus pectin."}]}}'::jsonb, functional_outcomes_to_track = '["cellular_detoxification","peace_of_mind"]'::jsonb WHERE id = 'heavy-metals-environmental-toxin-panel';

UPDATE modalities SET functional_impacts = '{"Cancer Early Detection":{"score":10,"studies":[{"title":"Clinical validation of a targeted methylation-based multi-cancer early detection test using an independent validation set (CCGA)","url":"https://pubmed.ncbi.nlm.nih.gov/34174360/","notes":"Annals of Oncology clinical validation in 4,077 participants proving the Galleri cfDNA methylation test detects signals from over 50 cancer types with 99.5% specificity and 89% accuracy in predicting tissue of origin."}]},"Peace of Mind":{"score":9,"studies":[{"title":"Multi-cancer early detection screening in asymptomatic longevity populations","url":"https://pubmed.ncbi.nlm.nih.gov/33459740/","notes":"Screening for asymptomatic genomic shed catches solid tumors at Stage I/II before metastatic dissemination."}]}}'::jsonb, functional_outcomes_to_track = '["cancer_surveillance","peace_of_mind"]'::jsonb WHERE id = 'grail-cancer-screen';

UPDATE modalities SET functional_impacts = '{"Structural Pathology Detection":{"score":10,"studies":[{"title":"Whole-Body MRI Screening in Asymptomatic Subjects: Prevalence of Clinically Relevant Incidental Findings","url":"https://pubmed.ncbi.nlm.nih.gov/31549925/","notes":"Radiology study evaluating comprehensive diffusion-weighted whole-body MRI, detecting actionable solid tumors, silent brain aneurysms, spinal foraminal stenosis, and liver steatosis."}]},"Peace of Mind":{"score":9,"studies":[{"title":"Zero-radiation preventive imaging and longitudinal structural organ tracking","url":"https://pubmed.ncbi.nlm.nih.gov/33459740/","notes":"Provides complete baseline structural anatomy without ionizing radiation, confirming visceral organ health."}]}}'::jsonb, functional_outcomes_to_track = '["pathology_screening","peace_of_mind"]'::jsonb WHERE id = 'full-body-mri-scan';

UPDATE modalities SET functional_impacts = '{"Systemic Anti-Inflammation":{"score":9,"studies":[{"title":"Periodontitis: from microbial dysbiosis to systemic inflammation and arterial plaque disruption","url":"https://pubmed.ncbi.nlm.nih.gov/25421721/","notes":"Nature Reviews Immunology review proving that key red-complex oral pathogens (P. gingivalis, T. denticola) cross into the bloodstream, invading aortic atheromas and accelerating systemic arterial inflammation."}]},"Immune Resilience":{"score":8,"studies":[{"title":"Salivary pathogen screening for targeted periodontal antimicrobial therapy","url":"https://pubmed.ncbi.nlm.nih.gov/17329696/","notes":"Identifies subclinical pathogens so they can be eliminated before seeding heart valves or brain tissue."}]}}'::jsonb, functional_outcomes_to_track = '["immune_resilience","cardiovascular_longevity"]'::jsonb WHERE id = 'oral-microbiome-pathogen-screen';

UPDATE modalities SET functional_impacts = '{"Body Composition Precision":{"score":10,"studies":[{"title":"Dual energy X-ray absorptiometry body composition reference values and visceral adipose tissue measurement","url":"https://pubmed.ncbi.nlm.nih.gov/20041110/","notes":"PLoS One study confirming DEXA provides the clinical gold standard for quantifying android/gynoid fat distribution, appendicular lean mass index, and sub-pound visceral adipose tissue (VAT)."}]},"Bone Mineral Density":{"score":10,"studies":[{"title":"DEXA T-score evaluation and osteopenia / osteoporosis fracture risk prediction","url":"https://pubmed.ncbi.nlm.nih.gov/20041110/","notes":"Provides precise regional bone density across the femoral neck and lumbar spine, guiding targeted axial loading."}]}}'::jsonb, functional_outcomes_to_track = '["body_composition","bone_density","motivation"]'::jsonb WHERE id = 'dexa-body-composition-scan';

UPDATE modalities SET functional_impacts = '{"Biological Pace of Aging":{"score":10,"studies":[{"title":"DunedinPACE, a DNA methylation biomarker of the pace of aging","url":"https://pubmed.ncbi.nlm.nih.gov/35023837/","notes":"eLife paper by Belsky et al. establishing DunedinPACE as a blood DNA methylation algorithm measuring the speedometer of biological aging (years of biological decay per calendar year), validated in the CALERIE calorie restriction trial."}]},"Motivation & Drive":{"score":9,"studies":[{"title":"Longitudinal epigenetic aging speed as a responsive readout for longevity protocol efficacy","url":"https://pubmed.ncbi.nlm.nih.gov/35023837/","notes":"Quantifies whether protocol interventions successfully decelerate aging below 1.0 biological year per chronological year."}]}}'::jsonb, functional_outcomes_to_track = '["biological_age_pace","motivation"]'::jsonb WHERE id = 'dunedinpace-epigenetic-clock';

UPDATE modalities SET functional_outcomes_to_track = '["energy","soreness","strength","endurance"]'::jsonb WHERE id = 'sports-nutrition';

UPDATE modalities SET functional_outcomes_to_track = '["joint_comfort","brain_fog_&_mood"]'::jsonb WHERE id = 'curcumin';

UPDATE modalities SET functional_outcomes_to_track = '["focus","stress","calmness","emotional_resilience"]'::jsonb WHERE id = 'mindfulness-meditation';

UPDATE modalities SET functional_outcomes_to_track = '["energy","soreness","sleep_quality","waking_restedness"]'::jsonb WHERE id = 'recovery-techniques';

UPDATE modalities SET functional_outcomes_to_track = '["vascular_health","inflammaging_reduction"]'::jsonb WHERE id = 'low-dose-aspirin';

UPDATE modalities SET functional_outcomes_to_track = '["focus","stress","calmness","emotional_resilience"]'::jsonb WHERE id = 'mental-fortitude-training';

UPDATE modalities SET functional_outcomes_to_track = '["immune_resilience","skin_&_collagen_resilience"]'::jsonb WHERE id = 'l-lysine';

UPDATE modalities SET functional_outcomes_to_track = '["focus","stress","motivation","productivity"]'::jsonb WHERE id = 'time-blocking';

UPDATE modalities SET functional_outcomes_to_track = '["alertness","sleep_latency","sleep_quality","waking_restedness"]'::jsonb WHERE id = 'evening-screen-time-reduction';

UPDATE modalities SET functional_outcomes_to_track = '["gut_health","joint_health"]'::jsonb WHERE id = 'bone_broth_fast';

UPDATE modalities SET functional_outcomes_to_track = '["focus","ketosis_entry"]'::jsonb WHERE id = 'fat_fasting';

UPDATE modalities SET functional_outcomes_to_track = '["immune_resilience","cardiovascular_health","blood_pressure_control"]'::jsonb WHERE id = 'aged-garlic-extract';

UPDATE modalities SET functional_outcomes_to_track = '["bone_density","vascular_health"]'::jsonb WHERE id = 'genistein';

UPDATE modalities SET functional_outcomes_to_track = '["vascular_health","bone_matrix_health"]'::jsonb WHERE id = 'vitamin-k1';

UPDATE modalities SET functional_outcomes_to_track = '["memory","sleep_latency","sleep_quality","waking_restedness"]'::jsonb WHERE id = 'dark-cool-sleep-environment';

UPDATE modalities SET functional_outcomes_to_track = '["immune_resilience","hormonal_homeostasis","skin_barrier_&_wound_repair"]'::jsonb WHERE id = 'zinc';

UPDATE modalities SET functional_outcomes_to_track = '["bone_matrix_health","arterial_decalcification"]'::jsonb WHERE id = 'vitamin-k2-mk4';

UPDATE modalities SET functional_outcomes_to_track = '["joint_comfort","all-cause_mortality"]'::jsonb WHERE id = 'glucosamine-sulfate';

UPDATE modalities SET functional_outcomes_to_track = '["mood","energy","stress","endurance"]'::jsonb WHERE id = 'running';

UPDATE modalities SET functional_outcomes_to_track = '["focus","calmness","strength","joint_comfort"]'::jsonb WHERE id = 'handstand';

UPDATE modalities SET functional_outcomes_to_track = '["mood","energy","strength","joint_comfort"]'::jsonb WHERE id = 'strength-training';

UPDATE modalities SET functional_outcomes_to_track = '["lifespan_extension","inflammatory_suppression"]'::jsonb WHERE id = 'ndga';

UPDATE modalities SET functional_outcomes_to_track = '["immune_resilience","cardiovascular_health","skin_elasticity_&_quality"]'::jsonb WHERE id = 'vitamin-c';

UPDATE modalities SET functional_outcomes_to_track = '["mood","alertness","sleep_quality"]'::jsonb WHERE id = 'morning-sunlight-exposure';

UPDATE modalities SET functional_outcomes_to_track = '["energy","strength","motivation"]'::jsonb WHERE id = 'dexa_scan';

UPDATE modalities SET functional_outcomes_to_track = '["brain_fog","metabolic_energy"]'::jsonb WHERE id = 'iodine';

UPDATE modalities SET functional_outcomes_to_track = '["physical_energy","endurance_&_stamina"]'::jsonb WHERE id = 'heme-iron';

UPDATE modalities SET functional_outcomes_to_track = '["skin_elasticity","cell_membrane_defense"]'::jsonb WHERE id = 'vitamin-e';

UPDATE modalities SET functional_outcomes_to_track = '["joint_comfort","glycemic_control","digestive_motility"]'::jsonb WHERE id = 'ginger-root';

UPDATE modalities SET functional_outcomes_to_track = '["brain_fog_&_memory","cardiovascular_health"]'::jsonb WHERE id = 'cocoa-flavanols';

UPDATE modalities SET functional_outcomes_to_track = '["autophagy_induction","cardiovascular_longevity"]'::jsonb WHERE id = 'extra-virgin-olive-oil';

UPDATE modalities SET functional_outcomes_to_track = '["prostate_health","cardiovascular_health"]'::jsonb WHERE id = 'lycopene';