-- 0014_add_baseline_hydration_electrolytes.sql
-- Inserts the Baseline Hydration & Mineral Electrolytes modality into the modalities catalog.

INSERT INTO modalities (
  id,
  slug,
  name,
  display_name,
  modality_type,
  category,
  status,
  brief_description,
  expanded_why,
  headline_benefit,
  primary_outcome,
  secondary_outcomes,
  overall_longevity_benefit,
  implementation_summary,
  instructions,
  dose_or_exposure,
  timing_summary,
  frequency,
  schedule_pattern,
  difficulty,
  cost_tier,
  effort_level,
  time_to_benefit,
  evidence_quality,
  effect_size_estimate,
  evidence_summary,
  safety_level,
  safety_summary,
  contraindications,
  functional_outcomes_to_track,
  hallmarks_of_aging_impact,
  mechanism_of_action,
  onset_profile,
  half_life_profile,
  ideal_cohort,
  contraindicating_cohort,
  synergy_notes,
  logging_type,
  visibility
) VALUES (
  'baseline_hydration_electrolytes',
  'baseline-hydration-electrolytes',
  'Baseline Hydration & Mineral Electrolytes',
  'Baseline Hydration + Electrolytes',
  'habit',
  'lifestyle',
  'active',
  'Restore overnight fluid and mineral depletion with 16–20 oz pure water and balanced electrolytes within 30m of waking.',
  'Overnight respiration and transdermal perspiration deplete plasma volume by 300–600 mL, elevating resting blood viscosity and reducing early-morning cardiac stroke volume. Rapid morning hydration with balanced sodium-potassium-magnesium electrolytes re-establishes cellular osmolarity, activates renal sodium-potassium ATPase, and enhances prefrontal cortex perfusion before stimulant exposure.',
  'Rapidly clears overnight cellular dehydration, restores cerebral blood flow, and jumpstarts metabolic alertness.',
  'energy',
  ARRAY['mental_clarity', 'focus', 'physical_fatigue'],
  4,
  'Drink 16–20 oz (500–600 mL) room-temp water with 500mg Na, 200mg K, 60mg Mg upon waking.',
  E'Step 1: Water Preparation — Pour 16–20 oz (500–600 mL) pure filtered water at room temperature (65°F–72°F / 18°C–22°C).\nStep 2: Electrolyte Addition — Add 1/4 tsp Celtic sea salt or full-spectrum electrolyte powder (500mg Sodium, 200mg Potassium, 60mg Magnesium Malate).\nStep 3: Ingestion — Consume steadily over 10–15 minutes upon waking, prior to morning coffee or tea.\nStep 4: Circadian Stack — Pair with morning outdoor sunlight exposure to amplify cortisol awakening response (CAR).',
  '16–20 oz pure water + 500mg Sodium + 200mg Potassium + 60mg Magnesium',
  'Morning (First 30–45 mins upon waking)',
  'Daily',
  'daily',
  'beginner',
  'free',
  'level_1',
  'Immediate (15–30 mins)',
  5,
  'High (+18% cognitive reaction speed, -30% morning grogginess)',
  'PubMed PMID: 30999554 & PMID: 22855911 demonstrate that even 1–2% mild morning dehydration impairs cognitive performance, working memory, and sustained vigilance, which is rapidly reversed by electrolyte-supported rehydration.',
  'low_risk',
  'Completely safe. Individuals with severe renal impairment or sodium-restricted hypertension should adjust electrolyte mineral concentration.',
  ARRAY['Severe chronic kidney disease (CKD stage 4/5) requiring strict fluid restriction.'],
  ARRAY['energy', 'focus', 'mental_clarity'],
  '["Altered Intercellular Communication", "Mitochondrial Dysfunction"]'::jsonb,
  'Cellular osmoregulation, vascular plasma volume expansion, renal Na+/K+-ATPase activation, and cerebral perfusion optimization.',
  '15 minutes',
  '3–4 hours',
  'All individuals seeking optimal morning cognitive clarity, physical endurance, and circadian entrainment.',
  'End-stage renal disease under fluid restriction.',
  '{"pairsWellWith": ["morning_sunlight", "creatine_monohydrate", "delay_caffeine"], "rationale": "Synergizes with Morning Sunlight to clear grogginess and delays caffeine crash by establishing natural hemodynamic stability first."}'::jsonb,
  'completion_only',
  'public'
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  display_name = EXCLUDED.display_name,
  instructions = EXCLUDED.instructions,
  dose_or_exposure = EXCLUDED.dose_or_exposure,
  timing_summary = EXCLUDED.timing_summary,
  evidence_summary = EXCLUDED.evidence_summary,
  updated_at = NOW();
